### ISSUE TITLE
Crash on validation error

### ISSUE THREAD

**Issue by questor** [floooh/sokol#1009]
Hi! It would be great to have the option to crash the program on a validation error as I get error messages, but in a bigger project it's hard to find out where this is coming from (especially because the error message only prints the linenumber from the sokol-header and not from the point where it's called and in the last time there was a bigger change needed in the projects).

If I could crash the program I could easily get a callstack to look where it's coming from....

**Comment by questor** [comment]
ah, the concept is that you first scan all substructures and if in the original call something was bad you assert, right?

**Comment by floooh** [comment]
Yeah exactly, the validation layer 'batches' several validation checks (usually one batch per API call) and then asserts when any of the checks failed. Sometimes it's useful that the first detailed validation doesn't immediately crash because the later validation checks may add useful information, but sometimes it can also be confusing.

In any case, a failed validation check ends up in the log callback with log level panic. If you hook in your own log callback and generate a call stack. Every detailed validation check also calls the log callback when it fails (with log level 'error' instead of 'panic'), and those also have the source file and line number in the log information. So by overriding the log callback you could extract quite a bit of information.
