### ISSUE TITLE
Help using sokol_app with OpenGL on Windows

### ISSUE THREAD

**Issue by GoldenbergDaniel** [floooh/sokol#1047]
I'm not sure how to get OpenGL working with sokol_app on Windows. On macOS, all I need to do is include the GL header file provided by Apple and link against the OpenGL framework. But since windows only provides OpenGL 1.1 support, I assume I have to use a loader (to get them from the GPU driver). My idea is to use GLAD, but I can't find any function that returns the loader for gladLoadGLLoader to use. Any help would be much appreciated.

**Comment by GoldenbergDaniel** [comment]
I found that OpenGL loading was moved out of sokol_app, so just calling gladLoadGL worked well for me.

**Comment by floooh** [comment]
An external GL loader or GL headers are not needed on Windows both for sokol_app.h and sokol_gfx.h since both headers are coming with their own GL loaders on Windows which are enabled by default (but can be disabled).

What types of problems were you seeing, and are you sure you didn't accidentially define `SOKOL_EXTERNAL_GL_LOADER`?

**Comment by floooh** [comment]
...ah I think I understand. You are probably using sokol_app.h with your own GL functions, and expect that sokol_app.h loads the GL headers for you. Yep, that's indeed not the case on Windows. You'll have to use a GL loader.

Here's an example where I'm doing somthing similar (call directly into GL functions). In that case I use flextGL as GL loader (and disable sokol_gfx.h's GL loader):

https://github.com/floooh/sokol-samples/blob/master/glfw/multiwindow-glfw.c
