### ISSUE TITLE
Offscreen with alpha background. Is it possible?

### ISSUE THREAD

**Issue by eduardodoria** [floooh/sokol#1064]
I`m trying to make an 3D UI using render-to-texture, but I cannot do with transparent background.

This is the result without transparency:
![Captura de tela de 2024-06-17 16-33-34](https://github.com/floooh/sokol/assets/11426911/98e77750-eff0-43c8-8962-4e99180eeb64)

After doing alpha 0.5 in clear_value `pass_action.colors[0].clear_value = { 0.8, 0.8, 0.8, 0.5 }`:
![Captura de tela de 2024-06-17 16-34-04](https://github.com/floooh/sokol/assets/11426911/545f0a3e-c2e9-4c50-afa1-72ebf1349e1a)

Now, after doing in RTT pipeline `pip_rtt_desc.colors[0].write_mask = SG_COLORMASK_RGBA`:
![Captura de tela de 2024-06-17 16-35-01](https://github.com/floooh/sokol/assets/11426911/30873129-c1a0-4b0f-8aed-d3825435e840)

The last one is almost result I want, but transparent UIs (text) is getting wrong background even if drawed last than others.

**Comment by eduardodoria** [comment]
Thank you. I got the results I want but with little different settings.

> * I would first clear the render target to alpha value 0.0 instead of 0.5

I don't understant why you said this because I don't want full transparent background, so I keep aplha with 0.2.


> ```c
>         .src_factor_alpha = SG_BLENDFACTOR_ZERO,
>         .dst_factor_alpha = SG_BLENDFACTOR_ONE,
> ```

If I use this settings the result is the same:
![Captura de tela de 2024-06-18 09-34-04](https://github.com/floooh/sokol/assets/11426911/e1b63c6c-2a4b-4cd8-928a-848ded3b92fc)



But I changed to this:

> ```c
>         .src_factor_alpha = SG_BLENDFACTOR_ONE,
>         .dst_factor_alpha = SG_BLENDFACTOR_ONE,
> ```

And now I get this result:

![Captura de tela de 2024-06-18 09-33-21](https://github.com/floooh/sokol/assets/11426911/e8dc79ad-c228-4025-b83b-9fe2c1d3b3db)

**Comment by floooh** [comment]
Hmm ok, ONE/ONE basically adds the alpha from the window background pixel shader on top of the alpha from the render target, that works too and is even better if your window backgrounds should be semi-transparent (and maybe you can even use the same shader for the text then).

What I had in mind was to not use any alpha blending at all when rendering the window background into the render target, but instead directly write an alpha value of 1.0 (and only use the ZERO/ONE alpha blend factors for the text) - but yeah, your solution might indeed be better and simpler.

I'll close the ticket since it looks like the issue is resolved :)

**Comment by eduardodoria** [comment]
Based on this reference https://stackoverflow.com/a/18497511/6089705:

> the FBO contains colour already multiplied with the alpha channel, so instead of doing that again with GL_SRC_ALPHA, it is drawn with GL_ONE. The destination colour is attenuated normally with GL_ONE_MINUS_SRC_ALPHA.

So, I think for better result I should blend alpha with:

```c
        .src_factor_alpha = SG_BLENDFACTOR_ONE,
        .dst_factor_alpha = SG_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,
```
