### ISSUE TITLE
Question: pool sizes?

### ISSUE THREAD

**Issue by amerkoleci** [floooh/sokol#107]
Hi,

I saw you have defined pool sizes for buffers, shaders, pipelines, this is ok if user knows number of thoose, but immagine in full game engine there can be stuff created from scripting etc.

I would suggest to use the vulkan type handle logic, basically you will have SG_DEFINE_HANDLE macro and forward declare struct when allocating:

SG_DEFINE_HANDLE(sg_buffer);

Then in lets say OpenGL backend you will have:
typedef struct sg_buffer_handle {
   GLuint buffer;
}

**Comment by floooh** [comment]
Some reason why this doesn't work:

- sokol resources don't always map 1:1 to 3D API resources (e.g. a dynamic sg_buffer actually has 2 GL buffers underneath, or a D3D11 pipeline object has a small number of D3D11 objects.
- some resource types need to reference other resources (e.g. the pipeline object needs to access "private" sokol-specific data in the shader object, same with passes and images)
- the resource id handles have a unique-tag in the upper bits for dangling protection
- sokol needs to associate a resource state with each resource (Initial, Allocated, Valid, Failed), because it will only draw resources in the Valid state.

The pool sizes can be set very generously though, the preallocated sizes per pool-slot for each resource type are (with the Metal backend):

- buffer: 56 bytes
- image: 104 bytes
- shader: 172 bytes
- pipeline: 144 bytes
- pass: 136 bytes

So the preallocated size is a lot smaller than the vertex- or image-data those resources would contain (and those are only allocated when the resource is actually created, and freed when a resource is destroyed). And I haven't been very picky about those sizes. With a bit of effort those could be made smaller (but again, compared to the sizes of the underlying 3D-API resources, this won't make much of a difference).
