### ISSUE TITLE
Storage buffer example broken

### ISSUE THREAD

**Issue by creikey** [floooh/sokol#1098]
![image](https://github.com/user-attachments/assets/79ed6cd7-3593-44a5-a475-21f42c4f2bc7)
I'm seeing this on macOS on brave and safari browser, this was working so I think something broke? This is on this URL: https://floooh.github.io/sokol-html5/ozz-storagebuffer-sapp.html

**Comment by floooh** [comment]
You're running the WebGL version, and unfortunately WebGL2 has no storage buffers since it implements the GLES3.0 API, you'd need to run the WebGPU version:

https://floooh.github.io/sokol-webgpu/ozz-storagebuffer-sapp.html

(on Safari this requires the Technology Preview versions, and I think WebGPU also needs to be enabled first).
