### ISSUE TITLE
Discord or some kind of community chat kind of thing?

### ISSUE THREAD

**Issue by SabeDoesThings** [floooh/sokol#1099]
Hey I wasn't really sure if there was like a discord or something for sokol to ask questions or chat. Is there really not a discord anything similar for sokol? I'm guessing not because I couldn't really find anything. If there isn't a discord or anything how else could I ask questions if I am stuck on anything?

**Comment by floooh** [comment]
Just ask here, in an issue. If it gets too overwhelming I'll probably open the Github Discussion and Wiki tabs so that others can hop in.

**Comment by SabeDoesThings** [comment]
Ok. I think Github discussion could be cool. The main thing I'm struggling with right now is just setting up. I am a bit confused.

**Comment by floooh** [comment]
You can check these projects as example, those are pure cmake projects and don't depend on my fips build system like the sokol-samples:

- https://github.com/floooh/pacman.c

- https://github.com/floooh/qoiview

- https://github.com/floooh/cimgui-sokol-starterkit

This section in the sokol-samples readme might also be useful:

https://github.com/floooh/sokol-samples?tab=readme-ov-file#how-to-build-without-a-build-system

**Comment by MrCheeseWasTaken** [comment]
I think a place to discuss small things would be helpful. Like somethings are just a bit too niche (Like rn I trying to see how to display a layer of a sg_image using imgui and can't find anything) and posting it on the issues page on github feels like a bit too much. I really do think having a Discord can help a lot, just to at least answer the smaller, basic features for people who are new

**Comment by epouv** [comment]
I'd like to up this idea, a discussion space of some kind would be nice. I'd love to see what people are doing with this wonderful library, and being able to share what I've been creating with it would be great.
That being said i know managing a community on multiple websites/apps is a lot of extra work. I'm not a big fan of discord personally, but I don't know if there's any options for doing this without efforts..

**Comment by tacf** [comment]
I'm experiencing the same need to quickly iterate question with possibly other users instead of bottle necking everything on @floooh . Unless you're really not up for the ideia i could help you set up something @floooh 

Edit: Tipically at some point in growth these communities tend to form either way. With 'help' i mean on the setup/config/maintenance where you still have full control/ownership of it (just to be clear, no weird need to be anything else then a helper). I don't actually enjoy the work i just feel that you have something here that's gaining some traction and communities may help push even further both by feedback and contributions.
