### ISSUE TITLE
Questions about GFX API

### ISSUE THREAD

**Issue by munrocket** [floooh/sokol#1106]
Thank you for a great library. I am considering to use Sokol instead of Dawn, because it is small and simple.
1) Compute support is planned. Will it support float-f16, atomics and subgroups(except nvidia)?
2) Sokol designed with wasm as _first-class citizen_. Why not WGSL? It will be hard to use Tint as offline WGSL->GLSL compiler for my own project? There are only one @glsl_options?
3) It will be helpful to share best practices for binding groups according to frequency of change, like in [webgpu-best-practices](https://toji.dev/webgpu-best-practices/bind-groups.html#grouping-resources-based-on-frequency-of-change). Also Attributes/buffers have third level of nesting.
```c
    state.pip = sg_make_pipeline(&(sg_pipeline_desc){
        .shader = sg_make_shader(triangle_shader_desc(sg_query_backend())),
        .layout = {
            .attrs = {
                [ATTR_vs_position].format = SG_VERTEXFORMAT_FLOAT3,
                [ATTR_vs_color0].format = SG_VERTEXFORMAT_FLOAT4
            }
            .buffers[0].stride = 24
        },
    });
```
instead of 
```c
    state.pip = sg_make_pipeline(&(sg_pipeline_desc){
        .shader = sg_make_shader(triangle_shader_desc(sg_query_backend())),
        .layout_attrs = {
             [ATTR_vs_position].format = SG_VERTEXFORMAT_FLOAT3,
             [ATTR_vs_color0].format = SG_VERTEXFORMAT_FLOAT4
        },
        .layout_buffers[0].stride = 24
    });
```
As I understand all this structs will be additional garbage collected class, if I using FFI with GC language? Anyway I don't have strong opinion here.

**Comment by floooh** [comment]
> Compute support is planned. Will it support float-f16, atomics and subgroups(except nvidia)?

I don't know the complete compute feature set yet, but in general, only features will be supported that work across D3D11, GL 4.3+ core profile (e.g. without extensions), Metal and WebGPU. I typically look at WebGPU and then check what additional restrictions apply for GL.

> Why not WGSL?

You can feed WGSL directly into sokol_gfx.h, but only if the WebGPU backend is used (e.g. see: https://github.com/floooh/sokol-samples/tree/master/wgpu). I haven't evaluated Tint deeply enough yet to decide if it can be complete replacement for SPIRVCross. WGSL *may* be supported as cross-backend shader authoring language at some point in the future,but don't hold your breath.

As for your third point: the additional nesting doesn't have any runtime cost since the structs are nested and not dangling off.. The entire `sg_pipeline_desc` is a single blob on the stack (WebGPU is actually less efficient in that regard for many desc structs).
