### ISSUE TITLE
Metal: avoid presentDrawable on sg_end_pass()

### ISSUE THREAD

**Issue by tanis2000** [floooh/sokol#1123]
Is it on purpose that `sg_end_pass()` calls `presentDrawable` on Metal? That means that multiple pipelines writing to the framebuffer will also swap the drawable and present the result on screen during each frame.

I was wondering if this is "by design" so that you are forced to write to an off-screen texture and then only plot the final texture on the framebuffer or if it is a misbehavior.

Thanks! :)

**Comment by floooh** [comment]
It's by design, I seem to remember that presentDrawable was in the `sg_commit()` call before, but that had to move into `sg_end_pass` in the 'render pass cleanup' update which dropped the concept of a default pass and allowed to render into multiple swapchain surfaces per frame.

In general you should only have a single render pass per 'render destination' in a frame, and never have multiple render passes into the same render target (think of a render pass as a node in a dependency tree of dependent render targets, and not as a group of related draw calls).

**Comment by tanis2000** [comment]
Yes, it was in `sg_commit()`, true. I get where this is coming from, but then how would you apply different blending modes when rendering to the same swapchain. I have a simple use-case where all the sprites of a game are drawn to a render target and then the render target is drawn on the swapchain as a simple quad and then on top of it, I draw the debui IMGUI stuff using blending to support transparency (and the debug IMGUI is rendered at the same resolution as the swapchain, while the game sprites are rendered at a smaller VGA-like resolution)

**Comment by floooh** [comment]
> but then how would you apply different blending modes when rendering to the same swapchain

You can all do this in the same pass, no? First apply a pipeline with alpha blending disabled, do some drawing, then apply a pipeline with alpha enabled and do all drawing that requires alpha blending. All within the same begin/end pass.

**Comment by tanis2000** [comment]
You are totally right. I was mixing up the passes and pipelines. For some reason I tightly coupled the pass to a single pipeline, silly me!

**Comment by floooh** [comment]
PS: I edited the comment with a code example while you already responded :)
