### ISSUE TITLE
Upside down render target

### ISSUE THREAD

**Issue by leiradel** [floooh/sokol#1129]
My render code is as discussed here: https://github.com/floooh/sokol/issues/1120

Both Windows and Android ports use the exact same code, and also they both use sokol_app and sokol_gl. However, while on Windows the render target (the little rectangle with Manic Miner) is ok, on Android it's upside down. The background is an image loaded from disk into a texture, and it renders correctly in both cases.

* Background is loaded from disk
* Background is rendered to the display framebuffer
* Emulator software framebuffer is used to update a stream texture, and is rendered to a render target
* The render target is rendered to the display framebuffer

This is my texture class:

```cpp
class SokolTexture : public rm::renderer::Texture {
public:
    SokolTexture(long const width, long const height, Usage const usage, void const* pixels)
        : rm::renderer::Texture(width, height) {
        RM_DEBUG("Creating texture with %ld x %ld pixels", width, height);

        if (usage == Usage::Static && pixels == nullptr) {
            RM_FATAL("Static textures must provide initialization data");
            return;
        }

        sg_image_desc desc = {};

        desc.width         = static_cast<int>(width);
        desc.height        = static_cast<int>(height);
        desc.pixel_format  = SG_PIXELFORMAT_RGBA8;
        desc.sample_count  = 1;

        switch (usage) {
        case Usage::Static:  desc.usage = SG_USAGE_IMMUTABLE; break;
        case Usage::Dynamic: desc.usage = SG_USAGE_DYNAMIC; break;
        case Usage::Stream:  desc.usage = SG_USAGE_STREAM; break;
        }

        if (usage == Usage::Static) {
            desc.data.subimage[0][0].ptr  = pixels;
            desc.data.subimage[0][0].size = width * height * 4;
        }

        _texture = sg_make_image(&desc);

        if (sg_query_image_state(_texture) != SG_RESOURCESTATE_VALID) {
            RM_FATAL("Failed to create texture");
            return;
        }

        if (usage != Usage::Static && pixels != nullptr) {
            update(pixels);
        }
    }

    ~SokolTexture() {
        sg_destroy_image(_texture);
    }

    void update(void const* pixels) override {
        sg_image_data data       = {};
        data.subimage[0][0].ptr  = pixels;
        data.subimage[0][0].size = _size.width() * _size.height() * 4;

        sg_update_image(_texture, &data);
    }

    sg_image _texture;
};
```

And this is my render target class:

```cpp
class SokolRenderTarget : public rm::renderer::RenderTarget {
public:
    SokolRenderTarget(long const width, long const height) : rm::renderer::RenderTarget(width, height) {
        RM_DEBUG("Creating render target with %ld x %ld pixels", width, height);

        {
            sg_image_desc desc = {};

            desc.render_target = true;
            desc.width         = width;
            desc.height        = height;
            desc.pixel_format  = SG_PIXELFORMAT_RGBA8;
            desc.sample_count  = 1;

            _target = sg_make_image(&desc);

            if (sg_query_image_state(_target) != SG_RESOURCESTATE_VALID) {
                RM_FATAL("Failed to create frame buffer image");
                return;
            }
        }

        {
            sg_attachments_desc desc = {};
            desc.colors[0].image = _target;

            _attachments = sg_make_attachments(&desc);

            if (sg_query_attachments_state(_attachments) != SG_RESOURCESTATE_VALID) {
                RM_FATAL("Failed to create frame buffer attachments");
                return;
            }
        }

        {
            sgl_context_desc_t desc = {};

            desc.color_format = SG_PIXELFORMAT_RGBA8;
            desc.depth_format = SG_PIXELFORMAT_NONE;
            desc.sample_count = 1;

            _context = sgl_make_context(&desc);

            if (_context.id == SG_INVALID_ID) {
                RM_FATAL("Failed to create frame buffer context");
                return;
            }
        }
    }

    ~SokolRenderTarget() {
        sgl_destroy_context(_context);
        sg_destroy_attachments(_attachments);
        sg_destroy_image(_target);
    }

    sg_image       _target;
    sg_attachments _attachments;
    sgl_context    _context;
};
```

Windows screen shot:

![windows](https://github.com/user-attachments/assets/6858d035-4d28-47aa-a209-b4e4076d6460)

Android screen shot:

![android](https://github.com/user-attachments/assets/13d9ead7-9be5-4ecf-9a2c-93bc11e9935e)

Any help is appreciated.

**Comment by floooh** [comment]
I guess the Windows version uses the D3D11 backend? (and Android GL).

sokol-gfx basically cannot hide all the differences between the backend APIs, and one of those is the 'upside down' texture coordinate system on OpenGL. This little details pretty much only matters when rendering into an offscreen texture and then rendering this texture to the screen.

If you use sokol-shdc, this has a meta-tag to patch up the vertex shader via SPIRVCross, this is for instance used in the mrt-sapp sample (check out the `@glsl_options flip_vert_y` here in the vertex shader for the 'fullscreen quad' which renders the offscreen texture content to the screen:

https://github.com/floooh/sokol-samples/blob/0502fa1fb840e502235518af94e7ab27b7a7adb3/sapp/mrt-sapp.glsl#L43

...the other option is to check `sg_query_features().origin_top_left` and do the y-flip youself. That's what I'm doing in my emulators for instance (since those also require 90 degree display rotation for arcade machine anyway).

I have vertex data for each possible display layout (y-flip and portrait vs landscape):

https://github.com/floooh/chips-test/blob/0387d452f521567af6447be1907dc111de39d4a5/examples/common/gfx.c#L57-L80

...and then I decide which one to use like this:

https://github.com/floooh/chips-test/blob/0387d452f521567af6447be1907dc111de39d4a5/examples/common/gfx.c#L322-L329

**Comment by floooh** [comment]
Hmm, do you render the background with the same rectangle drawing routine as the emulator output? 

The UV flip should only happen for the rectangle that renders the emulator rectangle.

**Comment by leiradel** [comment]
You mean only if I render to a render target? Something like this?

```cpp
if (sg_query_features().origin_top_left && renderingToRenderTarget) {
    // flip v
}
else {
    // don't flip v
}
```

**Comment by leiradel** [comment]
I tried to do that for both render targets and the display framebuffer, and the render target continued to be upside-down, but the regular texture also turned upside-down! So it didn't fix the problem, and created a new one xD

**Comment by floooh** [comment]
Ah, don't flip when rendering *to* a render target, only when rendering the render target to the screen.

In your scenario, you should only flip in a single draw call, when rendering the render target texture to the screen.

Also I think you need to flip when origin_top_left is false, not when it's true.

I would write two draw-rect functions tbh, one that looks like before, and one that checks the `origin_top_left` feature flag and if that's false renders a flipped rectangle (and otherwise regular)... and then figure out where to put the draw-rect function call which optionally flips :) It should only be in a single place.

**Comment by leiradel** [comment]
Ah nice, flipping y when drawing the render target to the screen when `sg_query_features().origin_top_left` is false fixed it! Thanks!
