### ISSUE TITLE
sokol_app Win32: need to throttle frame update calls when window is minimized

### ISSUE THREAD

**Issue by Oldes** [floooh/sokol#113]
While trying the `events-sapp.c` example, I noticed, that the information of `frame-counter` gives too high results after restoration from minimized state:
```
MOUSE_MOVE      frame_count:434 modifiers:0 mouse_x:280.00 mouse_y:0.00
UPDATE CURSOR frame_count:434
MOUSE_MOVE      frame_count:434 modifiers:0 mouse_x:281.00 mouse_y:0.00
UPDATE CURSOR frame_count:437
MOUSE_MOVE      frame_count:437 modifiers:0 mouse_x:279.00 mouse_y:0.00
UPDATE CURSOR frame_count:437
MOUSE_MOVE      frame_count:437 modifiers:0 mouse_x:280.00 mouse_y:0.00
MOUSE_LEAVE     frame_count:440 modifiers:0 mouse_x:280.00 mouse_y:0.00
ICONIFIED       frame_count:517 win_width:400 win_height:300 fb_width:400 fb_height:300
RESIZED         frame_count:517 win_width:0 win_height:0 fb_width:1 fb_height:1
RESTORED        frame_count:41564 win_width:0 win_height:0 fb_width:1 fb_height:1
RESIZED         frame_count:41564 win_width:400 win_height:300 fb_width:400 fb_height:300
```

**Comment by floooh** [comment]
Hi, what OS is this?

Looks like the app isn't throttled to the refresh rate when minimized (e.g. on Mac I can't reproduce this with the Metal backend).

Looks like I need to add some manual throttling when the window is minimized, depending on platform (behaviour is fairly "undefined" though, e.g. when running in the browser, the app may not be updated at all when the tab is switched to the background, this may give unexpected long frames when measuring the time between frames).

**Comment by floooh** [comment]
Ok, I can reproduce the behaviour on Windows. I'll try to come up with a short-term fix which throttles the rate at which the frame callback is called when minimized to some sane value.

Later it might make sense to have a config item in sapp_desc which says how the app should behave when switched to the background or minimized (e.g. don't call the frame callback at all, or at a very reduced rate, etc...).

**Comment by floooh** [comment]
...ok some more testing, it only happens with the D3D11 code path, the GL seems to be fine (at least from looking at the CPU usage graph. In D3D11 it goes way up when the window is minimized because it runs unthrottled, GL stays down.

I'll add a fix/hack for now that I put the process to sleep for (1.0/60.0*swap_interval) secs for now (without taking the execution time of the sokol-app frame callback into account. This will at least fix the high CPU usage and frame rate going amok, but a better fix will be to provide a hint what should actually happen when the window is minized (I think best is to not call the frame callback at all, or at a much lower rate when the application needs to do some "background processing".
