### ISSUE TITLE
sokol-nuklear cursors

### ISSUE THREAD

**Issue by dlannan** [floooh/sokol#1130]
I have been looking at using nuklears builtin cursors, so I disable the sapp cursor, and try to enable the nuklear ones but I think the nuklear context overlay isnt getting rendered to?
And it seems that ```ctx->style.cursor_active``` is null. 
I will investigate to see how this should occur. 

Current tests are on win11 + OpenGL rendering, and Im using the luajit version (so there may be some mem alloc nuances causing this)

I believe a good fix is adding the baked cursors after the line util/sokol_nuklear.h line 2154
https://github.com/floooh/sokol/blob/4bda1469d3b311af03a34dd956460776c920dc2e/util/sokol_nuklear.h#L2154

```nk_style_load_all_cursors(&_snuklear.ctx, &_snuklear.atlas.cursors);```

This loads in the default baked cursors into the ctx style, and then they seem to operate correctly. 
I would add a PR, but my fork is a bit of a mess atm :)

**Comment by floooh** [comment]
I haven't looked into Nuklear's cursors yet, but if Nuklear has a similar approach as Dear ImGui (e.g. "cursor types" instead of custom cursor images) you could look at how sokol_imgui.h is glued to sokol_app.h:

E.g. in sokol_app.h you can set a cursor type:

```c
void sapp_set_mouse_cursor(sapp_mouse_cursor cursor);
```

...where `sapp_mouse_cursor` is:

https://github.com/floooh/sokol/blob/4bda1469d3b311af03a34dd956460776c920dc2e/sokol_app.h#L1760-L1778

...these are common hardwired mouse cursor types supported by operating systems and browsers.

...this is then hooked up to Dear ImGui like this:

https://github.com/floooh/sokol/blob/4bda1469d3b311af03a34dd956460776c920dc2e/util/sokol_imgui.h#L2546-L2566

...supporting completely custom mouse cursors will be tricky, unless Nuklear renders its own software cursor (which IMHO isn't a good option, because that will have very visible lag).

**Comment by dlannan** [comment]
Nuklear embeds its cursors into the font atlas (hence my simple solve above :) ). 
And more importantly the cursor control is part of the nuklear event routine. It means if you use a native cursor it always looks like it is lagging (similar happens with imgui). In nuklear if you use their internal one, it is pixel accurate and in sync with all window/widget movements (imho looks alot cleaner). 
And it should be accel, as long as the backend nuklear implementation is sending fonts to render via vert buffers etc. 

For reference, I have a long timeline for a 3D movie like editor and the cursor (see pic). If I use native cursor it leads the cursor significantly (because of the frame loop - ie, native mouse moves before rendering). When I switch to use the nuklear one (by changing what I showed above) it is extremely clean and no lead/lag. I can provide vid to help clarify if needed.

And notes on why I use nuklear: Imgui has a _huge_ messy api and some very limiting rendering mechanisms (mostly in drawing) and its theming is also limited. With Nuklear I find the theming and general usability far more easy to create complicated ui's while still being very lightweight. 
https://forum.defold.com/uploads/default/original/3X/5/3/530aec2f33338d73c6ec07a7e6157586878f469f.jpeg

**Comment by floooh** [comment]
> It means if you use a native cursor it always looks like it is lagging (similar happens with imgui)

A 'pixel perfect' software rendererd cursor will lag even more though because of the additional lag introduced by the swapchain. Yes, it will be "connected" to dragged UI elements, but the mouse movement itself will feel laggy because the displayed render content lags behind up to several frames while rendered surfaces are in flight.

Hardware mouse cursors are rendered as sprites/hw-surfaces and are independent from the swapchain surface content.

But yes, if it's a small fix than PRs are welcome :)

**Comment by dlannan** [comment]
> A 'pixel perfect' software rendererd cursor will lag even more though because of the additional lag introduced by the swapchain. Yes, it will be "connected" to dragged UI elements, but the mouse movement itself will feel laggy because the displayed render content lags behind up to several frames while rendered surfaces are in flight, waiting to be presented.

Yep. But I disagree with your assessment. Because the mouse cursor only moves based on mouse event changes - there is no "native" visible cursor, and so there is no perception of lag because the movement is matching the active mouse events. The only time this becomes apparent is when you enter and exit the window (where the cursor might switch). Otherwise the user, simply cant tell. 

Native cursors are fine if you are working with native OS elements. But if you try to use native with even imgui, the visual artifacts can be extremely frustrating for the user (especially for pixel accuracy, and slider/drag movements). Most games, simulators and applications I've been involved with, you do the same thing. Internal coord's are nearly always used especially if you are rendering the ui.

**Comment by floooh** [comment]
Closing since https://github.com/floooh/sokol/pull/1138 has been fixed :)
