### ISSUE TITLE
sokol_gfx : dynamic buffer cannot be updated more than one time per frame

### ISSUE THREAD

**Issue by eloraiby** [floooh/sokol#114]
Is this intentional for dynamic buffers ? Not sure about Metal, but both D3D11 and OpenGL supports it.

**Comment by floooh** [comment]
See the sg_append_buffer() function for a way to append buffer content and interleave this with draw calls multiple times in a frame, see the imgui samples for an example:

https://github.com/floooh/sokol-samples/blob/4db6ebaefaaacedcb4ef9e8d2c5faaf8f5ae45fd/sapp/imgui-sapp.cc#L284-L321

The reason for the fairly limited update behaviours is basically that this guarantees that no lock-stalls happen where the CPU needs to wait for the GPU, and this is tricky to get right across all backend APIs without things like explicit double buffering (this is done in the GL and Metal backend, while the D3D11 backend uses MAP_WRITE_DISCARD (for sg_update_buffer) and MAP_WRITE_NO_OVERWRITE (for sg_append_buffer).

On GL, explicit double buffering is used (mainly because of WebGL because this doesn't allow buffer-orphaning (see for instance: https://www.khronos.org/opengl/wiki/Buffer_Object_Streaming).

Metal also uses double buffering, one buffer is rendered while the other is free to be updated, and the role switches in the next frame.
