### ISSUE TITLE
Odin Bindgen Type Mismatches

### ISSUE THREAD

**Issue by Barinzaya** [floooh/sokol#1157]
Some of the primitive types don't match when generating Odin bindings. The current types seem to be matched to 64-bit platforms specifically. Namely:

* `intptr_t` is currently `i64`, but [`core:c` currently uses `int`](https://github.com/odin-lang/Odin/blob/master/core/c/c.odin#L71).
* `uintptr_t` is currently `u64`, but should map to [`uintptr`](https://github.com/odin-lang/Odin/blob/master/core/c/c.odin#L72).
* `size_t` is currently `u64`, but should map to [`uint`](https://github.com/odin-lang/Odin/blob/master/core/c/c.odin#L21).

Alternatively, perhaps their aliases from `core:c` should be used instead to ensure compatibility.

**Comment by floooh** [comment]
Thanks, do you want to provide a PR? I think the change would only affect this mapping table:

https://github.com/floooh/sokol/blob/2c6fc7470e9b9121a178e6e68c55f2f06fac4647/bindgen/gen_odin.py#L94-L111

Since the C `int` type is already mapped to `c.int` I guess it's fine to map the intptr_t, uintptr_t and size_t types also to their respective `c.*` types.

**Comment by Barinzaya** [comment]
Will do. Looks like the first argument of `helpers.Allocator`'s `alloc_fn` is also affected, and changing the mapping in the bindgen doesn't seem to affect that one. I guess that's manually-written? I'll update it too; I guess that means a separate PR on `sokol-odin`.

**Comment by Barinzaya** [comment]
Made a PR with the helpers change separate from the bindgen updates. I can add the bindgen changes in if preferred.
