### ISSUE TITLE
hook position in _destroy_ functions

### ISSUE THREAD

**Issue by septag** [floooh/sokol#134]
Is it possible if sokol could call hook callbacks at the beginning of  destroy_xxx functions ?   
the reason is maybe the hook function wants to query the buffer data and extract some information from it before destroy. Like for example, keeping track of allocated buffer sizes and wants to access the `buf->size`

**Comment by floooh** [comment]
Yes good idea. I also started with the steps necessary to make the sokol_gfx_imgui.h header a normal "addon" header that no longer depends on the sokol_gfx.h implementation (only on public structs and functions):

https://github.com/floooh/sokol/commit/e90adb49824f9c11c0a497f1d26e810255e9c60a

**Comment by septag** [comment]
nice, I will check it out
thank you!

**Comment by septag** [comment]
on the side note, I don't think the problem with accessing internal sokol_gfx state by sokol_imgui gonna be solved easily. because there are lots of different internal data access there, like `cur_pipeline` and object pools. Also object data like `_sg_buffer_t` needs their API specific definition to work correctly, so I guess we still need to have the correct sokol api implementation with imgui.

Currently, I solved mine by having the exact same sokol implementation in the _imgui plugin_ and pass the `_sg_state_t*` to `sg_imgui_init` function, it's not perfect but it works

**Comment by floooh** [comment]
I think it's worth solving though. sokol_gfx_imgui.h may mirror some things (like keeping track of cur_pipeline itself, instead of accessing sokol_gfx.h internal state).

I'll work towards this, and see how it goes. I have a couple of related things in mind that would clean up some internal details sokol_gfx.h, so even if the whole thing doesn't work out it's still not wasted time ;)
