### ISSUE TITLE
WM_MOUSEHWHEEL not found on _WIN32_WINNT < 0x0600

### ISSUE THREAD

**Issue by septag** [floooh/sokol#138]
apparently (at least on my rig) .. WM_MOUSEHWHEEL throws error when building with windows x86 sdk.  (happens wnen _WIN32_WINNT < 0x0600)
I haven't found any documentation regarding this. But I could fix it with:

```c
#ifndef WM_MOUSEHWHEEL
#define WM_MOUSEHWHEEL                  0x020E
#endif
```

**Comment by floooh** [comment]
...hmm how strange, according to here:

https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-mousewheel

WM_MOUSEWHEEL exists since Win2k, so it should work at least back to WinXP (I guess 0x0600 is Win2k, and 0x0601 is WinXP).

If this is the only problem I guess it's fine to define the macro in sokol_app.h, no problem :)

**Comment by floooh** [comment]
PS: the right value is 0x020A, not 0x020E right?

**Comment by septag** [comment]
Actually I'm trying to build it with msvc 2015 - update 3 (windows sdk: 10.0.10240.0) - Win32 platform.
Yeah it was strange to me too. I'll try to build it with another setup too and see if brings up the same err.

btw, I got the value from [here](https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-mousehwheel)

**Comment by floooh** [comment]
Hmm... nevermind, I'm an idiot :D 

I didn't notice the subtle 'H' (WM_MOUSEWHEEL vs WM_MOUSEHWHEEL) that also explains the confusion, WM_MOUSEHWHEEL was only introduced in Vista. My fix is wrong, one sec...
