### ISSUE TITLE
blend-state enhancement

### ISSUE THREAD

**Issue by questor** [floooh/sokol#143]
Hi,
first: many thanks for your tiny layer, just what I needed! 

But for my projects I want to be able to set the factors of the blend state operation in the gl-emulation-layer (sokol_gl). Do you want to implement it yourself or should I create a pull-request?
Another idea could be not to create specific routines to set these arguments, but to create some sort of "generic callback" which can set the pipeline into the right state (does this make sense in the design of sokol? I'm too new to understand currently the complete design).

**Comment by floooh** [comment]
Hi, do you mean the blend factors set via glBlendFunc() (https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBlendFunc.xhtml)?

These are set in sg_pipeline_desc.blend.src_factor_rgb, dst_factor_rgb, src_factor_alpha and dst_factor_alpha when creating a sg_pipeline object.

For different blend factor combinations, you would create additional sg_pipeline objects, and then switch between them as needed via sg_apply_pipeline() during rendering.

A callback probably wouldn't make much sense because it wouldn't be compatible with the other 3D API backends, while OpenGL allows to change any granular render state at any time (at the cost of additional hidden background work to update the internal render pipeline state), the other 3D API backend only to allow changing entire state groups at once (that's why all render state is "baked" into pipeline objects).

You can check the "blend" sample here for an example:

https://floooh.github.io/sokol-html5/wasm/blend-sapp.html

Each of the colored quads is a different blending operation, each encoded in a different pipeline object.

**Comment by floooh** [comment]
PS: if you absolute need to set the blend factors without creating additional pipeline state objects, and you only care about OpenGL, you can also call glBlenFunc() (glBlendFuncSeparate()) directly somewhere between sg_apply_pipeline() and sg_draw(), just make sure that you call sg_reset_state_cache() somewhere before the next sg_apply_pipeline(), this will be slower though than creating separate pipeline object (the OpenGL backend has a state cache which only executes the minimal number of GL functions needed to transition from the previous pipeline state to the new pipeline state when sg_apply_pipeline() is called)

**Comment by floooh** [comment]
Oh shit, wait I completely misread your ticket (I was reading sokol_gfx instead of sokol_gl, it's quite late here...).

Ok yes. Makes sense. The only problem is "combinatorial explosion" with the current "dumb" pipeline object cache here:

https://github.com/floooh/sokol/blob/82346ae0365a3b1157e2ddce591a2d01087316a1/util/sokol_gl.h#L1085

There are around 15 blend factors (sg_blend_factor), we'd need 8 additional bits for the src/dst factor combinations, so with the current 6 bits that's 14 bits so if all blend factor combinations would be supported that array size would need to grow from 64 entries to 16384 entries.

Maybe a small subset would make sense?

I'll need to sleep about that, and I'm open for ideas ;)

**Comment by floooh** [comment]
...the other idea with setting the render state directly also sounds interesting... sokol_gl.h could offer a 
sgl_apply_pipeline() method which would allow to set a sokol-gfx pipeline directly, but this must be created in a way that it is compatible with sokol-gl (the vertex layout must match, and the pixel formats and sample count)...  This could be done by offering another 'wrapper function' ```sg_pipeline sgl_make_pipeline(sg_pipeline_desc*)```, this would work like the sokol_gfx.h sg_make_pipeline() function, but would modify the incoming sg_pipeline_desc object before it is forwarded to sokol_gfx's sg_make_pipeline().

...this would provide a maximum flexibility with minimal changes to sokol_gl.h... I think that's a small enough task that I could attempt this on the side in the next few days...

**Comment by floooh** [comment]
...ok I've been sleeping about this and came up with a slightly better idea: 

A pipeline stack (similer to the matrix stack, but for pipeline-state-objects).

There would be 3 new API functions:

```c
sg_pipeline sgl_make_pipeline(const sg_pipeline_desc* desc);
void sgl_push_pipeline(sg_pipeline pip);
void sgl_pop_pipeline(void);
```

The ```sgl_make_pipeline()``` functions is a thin wrapper around sokol_gfx.h's sg_make_pipeline, but doesn't take a vertex-layout-description, shader, pixel formats and sample count (these are all "patched in" before sokol_gfx function sg_make_pipeline() is called. If you keep all desc-values at their default-state (zero-initialized), you'll get a pipeline object sokol_gl.h's initial (default) state.

```sgl_push_pipeline()``` pushes a pipeline object on the internal pipeline-stack, all following begin/end calls will use this pipeline object for rendering. ```sgl_pop_pipeline()``` pops the topmost pipeline object from the stack, and the previous one becomes active (or sokol_gl.h's default state if the stack is empty).

I actually like this idea so much that I will remove the previous state functions from sokol-gl, so this will go away (except activating/deactivating texturing).

```
void sgl_state_depth_test(bool enabled);
void sgl_state_blend(bool enabled);
void sgl_state_cull_face(bool enabled);
```
This isn't much work (in fact, the implementation code of sokol_gl.h will be simplified a lot because the "on demand" pipeline object creation and the state bitmask stuff will go away. I'll start implementing this in a branch.

**Comment by floooh** [comment]
...hmm ok, it's not quite that simple, I forgot that I need to create one pipeline variant for each primitive type (line list, triangle strip etc...)... the basic idea is still good though, it's more implementation work though. I need add a new resource handle type sgl_pipeline (vs sg_pipeline) and a simple "resource pool" for this sgl_pipeline "meta-resource".

**Comment by floooh** [comment]
...ok I started working on this (it's pretty much done except for some more polishing and writing documentation).

The work is tracked in this PR:

https://github.com/floooh/sokol/pull/144 

... and the updated sample-code is tracked here:

https://github.com/floooh/sokol-samples/pull/25

**Comment by questor** [comment]
really really great, thanks :)

**Comment by floooh** [comment]
...and it's merged: https://github.com/floooh/sokol#updates
