### ISSUE TITLE
fluent interface for c++

### ISSUE THREAD

**Issue by questor** [floooh/sokol#148]
not directly an issue but more a question: I really like the c initialization interface of sokol, but sadly it's currently not available for c++ (afaik it should be included in the c++20 release). but something close to the c initialization is the fluent interface possible with c++. for example create a buffer without fluent interface would be:
```
    bind.vertex_buffers[0] = sg_make_buffer(&(sg_buffer_desc){
        .size = sizeof(vertices),
        .content = vertices,
        .label = "quad-vertices"
    });
```
and with fluent interface it would become this:
```
sg_buffer_desc desc
    .size(sizeof(vertices))
    .content(vertices)
    .label("quad-vertices");
bind.vertex_buffers[0] = sg_make_buffer(&desc);
```

what do you think about this type of interface for the c++ world of sokol? or don't you like this interface and don't want to have it because of additional overhead because maintenance would mean keeping them in sync with the structures? (maybe as pull-request)

[edit: format of code changed]

**Comment by floooh** [comment]
I've used something similar for the WIP sokol branch in Oryol, which is a C++ framwork and can't use C99 designated init, e.g. see here: 

https://github.com/floooh/oryol/blob/sokol-gfx/code/Samples/Triangle/Triangle.cc

I'm not a big fan of it since (essentially) it's just a lot of boilerplate code, but it's the only acceptable current workaround for C++ which comes close to designated init. However I really don't want to add any C++ specific code to the sokol headers, and with a subset of designated init coming in C++20 this probably won't be an issue in the near future.

It might make sense to create a separate github repo with "C++ bindings", similar to the Rust bindings (https://github.com/code-disaster/sokol-rs), but it's not something I'm currently interested in maintaining ;)

**Comment by questor** [comment]
okay, sounds reasonable. thanks for your comment!
