### ISSUE TITLE
sokol_audio: audio mixer question

### ISSUE THREAD

**Issue by septag** [floooh/sokol#155]
I'm trying to implement a very simple audio mixer with *sokol_audio* and I'm very much a beginner in audio programming so excuse me if the question is a little stupid ...

I'm using _push_ method to stream audio to the device (windows backend). I guess _push_ method is just a higher-level fifo ringbuffer implemented on top of stream callback.

here is my update loop:

```c
int frames_remain = saudio_expect();
if (frames_remain > 0) {
    float* frames = malloc(sizeof(float) * frames_remain * channels);
    memset(frames, 0x0, sizeof(float) * frames_remain * channels);
    int num_frames_mixed = mix(frames, frames_remain);    // mix audio data in the playlist into the buffer
    saudio_push(frames, num_frames_mixed);
    free(frames);
}
```

If I play one audio, it plays fine. But when I try mix multiple audio and push them into the buffer, I hear clicks and pops.
So the question is, does the update loop look alright ? If yes, any hints on what may cause clicks and pops ?

**Comment by floooh** [comment]
Is "frames_remain" the same as "num_frames_mixed"? (it should be, otherwise it would explain the click and pops).

Usually you'd mix different audio sources by adding their sample values (for example here in the Bombjack arcade machine emulator which has 3 sound chips: https://github.com/floooh/chips-test/blob/926ef98856a434095d210da965cd09f7c4d7b966/examples/sokol/bombjack.c#L425).

The problem with this approach is clipping (when the accumulated sample value goes above +1.0 or below -1.0), but even when this is ignored, the result is usually pretty good.

**Comment by septag** [comment]
Thank you. The tip resolved the issue for me, I thought the ring buffer fills remaining frames with zero.
