### ISSUE TITLE
change shader in pipeline object?

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol#158]
I'm in a situation where I'd would like to change the shader on a pipeline. (Obviously with the restrictions of all the shaders having same input layout.)

Would this be possible in theory, or would it not work on certain platforms?
Or should I be creating new pipeline object for each shader and not worry about this?

**Comment by septag** [comment]
I don't think it's currently possible. Andre has to confirm this btw.
However, here is what I did this in my [implementation](https://github.com/septag/rizz/blob/40e597c943b37ed3e0d601c194bc7cde3dbb7057/src/rizz/graphics.c#L295)

obviously, for every backend it needs a different implementation, metal being the hardest, because you have to recreate the pipeline object.

**Comment by floooh** [comment]
Nope, it's not possible to switch out the shader in an existing pipeline object.

However there's still some potential to make pipeline objects much cheaper, so that it's ok to have tens-of-thousands of them alive (basically instead of mutating existing pipeline objects, make it as cheap as possible to create slightly modified clones):

- reduce the internal struct sizes of pipeline objects in the sokol backends drastically by removing members that are not needed after creation, and tighter packing of the remaining members (e.g. bitmasks), basically try to get a sokol pipeline object down to a few dozen bytes
- used caching and sharing for internal pipeline object components (e.g. depth-stencil-state, rasterizer state, blend state...). D3D11 already does this automatically (for instance, creating a rasterizer state object with the same internal state twice will actually only create one object: https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/nf-d3d11-id3d11device-createrasterizerstate), but this would make sense in the Metal backend

**Comment by mattiasljungstrom** [comment]
Thanks for the feedback! I will create new pipeline objects then, don't need thousands (yet at least). :)
