### ISSUE TITLE
sample value is not validated in pipeline

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol#159]
If I understand it correctly the sample value in the render target (sg_image/screen buffer) and the pipeline needs to be set to the same value. There doesn't seem to be any validation for this, which would be nice. :)

On D11 it works anyways, but on Metal flicker is drawn if not correctly setup.

Can be tested on quad-sapp by setting the sample count to 4 in the init and not changing the pipeline.

**Comment by floooh** [comment]
It's currently validated only when rendering to offscreen passes, because only in this case sokol_gfx.h has all the required information:

https://github.com/floooh/sokol/blob/7fc4ef91abdb80d6fefaad5d7b74bbc1798a7271/sokol_gfx.h#L9239

When rendering the default pass, sokol_gfx.h doesn't know the sample count of the display framebuffer, since it didn't create that.

Metal's own validation layer should catch that though, this is what I'm seeing when running in debug mode in Xcode when the sample count mismatches:

```
2019-05-31 14:37:45.210709+0200 cube-sapp[37583:1229910] Metal GPU Frame Capture Enabled
2019-05-31 14:37:45.211465+0200 cube-sapp[37583:1229910] Metal API Validation Enabled
-[MTLDebugRenderCommandEncoder validateFramebufferWithRenderPipelineState:]:1211: failed assertion `For color attachment 0, the texture sample count (4) does not match the renderPipelineState sampleCount (1).'
```

**Comment by mattiasljungstrom** [comment]
Ok, I see. I wasn't running in Xcode so didn't notice it. Thanks!
