### ISSUE TITLE
Add DLL build option

### ISSUE THREAD

**Issue by datgame** [floooh/sokol#160]
Here's an example https://github.com/glfw/glfw/blob/master/include/GLFW/glfw3.h#L231

**Comment by floooh** [comment]
Hah, good timing :) Just wanted to add a ticket myself.

**Comment by floooh** [comment]
Here's what it would look like:

https://github.com/floooh/sokol/blob/7c88e7736e813479595489bb6acaa373d25fd1f8/sokol_gfx.h#L489-L497

You'd just define SOKOL_DLL both when building *and* using the DLL. When building the DLL (SOKOL_IMPL is also defined) it will use __declspec(dllexport), otherwise __declspec(dllimport).

I need to do this for all headers, and actually test on Windows before merging, might take a few days.

**Comment by datgame** [comment]
Sounds just right!

**Comment by Alzathar** [comment]
FYI, I did something similar under Windows 10 x64 (MSVC 2017), and it works like a charm for sokol-gfx!

**Comment by floooh** [comment]
New sample code to test building and using sokol as DLL (currently Windows only):

sokol-dll.c as Implementation file:

https://github.com/floooh/sokol-samples/blob/dll-defines/libs/sokol/sokol-dll.c

fips/cmake definition to create the DLL:

https://github.com/floooh/sokol-samples/blob/12e22867129b2c8a59ee7e85e5800b72fc56bcaf/libs/sokol/CMakeLists.txt#L59-L66

And an executable using sokol as DLL (note the SOKOL_DLL define, that's the only difference):

https://github.com/floooh/sokol-samples/blob/dll-defines/sapp/noentry-dll-sapp.c

fips/cmake definitions:

https://github.com/floooh/sokol-samples/blob/12e22867129b2c8a59ee7e85e5800b72fc56bcaf/sapp/CMakeLists.txt#L353-L361

...and the imports/exports via dumpbin, just to make sure it actually works :)

```> dumpbin /exports sokol-dll.dll:```
![sokol-dll-exports](https://user-images.githubusercontent.com/1699414/58890759-88149e80-86eb-11e9-8b40-1459c0af4c49.jpg)

The sokol-dll.dll depends on kernel32.dll, user32.dll, ole32.dll and d3d11.dll (with d3dcompiler_47.dll loaded on demand).

```> dumpbin /imports noentry-dll-sapp.exe```
![sokol-dll-imports](https://user-images.githubusercontent.com/1699414/58890855-babe9700-86eb-11e9-9af8-27197f7c8636.jpg)

The exe only depends on kernel32.dll and sokol-dll.dll.

Currently this is still all in a branch, and only the "main headers" are working. Next I'll update the headers in the util directory too, and merge to master.

**Comment by floooh** [comment]
Ok, everything done and merged. It may also make sense to add function pointer typedefs, for situations where the DLL is loaded manually via dlopen or LoadLibrary, but I'll wait with this until anybody actually needs it :)

**Comment by fenoloftaleina** [comment]
Hi @floooh, it would be nice to have the shared lib build on osx as well. Do you know what that would involve? Is the windows-only route cutting corners or is it a nightmare to get it working on osx?

I'm looking at the errors and the only thing that comes to mind is: is linking osx frameworks not working when building a dylib?

As I said, this would be a nice to have, I'm still going to use sokol without it. It's the best.

**Comment by floooh** [comment]
Hi @fenoloftaleina, DLL support on macOS and Linux doesn't require code changes like on Windows, only build system changes.

I've updated the DLL example ```noentry-dll-sapp``` so that it also works on macOS and Linux. The fips-cmake code to compile the sokol headers into a DLL looks like this:

https://github.com/floooh/sokol-samples/blob/9b8602ee063558285a67a53daab6d0b5c4086a62/libs/sokol/CMakeLists.txt#L80-L87

The generated library target is then used like a normal dependency on the program.

Sorry for only providing fips examples, and not "raw" cmake code, but if you know how to build a DLL with your favourite build system than this shouldn't cause problems.
