### ISSUE TITLE
sokol_gfx.h: investigate depth texture support

### ISSUE THREAD

**Issue by BrothaOnAcid** [floooh/sokol#165]
I was toying with deferred rendering (GL backend) and just noticed that for 'depth images' you use _renderbuffers_ instead of _textures_.
you cant read from renderbuffers afaik. So any workarounds ?

really **good** set of libraries by the way ! big up

**Comment by floooh** [comment]
I remember that I had some trouble in the past with renderable depth textures, since this requires a WebGL extension (WEBGL_depth_texture), support for this seems to be pretty good now though.

A workaround which definitely works across all platforms is encoding depth in a separate RGBA8 render target in a separate pass (this also avoids the use of floating point render targets, which may be another compatibility issue).

I did this here for the shadow mapping:

http://floooh.github.io/oryol-samples/wasm/BulletPhysicsBasic.html

The interesting stuff is here:

https://github.com/floooh/oryol-samples/blob/master/src/BulletPhysicsBasic/shaders.shd

I'm not sure if sampling from depth textures can be implemented in a 100% cross-platform-compatible way (with the SPIRV-Cross based shader compiler), but I'll keep the feature in mind.

**Comment by floooh** [comment]
Closing this preliminary as fixed, see this comment for details:

https://github.com/floooh/sokol/issues/576#issuecomment-1527810831
