### ISSUE TITLE
sokol_gfx.h : resizing render targets (sg_image)

### ISSUE THREAD

**Issue by siavashserver** [floooh/sokol#167]
Hello! I was wondering how would one scale down render targets? (for effects like bloom)

**Comment by floooh** [comment]
To resize render targets with window size changes, you need to destroy and recreate them, along with their pass. Here's an example which recreates offscreen render targets when the sokol_app.h RESIZED event is sent:

https://github.com/floooh/sokol-samples/blob/7df270a9ed402af95f3560fecc74fef55174ddd1/sapp/mrt-sapp.c#L52-L100

The actual downscaling must be done by rendering via pixel shader by rendering a fullscreen quad, there's no "fixed function" blitting operation in sokol-gfx.

**Comment by siavashserver** [comment]
Thank you!

**Comment by siavashserver** [comment]
Forgot to ask, is it a webgl/opengles limitation?

**Comment by floooh** [comment]
No, WebGL is fine since it has a scaling glBlitFramebuffer function (I'm using this - without the scaling - to resolve MSAA render targets to textures in sg_end_pass().

The problem are the other APIs, both D3D11 and Metal only offer fairly limited copying between texture resources without scaling, so a full render pass is needed for this anyway (and it's also more flexible since you have better control over the scaling via the pixel shader).

**Comment by floooh** [comment]
...oops correction, WebGL doesn't have glBlitFramebuffer() that's a WebGL2 feature (that's why sokol_gfx.h doesn't support MSAA render target in WebGL(1).

So yeah, in addition to D3D11 and Metal, WebGL/GLES2 also wouldn't work :)

**Comment by siavashserver** [comment]
I wasn't aware that limitation applies to D3D11 and Metal as well. Thanks again :)
