### ISSUE TITLE
sokol_gfx.h specifying default OpenGL fbo id, or auto querying it

### ISSUE THREAD

**Issue by exavi** [floooh/sokol#170]
Hi there,

Thanks for setting up this library, it looks great!

I'm in need of a OpenGL/Metal wrapper for a big-ish Linux/Windows/macOS/iOS project and sokol_gfx.h seems like it would be a good choice, so I started doing a test on macOS using a QOpenGLWidget and it seems to fail with an assertion failure in the glClear on line 4955, inside _sg_begin_pass.

`gl error code: 1286 (GL_INVALID_FRAMEBUFFER_OPERATION) because (glCheckFramebufferStatus(GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE) fails`

I did a bit of digging and it seems to be due to the fact that QOpenGLWidget creates a proper FBO which does not necessarily have to be "0", in my case it seems to be "1", after some more digging it appears that sokol_gfx assumes the default framebuffer to be 0 and that's what caused the error.

After setting: 

`_sg.gl.cur_context->default_framebuffer = 1; `

it worked fine!

It would be nice if sokol_gfx.h could automatically query it during initialization, instead of assuming it's going to be 0, the following does the trick:

```
GLint defaultFbo = _sg.gl.cur_context->default_framebuffer;
glGetIntegerv(GL_FRAMEBUFFER_BINDING, &defaultFbo);
_sg.gl.cur_context->default_framebuffer = defaultFbo;
```
small note, if default_framebuffer was an int instead of uint it would be queryable directly on the value instead of requiring nasty casting.

I will eventually need to create extra passes (I also use some other non-default FBOs) but it would be nice to be able to specify the default one and not have the default case be another "special" one if that makes sense.

**Comment by floooh** [comment]
Hi, hmm let me check, I was expecting that I had this case covered, because at least on some platforms the default framebuffer isn't 0...

**Comment by exavi** [comment]
it looks like _sg_create_context does query the default framebuffer, which is called by sg_setup_context which is in turn called by sg_setup, perhaps I'm missing some sg_desc flag?

I'm using plain 0.

sg_desc desc = {0}; sg_setup(&desc);

Could that be it?

**Comment by floooh** [comment]
...ok the code which gets the default framebuffer is here:

https://github.com/floooh/sokol/blob/fe159f4a37821cb66f8dfed1da51e31800412aff/sokol_gfx.h#L4173-L4188

Note the call to ```glGetIntegerv(GL_FRAMEBUFFER_BINDING, (GLint*)&ctx->default_framebuffer);```, this function is called at the end of sg_setup(). Maybe you're setting up the QOpenGLWidget after calling sg_setup()? If the order cannot be changed you can also create a context and make that active after creating the QOpenGLWidget (and making its GL context active). See: https://github.com/floooh/sokol/blob/fe159f4a37821cb66f8dfed1da51e31800412aff/sokol_gfx.h#L341-L382). Each sokol-gfx context queries the framebuffer binding, so that should also work. But I think it's better to defer the call to sg_setup() to after creating the and "activating" QOpenGLWidget GL context.

The type of default_framebuffer is a GLuint because that's what glBindFramebuffer expects: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBindFramebuffer.xhtml.

Let me know if this works!

**Comment by floooh** [comment]
...just a guess, but maybe you need to call QOpenGLWidget::makeCurrent() before the call to sg_setup(), the docs say that this only happens "automatically" in the paint-method...

But maybe this doesn't work either, because makeCurrent() might not bind the framebuffer. In that case a new sg_desc member "gl_default_framebuffer" would make sense, this could be initialized with QOpenGLWidget::defaultFramebufferObject().

**Comment by exavi** [comment]
Aha! Thanks for looking into it, looks like QOpenGLWidget::initializeGL() has pretty big gotcha.

https://doc.qt.io/qt-5/qopenglwidget.html#initializeGL

As fas as initialization functions go, this is a bit shitty on Qt's part. So you can initialize stuff *but not really*, great. ;)

Moved things around and this does the trick.

void GLWidget::initializeGL()
{
    initializeOpenGLFunctions();
}

void GLWidget::paintGL()
{
    static bool initialized = false;
    if(!initialized)
    {
        do_sokol_gfx_init_for_reals();
        initialized = true;
    }

    // drawing code
}

Thank you for your time, I may have more questions soon, apologies for the disruption.

**Comment by floooh** [comment]
ok that looks like an acceptable workaround :)

**Comment by exavi** [comment]
Replying here even though it's closed in case anyone is on the same boat.

The same workaround works for iOS too, as apparently the framebuffer isn't fully set up until -(void)glkView:(GLKView*)view  drawInRect:(CGRect)rect is called.

Of course this is only useful during the transition period from GL to Metal, or rather from homebrewed wrapper to sokol_gfx, but hey just in case I thought I'd leave a note for other users!

Needless to say, I'm really starting to like sokol !!!  :D

**Comment by Sharian** [comment]
This helped a lot! Thank you! :)
