### ISSUE TITLE
sokol_gfx.h Pixel Buffer Objects, reading pixels? CPU readbacks?

### ISSUE THREAD

**Issue by exavi** [floooh/sokol#171]
I did a quick search for `glReadPixels` and `GL_PIXEL_PACK_BUFFER` and couldn't find any entries, I understand that the second does not have an available equivalent for all supported backends (GL_ES2 in particular)

I've barely started to look at Metal but my understanding is that on the Metal end, reading from a framebuffer isn't a different operation from reading from say, any other buffer.

Are CPU readbacks possible in sokol or being considered? 

If they aren't or it is not a design priority, would you consider exposing some of the internals so library users can make a small ad-hoc implementation of this for each of the backends?

I'd be more than happy to contribute an implementation for all OpenGL backends if this isn't covered but you think would make sense to have. I would do my best to do a Metal one too. (although my Metal knowledge at the moment is non-existent)

**Comment by floooh** [comment]
I don't want to add pixel read-back in the "official sokol-gfx API since there's no fast way to do this, but it should be possible with what's already there.

You could create an "extension header" which would have to be included after the sokol-gfx *implementation* (and thus has full access to all internal functions and data structures), and add your own functions which would extend the sokol-gfx API, e.g.:

```c
#define SOKOL_IMPL
#include "sokol_gfx.h"
// the following header has access to all sokol-gfx "internals" because the full sokol-gfx
// implementation is included before it
#include "my_sokol_gfx_extensions.h"
```

However if you only need the GL backend, there's probably a much easier way: simply call glReadPixels() right before an sg_end_pass(). This should do the "right thing", unless it's an MSAA framebuffer (for this you would need to do an MSAA resolve first which normally happens in sg_end_pass(), for more complex stuff like this it probably makes sense to use the extension header method).

**Comment by floooh** [comment]
PS: in general it's possible to mix sokol-gfx calls with native 3D-backend-API calls (e.g. GL), you just need to call sg_reset_state_cache() after doing if your own calls changed the internal 3D-API state (glReadPixels() doesn't do this so calling sg_reset_state_cache() it isn't needed there).

There's also support for "injecting" your own "native" 3D resources (buffers and textures) into sokol-gfx:

https://github.com/floooh/sokol-samples/blob/master/d3d11/inject-d3d11.c

https://github.com/floooh/sokol-samples/blob/master/glfw/inject-glfw.c

https://github.com/floooh/sokol-samples/blob/master/metal/inject-metal.mm

**Comment by exavi** [comment]
Thanks a lot for your reply I will have a look through this!

I need a few extra calls, glReadPixels by itself is indeed slow but when combined with Pixel Buffer Objects you get fast DMA read-back which is what I'm after, there is a little bit of setup for the PBOs and a bit of glFences involved to make things fancier but that's about it.

My only concern is on the Metal end, as is the part that I don't know too much of, I'm afraid that it may require setting up the framebuffer initially with some "readable" flag, I haven't looked through that part yet, I will when I have a better understanding of metal, I guess I'll cross that bridge when I get to it, thanks! ;)

**Comment by floooh** [comment]
...true, solving the problem "properly" may require tinkering in sokol-gfx itself, and probably also making the read-back asynchronously (either with polling whether the pixels are available, or with a callback).

Since PixelBufferObjects in GL are not supported in all backends this would have to be an optional features (via sg_query_feature()), and a few more desc-struct member for images and/or passes might be needed.

**Comment by nurpax** [comment]
I wonder if there's any recommended way to do the equivalent of glReadPixels nowadays?  I'm running on macOS and wanted to save a screenshot, but don't know what's the recommended way to do it. 😄

**Comment by floooh** [comment]
@nurpax glReadPixels should work without pixel buffer objects (e.g. also on macOS and WebGL2), it will just be slow. 

E.g. I would try (pseudo code...)

```c
const sg_swapain swapchain = sglue_swapchin();
sg_begin_pass(&(sg_pass){ ..., .swapchain = swapchain);
...
sg_end_pass();
glBindFramebuffer(GL_FRAMEBUFFER, swapchain->gl.framebuffer);
glReadPixels(...);
```
...haven't actually tried that though...

**Comment by floooh** [comment]
...as for the 'proper way I finally started planning the new resource update API (https://github.com/floooh/sokol/issues/1547), not much thought has gone yet into reading data back though...

**Comment by nurpax** [comment]
Thanks!  Sorry for being imprecise in my question, I meant "something like glReadPixels, whatever that may be on macOS/Metal". 😄 I'm also using Zig so reaching out for the native APIs feels a bit daunting.

I'll keep my eyes on the resource API update for future needs, now I just went ahead and used the macOS screenshot tool.
