### ISSUE TITLE
Query default backbuffer format (new func sg_query_defaults())

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol#196]
With the new changes, is there a way to query what the screen backbuffer format is? It's needed in the pipeline setup and I'd prefer not to hardcode it. :)

Maybe _sg_default_rendertarget_colorformat() should be accessible?

**Comment by floooh** [comment]
The idea is that you don't provide a value for ```sg_pixelformat_desc.blend.color_format``` (keep it zero-initialized), this will use the proper backend-specific pixelformat. Is this ok in your opinion?

**Comment by mattiasljungstrom** [comment]
Do you mean sg_pipeline_desc? Can I create one of those and then check the value?

The thing is I'm caching various pipelines based on the shader/pixelformat/etc values so I need to explicitly know the value for the caching key.

**Comment by mattiasljungstrom** [comment]
This isn't a huge thing, but I'm basically replicating the code from _sg_default_rendertarget_colorformat() in my own code now.

**Comment by floooh** [comment]
> Do you mean sg_pipeline_desc?

Erm yes, typo.

> Can I create one of those and then check the value?

No, the value is basically "write-only...

> The thing is I'm caching various pipelines based on the shader/pixelformat/etc values so I need to explicitly know the value for the caching key.

Would it work to use the _SG_PIXELFORMAT_DEFAULT value (or simply zero) for the caching key?

The reason why I don't want to bake this in the API yet is because I'm not sure myself whether the _sg_default_rendertarget_colorformat() is really useful, since it just "assumes" those pixel formats. If another library than sokol_app.h is used for swapchain setup this might break.

The proper way would be to pass the default-framebuffer pixel formats into sg_setup() via new members in the sg_desc structure.

...hmm, but I guess a way to query that would make sense.

I would probably add a new function like this though:

```
sg_defaults sg_query_defaults();
```
...and the sg_defaults struct would contain ```rendertarget_color_format```, ```rendertarget_depth_format```, ```texture_color_format``` (and maybe more stuff in the future).

**Comment by mattiasljungstrom** [comment]
Yeah, _SG_PIXELFORMAT_DEFAULT would work for me, good point! I'll use that for now, and since BGRA is unique anyways it doesn't matter. (I mean I'm not using that for any other buffers.)

**Comment by floooh** [comment]
(note to self)

Better idea: 5 new functions:

```c
sg_buffer_desc sg_query_buffer_defaults(const sg_buffer_desc* desc);
sg_image_desc sg_query_image_defaults(const sg_image_desc* desc);
sg_shader_desc sg_query_shader_defaults(const sg_shader_desc* desc);
sg_pipeline_desc sg_query_pipeline_defaults(const sg_pipeline_desc* desc);
sg_pass_desc sg_query_pass_defaults(const sg_pass_desc* desc);
```
These would take a desc struct, and return a matching desc structs with all default-values replaced with the actual values. Those functions exist internally anyway, and it's much more flexible than just exposing a small selected number of values.

**Comment by floooh** [comment]
Ok this is implemented in commit https://github.com/floooh/sokol/commit/806160c6fd719d08bfeabd0cbd081892e7bbf4f2.

And the accompanying tests:

https://github.com/floooh/sokol-samples/blob/804fd80facf34b182941341ef4dcbdc4239f518c/tests/sokol-gfx-test.c#L483-L590
