### ISSUE TITLE
sokol_gfx: SwapChain

### ISSUE THREAD

**Issue by amerkoleci** [floooh/sokol#215]
Hi,

I think it would be good if sokol supports SwapChains, currently they are created externally d3d11entry for example, maybe a new capability for platform not supporting it (OpenGL/GLES) and maybe have the sg_begin_pass accepting SwapChain instance then commit can present the SwapChains on screen.

Tell me what you think

**Comment by floooh** [comment]
I think the current approach to have the swap chain created externally and pass the required information for rendering to the default framebuffer via callback functions to sg_setup() is ok. Swap chain creation usually requires interacting with the window system, and that's outside sokol_gfx.h's scope (this stuff lives in sokol_app.h instead).

**Comment by amerkoleci** [comment]
Not sure why you say this? Swap Chain requires native window handle and that's all, you can the resize if required or present to screen

**Comment by floooh** [comment]
Swap-chain related code would need to be different for WGL, GLX, Wayland, GLKit (on Mac and iOS), EGL (and again different for EGL on Android vs EGL on RaspberryPi, DXGI (with different DXGI versions to consider), MetalKit (again slightly different for iOS and macOS) and emscripten. 

Interacting with a swap chain from sokol_gfx.h would add a new "platform dimension" to the code with lots of new code paths:

- GLCORE33 with WGL on Windows
- GLCORE33 with GLX on Linux
- GLCORE33 potentially GL with EGL(?) on Wayland
- GLCORE33 with GLKit  on Mac
- GLES2/3 with GLKit on iOS
- GLES2/3 with emscripten (WebGL doesn't even have the concept of a "swap chain")
- GLES2 with EGL on Raspi
- GLES2/3 with EGL on Android
- D3D11 with DXGI on Windows
- METAL with MetalKit on macOS
- METAL with MetalKit on iOS

...I guess that's it.

Also, this code would essentially be a copy from the code that's already in sokol_app.h. IMHO it doesn't make much sense to separate the swap chain code from the other window system code, since the two are closely related anyway.

**Comment by amerkoleci** [comment]
Ok I see.

Lets close it then :)
