### ISSUE TITLE
sokol_audio: saudio_buffer_size(void) isn't implemented

### ISSUE THREAD

**Issue by JoyeuxCodeur** [floooh/sokol#228]
Hello.

int saudio_buffer_size(void) is declared but never implemented in sokol_audio.

Regards.

**Comment by floooh** [comment]
Good catch, I think the function declaration is a left-over from the time when sokol_audio.h was WIP, because with the frame callback model you're getting the required number of samples to fill with the callback, and with the push-model you can ask via saudio_expect() how much data fits into the intermediate ring buffer.

Do you have a specific situation where the saudio_buffer_size() function makes sense? Otherwise I'd like to remove the function declaration.

**Comment by JoyeuxCodeur** [comment]
Wait it's implemented but with the wrong name. saudio_buffer_frames(void) (line 1404) seems to returns the right value but isn't used anywhere and isn't in the public API declaration.

I don't have a use case on my side, I just stumbled upon it while messing around with sokol_audio. 
The only case I can think of is if the user wants to make sure that the requested buffer_frames size in saudio_setup() is the one being used.
The Empscriptem implementation seems to be the only one which can use a different buffer size than the one requested.

**Comment by floooh** [comment]
Ah ok, I'll try to clean up the mess ASAP. Thanks for looking into it :)

**Comment by floooh** [comment]
Ok, I simply fixed the wrong function prototype and also added a little API test here:

https://github.com/floooh/sokol-samples/blob/master/tests/sokol-audio-test.c
