### ISSUE TITLE
fullscreen is wonky on macOS / metal

### ISSUE THREAD

**Issue by mattiasljungstrom** [floooh/sokol#231]
About 10% of the time when I launch on macOS my app fails to launch in fullscreen and is instead shown in a window.

When I run in fullscreen and switch between "spaces" the sokol app sometimes becomes unresponsive (beach ball). It works correctly if I instead use cmd+tab to switch between apps. When it's frozen if I cmd+tab away and back it becomes responsive again.

This is on macOS 10.14.6, latest sokol code.

**Comment by floooh** [comment]
Hmm, not sure what I did wrong there, I remember some "wonkiness" with showing/hiding the titlebar on entering fullscreen, but no unresponsiveness.

The code is basically here:

https://github.com/floooh/sokol/blob/939c071043707c283b3122a36cc3df9b533711cd/sokol_app.h#L1392

Do you also see this behaviour in the imgui-highdpi-sapp sample application?

I guess best way to tackle this is to look into GLFW and SDL2 first how they initiate fullscreen on Mac. I'm currently busy with emulator stuff, so if anybody wants to grab the bug... ;)

**Comment by mattiasljungstrom** [comment]
When I pull the latest sokol-sample and config it for sapp-metal-osx-xcode-debug, build and run I get:  "application requires at least OS X version 10.15.0 (10.15), but is being run on 10.14.6 ( 10.14.6/18G95), and so is exiting."

I opened the project in Xcode and changed deployment target to 10.14 and it runs. 

Adding these lines to sapp-cube / sapp_desc reproduces the freeze:
```
        .width = 1440,
        .height = 900,
        .fullscreen = true,
        .high_dpi = false,
```

When I trigger the issue and then debug pause in Xcode, it looks like it's blocked here: (but maybe that's where it's always blocked?)
```
    /* if this is the first pass in the frame, create a command buffer */
    if (nil == _sg_mtl_cmd_buffer) {
        /* block until the oldest frame in flight has finished */
>>>  dispatch_semaphore_wait(_sg_mtl_sem, DISPATCH_TIME_FOREVER);
        _sg_mtl_cmd_buffer = [_sg_mtl_cmd_queue commandBufferWithUnretainedReferences];
    }
```

**Comment by floooh** [comment]
Thanks for the info, that gives at least a place where to start searching...

**Comment by floooh** [comment]
...only problem is I can't reproduce the problem here... (mid-2014 13" MBP, macOS 10.15.1), with the changes to cube-sapp you describes :/

...basically compiled in release mode (I was hoping the bug manifests there, since it didn't in debug), and then continuously starting/stopping the sample via "./fips run cube-sapp".

**Comment by mattiasljungstrom** [comment]
Sorry, I wasn't clear enough in the bug report. There are two issues: 
1. Fullscreen sometimes doesn't trigger and app is shown in window. 
2. The app freezes when you switch away/back from the fullscreen "space". (I do it with four fingers swipe upwards, or with a keyboard shortcut.) It doesn't freeze when you cmd+tab away. It unfreezes when you cmd+tab back to the app.

I've only replicated #2 in the cube-sapp example so far.

**Comment by floooh** [comment]
Ah alright, let me check again with swiping out and into the app...

**Comment by floooh** [comment]
Ok, I'm seeing that "rendering stops" when doing swiping gestures with the fullscreen app, but it recovers automatically after the app is becoming "active" again (not just after cmd+tab). It looks similar to minimizing a windowed app during the minimizing animation (I've set the minimize animation to "Scale effect", not "Genie effect")...

Maybe it's possible to detect this state before it happens, skip rendering completely, and instead do a little sleep to prevent the CPU from running at 100% (since it would no longer be throttled by vsync).

There was a somewhat related problem with the D3D11 backend, which was solved like this:

https://github.com/floooh/sokol/blob/939c071043707c283b3122a36cc3df9b533711cd/sokol_app.h#L4367-L4369

(hmm, but when minimizing a windowed app, the frame loop continues to run just fine in the minimized state here on macOS, so at least for the minimized state, such a hack isn't needed).

Not sure how to proceed currently TBH :)

**Comment by floooh** [comment]
PS: when the fullscreen cube-sapp is "offscreen" the frame loop also continues to run... rendering only appears to stop during "transitions".

**Comment by mattiasljungstrom** [comment]
I get a beach ball when I swipe back to the app, and if I then cmd+tab back and forth it starts running again. Is this what you're seeing as well?

**Comment by floooh** [comment]
Nope, no beachball, but I just checked whether the "official" macOS Game sample in Xcode behaves the same after switching it to fullscreen via the fullscreen window icon (it does).

Can you check whether you also see the freezing when starting cube-sapp in windowed mode,, then switch to fullscreen through the UI and do the swiping gestures?

And then: check how the Xcode Game sample ("File => New => Project => macOS => Game") behaves when trying the same?

**Comment by floooh** [comment]
I just had the grand idea to do a Quicktime screen recording, but the behaviour slightly changes when recording (the animation never stops in this case, even during transitions). But here's the movie anyway. Only difference to the "non-recording" case is that the animation stops playing during the transitions:

[macos_fullscreen.mov.zip](https://github.com/floooh/sokol/files/3813854/macos_fullscreen.mov.zip)

**Comment by mattiasljungstrom** [comment]
Your video is different from my view so I guess it's a 10.14 / 10.15 issue. 

Tried launching in windowed, and get the freeze after making it fullscreen and changing spaces. The "game" sample doesn't have the issue, so something must be different.

**Comment by mattiasljungstrom** [comment]
and of course when I do a screen recording with quicktime, the cube-app doesn't freeze... :/

**Comment by mattiasljungstrom** [comment]
This isn't a major issue for me, but I'll try to debug it a bit more later and compare to the "game" sample.
