### ISSUE TITLE
warnings during d3d11 shader compilation result in invalid shader object

### ISSUE THREAD

**Issue by kevinw** [floooh/sokol#232]
While compiling some of my shaders, this gets printed to the console:

```
(47,19-62): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
(43,12-57): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
```

These warnings cause `_sg_d3d11_compile_shader` to return NULL, so effectively warnings become errors. Is that the desired effect?

**Comment by floooh** [comment]
Hi, I'm seeing those warnings too when compiling the shaders for the sdf-sapp and cgltf-sapp samples. However in this case the compilation happens in the offline shader compiler via sokol-shdc, and the resulting shader blob is then accepted by D3D11.

I guess your case is different in that you compile the D3D11 from source at runtime. I guess my "error detection" is a bit too simplistic here:

https://github.com/floooh/sokol/blob/939c071043707c283b3122a36cc3df9b533711cd/sokol_gfx.h#L7101-L7105

...since this triggers when there's *any* diagnostic output from the shader compiler.

I'll see what I can do about it, but I'm currently a bit busy with other stuff, I guess workaround for now is to fix the warning in the shader code :)

**Comment by kevinw** [comment]
Makes sense, thanks!

**Comment by Fra-Ktus** [comment]
If you need something to test, I have the same warning when I compile this shader:
https://www.interactiveshaderformat.com/sketches/3767

**Comment by floooh** [comment]
Thanks for investigating this @Fra-Ktus, I've been doing emulator stuff over my holiday vacation and only go through the sokol issues that have accumulated. I'll try to work through some of them during January or so :)

**Comment by floooh** [comment]
Ok, I implemented your suggested fix, seems to work nicely :)
