### ISSUE TITLE
sokol_app: Memory issue when creating a large vertex buffer?

### ISSUE THREAD

**Issue by danhambleton** [floooh/sokol#235]
So, I am not 100% sure this is sokol related, but in my code I am creating a large vertex-buffer (~100k vertices, with color/normal/uv coords). If I create this buffer with ~16k vertices, my code runs fine. If I create it with the full ~100k, I get bad access errors. I guess my question is: when creating an app with sokol_app.h, is there some fixed memory size or something? I know there are hard coded limits on various pool size....

I can post some code if this is not ringing any bells :)

**Comment by floooh** [comment]
Hi, there are no size restrictions for the actual vertex buffer content, so 100k vertices shouldn't be a problem, the pool sizes only kick in for the number of bufffers (and in the Metal backend, number of draw calls and amount of updated uniform data per frame).

Some questions:
- which 3D backend and platform (e.g. for emscripten the default heap size might be exhausted)
- are you compiling with release or debug mode? (debug mode might catch problems already in the validation layer, so that's always recommended for development)
- static or dynamically updated vertex buffer? (e.g. if it's a dynamically updated vertex buffer, do the access errors happen during the CPU update?)

Some code might also help :)

**Comment by danhambleton** [comment]
Update: it was a rookie mistake :)  I was a creating the large vertex buffer in the same way that the samples do it, i.e 
```
vertex_data largeVertexBuffer[BIG_NUMBER] //also the vertex_data struct is 16 floats or something...
```
You then run in to stack frame size limitations, and that was what was triggering the error.  To fix, use a vector or `new` or anything else...

**Comment by floooh** [comment]
Ah ok, that makes sense :)
