### ISSUE TITLE
sokol_imgui: how to render to a clipped rect after ImGui is on screen?

### ISSUE THREAD

**Issue by danhambleton** [floooh/sokol#251]
I am porting an little 3d editor project over from Oryol to Sokol (because reasons). My UI is working great (via ImGui), but I now need to render some 3d objects into an ImGui window. I do this by tracking the relevant Rects and apply a viewport and/or scissor. This does not seem to work for me in Sokol. Here is what I've got:

```
void frame()
{

    const int w = sapp_width();
    const int h = sapp_height();

    //start imgui
    simgui_new_frame(w, h, 1.0/60.0);

    //do imgui stuff here
    ImGui::Text("Hello");

    //render
    sg_begin_default_pass(&state.pass_action, w, h);
    sg_apply_pipeline(state.raster_pipeline);
    simgui_render();
    sg_end_pass();
    sg_commit();
    
// now that the ui is renderer, how do I render to clipped rect somewhere on the screen?
//    sg_apply_scissor_rect(300, 300, 800, 500, false);
//    sg_apply_viewport(300, 300, 800, 500, false);
//    sg_begin_default_pass(&state.pass_action, w, h);
//
//    sg_apply_pipeline(state.raster_pipeline);
//    sg_apply_bindings(&state.raster_bindings);
//   sg_draw(..)
//    sg_end_pass();
//
//    sg_commit();   
    
}
```

I have been digging through the issues and there is some mention of the scissor cmd, but not much. Any advice is appreciated.

**Comment by floooh** [comment]
Hi, the sg_imgui_render() function manipulates both viewport and scissor-rect, maybe that's what's throwing your code off (the Oryol Imgui renderer didn't do this):

- at the start of sg_imgui_render(), both the viewport and scissor rect are set to cover the whole framebuffer: https://github.com/floooh/sokol/blob/d7b77c751f6887803dc4efbd3206b09bd94cad1f/util/sokol_imgui.h#L1004

- during rendering, the scissor rect is set as needed by the ImGui draw commands: https://github.com/floooh/sokol/blob/d7b77c751f6887803dc4efbd3206b09bd94cad1f/util/sokol_imgui.h#L1072

- before exit, both the scissor rect and viewport are reset to cover the whole framebuffer again: https://github.com/floooh/sokol/blob/d7b77c751f6887803dc4efbd3206b09bd94cad1f/util/sokol_imgui.h#L1078

In addition sg_begin_pass() and sg_begin_default_pass() will also initialize the viewport and scissor rect to cover the whole frame buffer.

If the code you're running is what you show above, but just with the comments removed, there would be a few issues:

- there must be only one sg_begin_default_pass() per frame
- there must only be one sg_commit() per frame, and no other sokol-gfx calls rendering calls should come after that

So I would try this:

```c
    sg_begin_default_pass(&state.pass_action, w, h);
    // sg_apply_pipeline(state.raster_pipeline); (???)
    simgui_render();
    sg_apply_scissor_rect(300, 300, 800, 500, false);
    sg_apply_viewport(300, 300, 800, 500, false);
    sg_apply_pipeline(state.raster_pipeline);
    sg_apply_bindings(&state.raster_bindings);
    sg_draw();
    sg_end_pass();
    sg_commit();
```

I think the "proper way" to do things like this is via ImGui UserCmds though, I haven't actually tried that, but ImGui draw-commands can have a user callback, so that you can "inject" your own rendering at a specific point during UI rendering:

https://github.com/floooh/sokol/blob/d7b77c751f6887803dc4efbd3206b09bd94cad1f/util/sokol_imgui.h#L1057-L1059

This is described here:

https://github.com/ocornut/imgui/issues/984

I haven't tried that our yet though (maybe I should write an example for that).

Hope this helps :)

**Comment by danhambleton** [comment]
Thanks! I will give this a shot. +1 for an example of sg_draw() inside an ImGui window :)

**Comment by danhambleton** [comment]
Ok this is working. 👏
