### ISSUE TITLE
Possible bug with low-dpi on macos with OpenGL

### ISSUE THREAD

**Issue by prime31** [floooh/sokol#253]
I wanted to get your opinion on this so that I can research it more fully. The issue is apparent on macos when using SDL2 for creating the window. If I create the window with `SDL_WINDOW_ALLOW_HIGHDPI` everything works as expected. If I create the window without `SDL_WINDOW_ALLOW_HIGHDPI` only 1/4 of the window is rendered to, as in this image:

<img width="1106" alt="Screen Shot 2020-01-23 at 9 14 09 PM" src="https://user-images.githubusercontent.com/60377/73046071-72441d00-3e25-11ea-89e8-3ab5f7955892.png">

If I comment out the call to `glScissor` in sokol_gfx then the entire window is cleared but rendering is still only in the bottom 1/4 of the screen:

<img width="1136" alt="Screen Shot 2020-01-23 at 9 15 32 PM" src="https://user-images.githubusercontent.com/60377/73046115-9b64ad80-3e25-11ea-9b72-e350330a30bf.png">

Do you have any idea what this could be? When I setup an SDL window in the exact same fashion with just SDL and minimal OpenGL without Sokol it render correctly filling up the entire window.

**Comment by floooh** [comment]
On macOS Catalina with GL that's a bit hard to say because at first NSOpenGLView, and then definitely changed behaviour related with Retina resolution (I think the default High/LowDPI behaviour changed, and the reported resolution).

But the above problem looks like both the scissor-rect and viewport are half the size they should be. What window size are you reporting to sg_begin_default_pass()? My guess is that those are half the size they should be (just try doubling the size you're getting from SDL to check).

But as I said, GL rendering on macOS Cataline is definitely still wonky (e.g. the LowDPI sokol-samples just render a clear screen, while the HighDPI-sample works on my current setup, but this changed over time, at least during the Catalina Beta).

**Comment by prime31** [comment]
When I double the values SDL gives me it does indeed fit the entire window but then it is just a high dpi backbuffer! I’ll dig around in the SDL and Sokol code and see if I can figure out what is different between them.

**Comment by prime31** [comment]
So, after messing around in GDB and the Xcode view hierarchy debugger I have some more data. I was trying to see what is happening by changing the `contentsScale` and `contentsGravity` of the backing layer.

You can see in this image where i set the scale to 3 and gravity to bottom-left that there is 3/4 of the layer not being drawn to:

<img width="1136" alt="Screen Shot 2020-01-24 at 2 30 37 PM" src="https://user-images.githubusercontent.com/60377/73109045-ebd81b80-3eb6-11ea-9bb5-392756a5c0b8.png">

Changing the values to a scale of 1 and gravity of bottom-left it essentially zooms in on the bottom 1/4 of the layer contents and displays "correctly".

<img width="1136" alt="Screen Shot 2020-01-24 at 2 40 22 PM" src="https://user-images.githubusercontent.com/60377/73109243-7882d980-3eb7-11ea-85fb-98a105869898.png">

**Comment by prime31** [comment]
Adding more data as I dig deeper. It turns out all I have to do is call `sg_setup(&(sg_desc){});` and no other Sokol methods and that is all it takes to make the window render only to the bottom 1/4. Still digging in to see what is going on in sg_setup.

**Comment by prime31** [comment]
`glEnable(GL_SCISSOR_TEST);` is the culprit!

**Comment by prime31** [comment]
Annnnnd closing this out. Turns out it is fixed for the next SDL release: https://hg.libsdl.org/SDL/rev/46b094f7d20e

**Comment by floooh** [comment]
Ooops, accidentally reopened this, nevermind.
