### ISSUE TITLE
Separate sg_draw to avoid confusion 

### ISSUE THREAD

**Issue by amerkoleci** [floooh/sokol#254]
Currently sg_draw handles indexed and non indexed drawing with instance count, maybe separate in sg_draw_indexed, indexed instanced etc, what do you think?

**Comment by floooh** [comment]
I'll think about the consequences but currently I'm not fond of the idea :) Whether to use indexed or non-indexed rendering must already be configured before the draw call in the pipeline object so that sg_apply_bindings() can do a proper validation check whether an index buffer is provided in the bindings. This check would need to be delayed to the actual draw call.

If there are "real world situations" where it makes sense to render the same data indexed and non-indexed it might make sense though, but I can't think of any right now.
