### ISSUE TITLE
Generate artifacts using github actions

### ISSUE THREAD

**Issue by amerkoleci** [floooh/sokol#257]
Hi,

I think would be cool to have latest samples downloaded from github, I have added artifacts build in my engine as well (https://github.com/amerkoleci/alimer/actions/runs/32265378)

I can submit PR in case.

Thanks

**Comment by floooh** [comment]
That's a good idea, I'm not sure if it makes much sense for the samples, but I've been looking for a better solution for the shader compiler executables (currently I compile those locally and commit them to the sokol-tools-bin repository).

I need to figure out a solution that not every (potentially buggy) commit triggers a "deployment", I guess the best solution is to run tests before, and only update the artefacts when those tests run successfully.

Thanks for the suggestion!

**Comment by floooh** [comment]
(PS: a PR for the sokol-samples would still be welcome, if you wanna give it a shot)

**Comment by amerkoleci** [comment]
Some question, how do I specify the output path?
Now fips builds in the repository folder/../fips-build/ etc

Any change how can I build with lets say:
cmake --build . --target install

Thanks

**Comment by floooh** [comment]
Not possible at the moment because too many things depend on it both on the python and cmake side (there's a fixed subdirectory structure to separate the different build configs from each other etc).

But the output path is guaranteed to be:

```../fips-sdk/[project-name]/[config-name]/```

But under there it's platform-specific again:

- under Windows there's a bunch of exe files: ```[target-name].exe```
- under Linux the same, but no file extension: ```[target-name]```
- under macOS (and iOS), for windowed apps, there are app-bundle directories: ```[target-name].app```, and for command line apps it's like Linux
- under emscripten, one .wasm, .html and .js file per target: ```[target-name].wasm```, ```[target-name].html```, ```[target-name].js```
- under Android it's a bunch of .apk files (I think ```[target-name].apk```

I don't know if cmake's install() function and cpack can actually deal with such scenarios (having more than one output file per target)

You should be able to invoke the cmake build "manually" in the build directory created by cmake via ```fips gen``` (in ```fips-build/[project-name]/[config-name]```) like this (as example):

```
cmake --build . --config Debug --target cube-wgpu -- -j6
```

The actually important stuff is

```
cmake --build .
```
