### ISSUE TITLE
Sokol imgui errors

### ISSUE THREAD

**Issue by gavriil07** [floooh/sokol#260]
```
sokol_imgui.h:777:33: warning: implicit declaration of function ‘_simgui_is_osx’ [-Wimplicit-function-declaration]
  777 |     io->ConfigMacOSXBehaviors = _simgui_is_osx();
sokol_imgui.h:929:26: error: ‘SAPP_MODIFIER_ALT’ undeclared (first use in this function)
  929 |     io->KeyAlt = (mods & SAPP_MODIFIER_ALT) != 0;
sokol_imgui.h:930:27: error: ‘SAPP_MODIFIER_CTRL’ undeclared (first use in this function)
  930 |     io->KeyCtrl = (mods & SAPP_MODIFIER_CTRL) != 0;
```
Before I included sokol_imgui.h, I defined SOKOL_IMGUI_NO_SOKOL_APP

**Comment by floooh** [comment]
Whoops, looks like I forgot to put an #ifndef SOKOL_IMGUI_NO_SOKOL_APP around some new code. Thanks for spotting that (I should add an automated compile test for this too).

**Comment by floooh** [comment]
Ok, should be fixed in this commit:

https://github.com/floooh/sokol/commit/196aa649f15a7ef05af64fedf5c90f64dc6d2fdd

I also rewrote the imgui-metal sample in sokol-samples to use sokol_imgui.h with SOKOL_IMGUI_NO_SOKOL_APP defined:

https://github.com/floooh/sokol-samples/commit/6e5d16b3df1c1dfb5f68b9d79b2f70a6b3a601bb

This should prevent that the feature regresses in the future because it's compiled during CI.

**Comment by gavriil07** [comment]
Thank you @floooh !! :)
