### ISSUE TITLE
SAAP Middle Mouse detection on OSX ?

### ISSUE THREAD

**Issue by melMass** [floooh/sokol#261]
Hi,

I'm trying to catch the **middle mouse button** in a `sapp_event` but it is not firing under OSX:

```c
static void event(const sapp_event* e) {
   assert((e->type >= 0) && (e->type < _SAPP_EVENTTYPE_NUM));
   if(e->type == SAPP_EVENTTYPE_MOUSE_DOWN){

        if (e->mouse_button==0){
            puts("Left Click");
        }
        if (e->mouse_button==1){
            puts("Right Click");
        }
        if (e->mouse_button==2){
            puts("Middle Click");
        }

    }
}
```

Do you know a workaround?

Thanks

**Comment by floooh** [comment]
Looks like I forgot to implement on macOS:

https://github.com/floooh/sokol/blob/07ca7631ee9a0854a0f269bd53df5a54fe235bd5/sokol_app.h#L1654-L1665

...probably because macOS has no "obvious" callbacks for the middle mouse button, it seems to be handled through a callback otherMouseDown/Up:

https://developer.apple.com/documentation/appkit/nsresponder/1525719-othermousedown?language=objc

I actually need to figure out how to test middle mouse button with a touchpad (or I guess attaching a PC mouse should work as well for testing).

Thanks for the bug report!

**Comment by floooh** [comment]
I added a "blind" fix here:

https://github.com/floooh/sokol/commit/d8454bf1f6d1066758ed088f63a342c8ac4e75d4

But I currently don't have a way to test this, a "bare" MBP doesn't seem to have a way to simulate a middle mouse button press, I'll try to test tomorrow when I have access to a PC mouse :)

Feel free to reopen the issue if something doesn't work.

**Comment by melMass** [comment]
@floooh Yes !! It does work thanks.

I guess the reason this callback is different in Apple's API is that, as you said, most mac don't use PC mouse and there is no middle mouse concept in any of Apple's hardware that I know of. 

It's still quite standard to use this binding in most software! 

Can you reference this issue in the commit once it's in master ?

Thanks again

**Comment by melMass** [comment]
I realize it is already in master !! thanks
