### ISSUE TITLE
[[point_size]] in msl 

### ISSUE THREAD

**Issue by pjako** [floooh/sokol#27]
Not sure if this is really a Sokol problem but referencing
https://github.com/KhronosGroup/SPIRV-Cross/issues/169
it does not seem to be a problem with Oryol?

So the problem is currently, if a msl defines the out struct of the vertex shader with a [point_size]
```
struct main0_out {
 float gl_PointSize [[point_size]]; // This by default is always in the compiled shader
};
```
Sokol/Metal complains: Compiler failed to build request
Vertex shader writes point size but inputPrimitiveTopology is MTLPrimitiveTopologyClassTriangle

Could this something specific to the Metal API Validation being enabled?
Currently fixed the problem in the spirv-cross compiler with "opts.point_size_compat = true" but thats not good solution.

**Comment by floooh** [comment]
Good catch, I had to dig a bit into the Metal documentation to find out what's going on.

Sokol currently sets the ```inputPrimitiveTopology``` on the MTLRenderPipelineDescriptor:

https://github.com/floooh/sokol/blob/c4623b95d9a1ce53558b93fe9ec0a335b1fca93b/_sokol_gfx_metal.impl.h#L1200

Oryol doesn't do this (so that's the reason why it works there). The primitive topology is only needed with this rendered-layering-stuff, which sokol isn't supporting currently anyway:

https://developer.apple.com/documentation/metal/mtlrenderpassdescriptor/1437975-rendertargetarraylength

Since SPIRVCross is always emitting point size, it also means that it is incompatible with this layered rendering, might be worth writing a ticket there too to make them aware.

Also, the feature only exists on MacOS, not iOS, so it is fairly useless IMHO. I'll go ahead and remove this code from sokol_gfx...

**Comment by floooh** [comment]
PS: the SPIRVCross version used in oryol-shdc is fairly old, before writing a ticket there I should first upgrade the dependencies. I was planning to do that when I move Oryol over to sokol_gfx, definitely won't happen before end of the year though.

**Comment by floooh** [comment]
Ok, fix is in https://github.com/floooh/sokol/commit/8ec6a1dbc90a0b9fe5974f30e348c2bae02131a4 :)

**Comment by pjako** [comment]
Thanks for acting so quickly!
A bit ot: I also had to change the oryol shader compiler. Sokol does not like non continuous locations for vertex attributes. (Also hard coded vertex property names seem like an unnecessary burden)
See: [31fb3dc](https://github.com/pjako/oryol-tools/commit/bd9433eebd34d6f58695a74217fda8b821fcc005)

**Comment by floooh** [comment]
Yes I have both on my mental todo list to change for Oryol. The hardcoded vertex attribute names with gaps inbetween will go when Oryol moves to sokol.
