### ISSUE TITLE
Sokol + ANGLE

### ISSUE THREAD

**Issue by prime31** [floooh/sokol#272]
I was thinking about slapping ANGLE onto Sokol to see what the performance is with the different backends. ANGLE requires ES2/3 but Sokol uses Core on desktop. What would you recommend as the easiest path to getting Sokol desktop to be ES2/3 compliant?

**Comment by floooh** [comment]
For sokol_gfx.h you can try building the GLES3 code path on desktop (define SOKOL_GLES3 instead of SOKOL_GLCORE33 before including the implementation), you just need matching GL headers somewhere (and include them first).

It's not that easy for sokol_app.h though, does ANGLE have its own GL context initialization functions, or does it offer something like EGL?

I would probably start with one of the ANGLE demos, initialize sokol_gfx.h after the GL context has been initialized, and then replace all the GL calls with sokol_gfx.h calls.

The next steps depend on whether you want to use sokol_app.h for window creation and input (this would need changes to sokol_app.h)

**Comment by prime31** [comment]
Thanks! I’ll give it a go. I’m using SDL so I won’t have any issues with Sokol app. ANGLE provides all the GL functions as well so that’s all covered.
