### ISSUE TITLE
Vulkan plans?

### ISSUE THREAD

**Issue by ompadu** [floooh/sokol#285]
Hi, I've been following your work since around just starting the Nebula 3 Device and in that time I've learned a lot from you, so I think a thank you might be in order :)

I've been reading every bits connected to implementing Vulkan in sokol_gfx found in the issues and change log. I thought I should ask you what are the most recent plans regarding this toppic.

**Comment by floooh** [comment]
No immediate plans :)

But the soon-to-land experimental WebGPU backend has resource management that would look quite similar to Vulkan, and the required line count for resource management was my main concern so far. So maybe with the resource handling code shared between the WebGPU and a hypothetical Vulkan backend it might be an option.

But to be honest, don't hold your breath, as long as the OpenGL situation on Linux or Android doesn't completely fall apart and GL isn't usable anymore there, a Vulkan backend wouldn't make all that much sense (because sokol_gfx.h is a fairly "traditional" single-threaded triangle-rendering API, you would most like not see any performance benefits, at least not with a good desktop GL driver like NVIDIAs).

**Comment by ompadu** [comment]
Thank you for taking the time to answer. Sorry I took so long to reply. 
I understand better the situation around sokol_gfx.h and indeed a Vulkan backend doesn't make very much sense.
