### ISSUE TITLE
sokol_gfx/sokol_app: GL loader

### ISSUE THREAD

**Issue by lithiumtoast** [floooh/sokol#302]
When using `sokol_gfx` without `sokol_app`, there is no convenience of GL loader which is found in `sokol_app`. 

My use case is using `sokol_gfx` with SDL2. What I end up doing is copying the GL loader from `sokol_app` or use something like GLEW.

The suggestion is to move the GL loader from `sokol_app` to `sokol_gfx` and expose a public API function that performs the loading. If `sokol_gfx` does not have the magic constant defined, the function does nothing.

What do you think?

**Comment by floooh** [comment]
I'd like to keep it as it is (keep the GL loader code outside sokol_gfx.h). The reason is that a GL loader is very target-platform specific, and sokol_gfx.h would suddenly need a new "dimension" of platform-specific code: not only the backend 3D-API, but also the operating system.

sokol_app.h is mostly platform-specific code anyway (and very little 3D-backend-specific), so I think the GL loader fits better in there (and it's more like a convenience hack anyway when sokol_gfx.h is used with sokol_app.h).

Btw, I'd recommend a light-weight GL loader like https://github.com/mosra/flextgl over GLEW, this adds much less code and binary size to the project because it generates a specialized header/source pair only for the actually used GL version and required extensions.

**Comment by floooh** [comment]
btw... a very longtime goal (but I don't know yet whether it is actually realistic) is to make the sokol headers entirely independent from system headers and ObjC. If this is ever started that would be a situation where the current GL loader behaviour can be reconsidered, since sokol_gfx.h would then need to embed a lot of platform-specific structs and function declarations anyway.

**Comment by lithiumtoast** [comment]
OK, I understand. When I was looking deeper into it, it seems that `sokol_app` doesn't support a GL loader for Linux. This would mean I would have to make some extensions to `sokol_gfx` anyways since I use `sokol_gfx` as a shared library for a good amount of desktop platforms. The extension is basically a "glue" for SDL2; loading GL, setting up a "renderer" to fill `sg_desc`, etc.

**Comment by floooh** [comment]
> doesn't support a GL loader for Linux

That's because on Linux a GL loader usually isn't needed, it's enough to include the <GL/gl.h> header and link with 'GL'. AFAIK GL loaders are really just a Windows thing because the Microsoft Windows SDK doesn't come with uptodate GL headers.

**Comment by lithiumtoast** [comment]
Ah yes, that makes sense, thanks.

**Comment by edubart** [comment]
I want to share here that GLAD is a very good GL loader option too, you can configure and generate its headers on its website https://glad.dav1d.de/ . I personally like more then flextgl.

**Comment by floooh** [comment]
NOTE: this PR will move the GL loader from sokol_app.h to sokol_gfx.h, and for non-Win32 platforms, sokol_gfx.h will include the system's GL headers. I think this should fix most inconveniences when using the sokol_gfx.h backend without sokol_app.h (and even when using sokol_app.h and sokol_gfx.h are used together, the implementation include order doesn't matter anymore, which should also fix a common confusion).
