### ISSUE TITLE
Borderless windows

### ISSUE THREAD

**Issue by medvednikov** [floooh/sokol#313]
Similar to GLFW_DECORATED 0

`fullscreen` option on macOS uses the slow full screen mode which results in unskippable animations.

Borderless windows can also be used not in full screen mode.

**Comment by floooh** [comment]
IMHO we shouldn't have two different fullscreen modes because that complicates the API and only makes sense on some desktop platforms. Maybe it makes sense to change the current fullscreen code to use a borderless window instead, but I don't know about that (because the "maximize" button in window titlebars also switches to fullscreen mode).

Also I can change with a swipe between fullscreen applications which wouldn't work with a borderless window.

Maybe there's a way to disable the animation programmatically, I need to check.

But all in all I feel like this ticket, and https://github.com/floooh/sokol/issues/311 would make more sense if sokol_app.h would be expanded with a proper multi-window API. 

I'm slowly warming up to the idea because it would enable using Dear ImGui's detachable windows, but it's definitely a very different scope (essentially sokol-app 2.0).

**Comment by medvednikov** [comment]
There's no way to disable that animation, not since Lion I think.

**Comment by medvednikov** [comment]
I think Apple's native full screen mode should be avoided. It's slow, it messes up FPS, it has unskippable animations.

**Comment by medvednikov** [comment]
@floooh I implemented "soft" fullscreen on macos in my fork:

https://github.com/vlang/v/commit/3478430762552cbe11b07fc5a95091d340f6a83f

Had to add a new NSWindow class so that the events would be handled.

**Comment by medvednikov** [comment]
Just created a PR. https://github.com/floooh/sokol/pull/314

**Comment by floooh** [comment]
I'm closing this issue because it overlapped with the fullscreen topic. Maybe when the multi-window-topic gets "interesting" it makes sense to give more control over window decorations.
