### ISSUE TITLE
Running out of resources when creating and destroying buffers with the Metal backend

### ISSUE THREAD

**Issue by kneeko** [floooh/sokol#32]
I'm running into trouble when creating and destroying buffers (or pipelines) every frame with the Metal backend.

[Here's a test case](https://gist.github.com/kneeko/3bb0793d5b6fc380cb619e3ddb19b035) made by moving the vertex buffer creation from `init` to `frame` in the `triangle-metal.c` sample and destroying it after using it. After a few seconds it fires an assert:
```
Assertion failed: (_sg_mtl_free_queue_top > 0), function _sg_mtl_add_resource, file sokol/_sokol_gfx_metal.impl.h, line 379.
```
One possible error could be with the logic in `_sg_mtl_garbage_collect`, since it is called after every frame via `sg_commit` but seems to never process any of the resources in the release queue. Specifically, on [line 413](https://github.com/floooh/sokol/blob/master/_sokol_gfx_metal.impl.h#L413) it checks if frame index of the oldest resource is less than the current frame + inflight frames + 1, which should always be true if the frame index only increases and inflight frames is positive.

**Comment by floooh** [comment]
Thanks for the bug report! I'll have a look, resource destruction isn't tested in the sokol samples, so that's likely to have slipped through. The timing is good since today I wanted to work on the Oryol-sokol migration for the Metal backend, Oryol has a resource stress test sample which hopefully would also trigger this bug (I'll test that too).

**Comment by floooh** [comment]
Ok, it was actually 2 problems: first in the garbage-collect function the release-path was never called because the check was broken (as you suspected), and the second part was that the now free pool index was never put back into the 'free queue'.

I made both those things a bit more robust and cleaner now, and I also added a new stress-test to the samples (https://github.com/floooh/sokol-samples/blob/master/metal/releasetest-metal.c), same as your test case, but I'm also creating and destroying the shader and pipeline (and I reduced the resource pool sizes so that the bug would trigger earlier).

Thanks again for the bug report :)
