### ISSUE TITLE
sokol_gfx.h: using cubemap with mipmaps as color attachment will generate incomplete framebuffer error

### ISSUE THREAD

**Issue by ukabuer** [floooh/sokol#330]
I'm using the `SOKOL_GLCORE33` backend and the following C++ code will generate an incomplete framebuffer error, which uses a cubemap texture with mipmaps as the color attachment.

The error occurs when `pass_desc.color_attachments[0].mip_level` is set to value other than 0.
```c++
sg_image_desc image_desc{};
image_desc.type = SG_IMAGETYPE_CUBE;
image_desc.render_target = true;
image_desc.width = 128;
image_desc.height = 128;
image_desc.num_mipmaps = 4;
image_desc.pixel_format = SG_PIXELFORMAT_RGBA32F;
image_desc.min_filter = SG_FILTER_LINEAR_MIPMAP_LINEAR;
image_desc.mag_filter = SG_FILTER_LINEAR;
auto image = sg_make_image(image_desc);

sg_pass_desc pass_desc{};
pass_desc.color_attachments[0].image = image;
pass_desc.color_attachments[0].face = SG_CUBEFACE_POS_X;
pass_desc.color_attachments[0].mip_level = 1;
auto pass = sg_make_pass(pass_desc); // "Framebuffer completeness check failed!"
```
 
And I managed to fix this error by adding the following codes to `_sg_gl_create_image` function, but I don't know what's the secrets here :)
```c
if (SG_IMAGETYPE_CUBE == img->cmn.type && img->cmn.num_mipmaps > 1) {
    glGenerateMipmap(GL_TEXTURE_CUBE_MAP);
}
```

**Comment by floooh** [comment]
One thing that looks strange is that the cubemap's mipmap chain is incomplete (4 mipmaps means there's only 128, 64, 32 and 16 sized mipmaps, 4, 2 and 1 are missing). AFAIK glGenerateMipmap() completely replaces the mipmap chain (makes it complete).

I don't know why an incomplete mipmap chain would lead to a failing framebuffer completeness check though, this needs investigation. I need to do something about incomplete mipmap chains anyway (see: https://github.com/floooh/sokol/issues/128)

**Comment by floooh** [comment]
...googled around a bit more: it seems that desktop GL allows incomplete mipmap chains as long as GL_TEXTURE_MAX_LEVEL is set (which sokol_gfx.h doesn't do). I haven't found definitive information for GLES2 yet, but since GLES2 doesn't have GL_TEXTURE_MAX_LEVEL I assume that a texture in GLES2 must either have one mipmap surface, or a complete mipmap chain down to 1x1 pixels.

Because of this restriction I tend to also only allow a single mipmap, or a complete mipmap chain in sokol-gfx, the validation layer is basically missing a couple of checks (if an image only has a single mipmap it must be used with one of the non-mipmap filters, otherwise it must have the complete mipmap chain).

**Comment by floooh** [comment]
Oooh old issue. This has been fixed in the meantime. The sokol-gfx GL backend now generally sets GL_TEXTURE_MAX_LEVEL on texture creation.
