### ISSUE TITLE
Pixel coordinate, mouse pos, etc for fragment shader.

### ISSUE THREAD

**Issue by nightlifelover** [floooh/sokol#333]
Well this is a question not an issue:

How can I get things like the mouse position, a pixels coordinate, the with / height of the viewport and other inputs into a fragment shader using sokol-gfx and sokol-shdc? The only way I saw so far is through a vertex shader but can I also input some things directly into a fragment shader?

**Comment by nightlifelover** [comment]
This is my attempt to draw a circle with ended up looking like a ellipse because I do not take the viewport shape into account:

```
@vs vs
in vec4 position;
in vec4 color0;

out vec4 color;
out vec4 vertex_pos;

void main() {    
    vertex_pos = position;
    gl_Position = position;
}
@end

@fs fs

in vec4 color;
in vec4 vertex_pos;
out vec4 frag_color;

void drawCircle(vec2 pos, float r, float x, float y, vec4 circleColor, inout vec4 fragColor) {
    float a = abs(x - pos.x);
    float b = abs(y - pos.y);
    float d = sqrt(a*a + b*b);
    
    float m = smoothstep(r-0.003, r+0.003, d);                  
    fragColor = mix(circleColor, fragColor, m);
}


void main() {

    drawCircle(vec2(0.0, 0.0), 0.5, vertex_pos.x, vertex_pos.y, vec4(1,0,0,0), frag_color);
}
@end

@program pirate vs fs
```

I also saw an example where a circle was approximated using triangles, which one would be preferable for a 2D app?

**Comment by nightlifelover** [comment]
Please do not worry about too much, I am learning by digging through the examples. Will probably write a tutorial once I am done.

**Comment by floooh** [comment]
Hi, getting uniform data into the fragment shader works the same as in the vertex shader, you define a ```uniform bla { ... };``` in the @fs block in the shader source code, and on the CPU side, you use ```sg_apply_uniforms(SG_SHADERSTAGE_FS, ...)``` to update the uniform data somewhere after calling ```sg_apply_pipeline()``` and before ```sg_draw()```.

The blend-sapp sample uses a uniform block in the fragment shader, this is the shader side:

https://github.com/floooh/sokol-samples/blob/4ebdbe8a7b49b2898d31456503b497eed0600ffd/sapp/blend-sapp.glsl#L14-L16

...and this is the CPU side call to sg_apply_uniforms() (note the SG_SHADERSTAGE_FS):

https://github.com/floooh/sokol-samples/blob/4ebdbe8a7b49b2898d31456503b497eed0600ffd/sapp/blend-sapp.c#L141

**Comment by floooh** [comment]
PS: to get the shader 'aspect-ratio-independent', you can also look at the sdf-sapp sample (https://floooh.github.io/sokol-html5/sdf-sapp.html), in this case the correction happens in the vertex shader.

I'm passing an 'aspect' factor into the vertex shader here:

https://github.com/floooh/sokol-samples/blob/4ebdbe8a7b49b2898d31456503b497eed0600ffd/sapp/sdf-sapp.glsl#L10

Which is multiplied into the incoming vertex x-position:

https://github.com/floooh/sokol-samples/blob/4ebdbe8a7b49b2898d31456503b497eed0600ffd/sapp/sdf-sapp.glsl#L37

...and the aspect value is computed here from sapp_width() and sapp_height() (both are guaranteed to be > 0, even when the window is minized):

https://github.com/floooh/sokol-samples/blob/4ebdbe8a7b49b2898d31456503b497eed0600ffd/sapp/sdf-sapp.c#L52-L55

If all your computations are in the fragment shader, the same idea should work by using gl_FragCoord instead of the vertex position (although I don't remember why I didn't do this but used the vertex position instead).

**Comment by floooh** [comment]
> I also saw an example where a circle was approximated using triangles, which one would be preferable for a 2D app?

Using "traditional" triangle rendering instead of shadertoy-style "do all rendering in the fragment shader via a fullscreen rectangle"  will most likely be better for low-end GPUs, but it depends what you want to do for more complex scenes. If your goal is to render complex scenes with path-tracing (e.g. signed-distance-field stuff like the sdf-sapp sample above), then your current approach is better, but if you want to render more 'traditional' scenes, then it's better to let the GPU rasterizer do all the work :)

**Comment by nightlifelover** [comment]
Thanks a lot for you'r quick answer! Really appreciate it!
