### ISSUE TITLE
Allow sokol_gfx backend to be chosen at application start

### ISSUE THREAD

**Issue by TheSpydog** [floooh/sokol#338]
Currently, the only way to select a graphics backend is at compile time with a preprocessor define. This is not ideal for application consumers, who may be better served by a different graphics API depending on their hardware.

For instance, if I ship a game for Windows using the OpenGL backend, some users might have lower-end laptops with less-than-stellar GL drivers but decent D3D11 support. Or a user may have a MacBook with an integrated card that runs GL faster than Metal. (This does happen unfortunately... my MacBook Pro is one of those unlucky machines. ☹️ ) Or maybe a user wants to try running a GL app on Vulkan via ANGLE, which requires GLES.

These examples may seem contrived but I've run into all three in real-world applications. If there was a mechanism in sokol_gfx to allow for multiple supported backends and selecting them at application start time, I think that would be very useful.

I'm not sure if bgfx allows for this, but I know [FNA3D](https://github.com/FNA-XNA/FNA3D) does. The typical use case is that a user passes a command line argument to the game (e.g. `/gldevice:<OpenGL/D3D11/Metal/Vulkan>` ), and the game will boot with whichever they have selected (if it's available, with fallbacks in case it's not). This does require the application to set up their windows appropriately based on the selected backend, but that shouldn't be _too_ much of a hassle to put on sokol_gfx users...

FNA3D does have the advantage of having a shared bytecode shader format that is translated at runtime to all possible backends. Since sokol requires prebaked shaders for each backend, that piece might be a bit tricky to figure out. Although I suppose the simplest solution is to allow the sokol_gfx user to #define all possible backends they want to support for a given platform, and then they are responsible for distributing the various shaders as appropriate.

Anyway... I have no idea how much of a refactor this would be, and perhaps there are other factors I'm not taking into account, but if possible, I think this would be a useful and practical addition to the library.

**Comment by floooh** [comment]
Hmm, not a big fan of the idea to be honest, it should be a bit easier now with the code cleanup I did in January but it will be a lot of changes for a somewhat esoteric use case. Also the whole thing is a bit more complicated then just replacing all #ifdefs with ifs(), because it can only work for certain API combinations on certain platforms (e.g. on macOS and iOS: GL + Metal (however why even use GL on Apple platforms when it's deprecated there), on Windows it would be GL + D3D11 (same situation, why use GL on Windows when there's D3D11), on Linux only GL, and on the web WebGPU vs WebGL.

For a game I would probably compile out two executables, and either have two start menu entries, or handle the API selection in a separate launcher executable which then launches the right executable. On the web I'd do the same with two WASM blobs (one for WebGPU and WebGL), and either load the WebGPU blob or the WebGL blob.

Another idea would be to compile sokol_app.h and sokol_gfx.h into a DLL and compile that out for each backend, and then at runtime, load the right DLL for the selected backend. In sokol_app.h this would require to compile SOKOL_NO_ENTRY, because you would need your own application entry point to load the right DLL before entering sokol_app.h.

For the shader code it might already be possible, sokol-shdc already supports having different shader versions side-by-side for the situation where WebGL2 needs to fall back to WebGL1, the same should also work for the other backends.

**Comment by floooh** [comment]
A few more thoughts after thinking a bit more about it (still not a big fan of the idea though, but I think it could be implemented with much "disruption", at least in sokol_gfx.h:

- a new config-define ```SOKOL_MULTIPLE_BACKENDS``` (or similar)
- if SOKOL_MULTIPLE_BACKENDS is set, it's possible to compile with multiple SOKOL_xxx backend defines (e.g. SOKOL_D3D11 and SOKOL_GLCORE33), but combinations that don't make sense should be caught as errors (e.g. SOKOL_D3D11 combined with SOKOL_METAL)
- ```sg_desc``` needs a new item ```sg_backend backend;``` (this would also make the current ```force_gles``` item obsolete, and would be a bit cleaner.
- the ```SG_BACKEND``` enum should get a new item ```SG_BACKEND_DEFAULT = 0```
- most places where backend-specific ```#if...#elif...#endif``` 'cascades' should be replaced with ```#if...#endif```
- 'backend-splitter functions' like this need an additional if (...) check if SOKOL_MULTIPLE_BACKENDS is enabled: https://github.com/floooh/sokol/blob/a3278884e3895d996e79a38bd74e44826e3efb74/sokol_gfx.h#L11675-L11689
- all the internal resource structs _sg_buffer_t, _sg_image_t etc... must be changed from typedefs to something which looks more like this (but without the #elif's): https://github.com/floooh/sokol/blob/a3278884e3895d996e79a38bd74e44826e3efb74/sokol_gfx.h#L3625-L3636

...and a similar changes must be applied to sokol_app.h (it's a bit more complicated there because the code isn't as strictly separated by 3D API backends, but instead by operating system).

**Comment by TheSpydog** [comment]
> Another idea would be to compile sokol_app.h and sokol_gfx.h into a DLL and compile that out for each backend, and then at runtime, load the right DLL for the selected backend

I think this approach makes the most sense. It should be simple enough to do, and it removes any maintenance burden in the sokol library itself.

Thank you for investigating how this could work. :) I'll go ahead and close the issue since the DLL solution you described should be sufficient for my use case.

**Comment by floooh** [comment]
If you stumble over any problems with the DLL approach, please open a ticket, I'd like to make this use case work well. NOTE the SOKOL_DLL define which prefixes the functions with __declspec(dllexport/dllimport), there's also a sokol-sample which uses the sokol headers as a DLL:

https://github.com/floooh/sokol-samples/blob/f92aec39e65a02b2286e343c275be36ef937f41b/sapp/CMakeLists.txt#L531-L539

For loading the DLL manually at runtime it probably would make sense to add function pointer typedefs to the sokol-headers (maybe only when SOKOL_DLL is defined), to simplify the function lookup.

**Comment by code-disaster** [comment]
> For loading the DLL manually at runtime it probably would make sense to add function pointer typedefs to the sokol-headers (maybe only when SOKOL_DLL is defined), to simplify the function lookup after loading the DLL.

Just a crazy thought, but maybe it's possible to "automate" that with the bind-gen stuff you're working on? :)

**Comment by floooh** [comment]
I had a similar train of thought when thinking about the hot-reloading requirements that recently popped up (where the sokol functions are called through a jump table). One could generate loader-wrappers which basically work like a GL loader (load a DLL populate a function pointer table, and expose "regular" functions which go through the jump table so that calling code can simply continue including the regular sokol-header for the API declarations, but link with a generated loader-implementation)

**Comment by SoylentGraham** [comment]
Just to weigh in on this, (late I know, but I was searching to see if someone had similar problems to me), I have been using Metal & GLES together (on ios & mac) by putting the IMPL and include, per-backend inside a namespace. (so C++ solution)

This was actually working fine until a recent update-to-latest-sokol where 1 symbol has become ambiguous...

But I will be switching to the DLL approach :)
