### ISSUE TITLE
Plans to support d3d9?

### ISSUE THREAD

**Issue by medvednikov** [floooh/sokol#352]
I'm using Sokol for a UI library, and lots of older windows machines don't support d3d11.

d3d9 is much simpler than d3d11, in imgui the d3d9 backend is <300 lines: https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_dx9.cpp

But looking at the way Sokol is structured, it looks like adding a new backend would be a lot more work.

**Comment by floooh** [comment]
Yeah, D3D9 would be quite a bit more code compared to the D3D11 backend because of the granular render state, it would look more like the GL backend (with a render state state cache implementation etc...).

I would really not want to add a D3D9 backend, because that a generall a lot more hassle and would only be useful for WindowsXP machines (which isn't supported by Microsoft anymore). It's also a problem to download and install the last D3D9 SDK (June 2010), AFAIK this SDK version is no longer available from Microsoft (only the runtime), and it doesn't install as is on newer Windows machines. 

WinXP machines might be better served with the OpenGL backend.

A potential solution would be to support DX9 feature-level GPUs (see here: https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-devices-downlevel-intro#overview-for-each-feature-level)

However, DX9 feature level GPUs only support shader model 2.0, which would be a massive step back from shader model 4, I doubt it would be possible to cover SM 2.0 to SM 4.0 with shader cross-compiling from the same shader source.
