### ISSUE TITLE
is sokol_app for Android working?

### ISSUE THREAD

**Issue by albertofustinoni** [floooh/sokol#368]
I'm trying to get sokol_app/sokol_gfx for Android working but it always fails at

```
EGLContext context = eglCreateContext(display, config, EGL_NO_CONTEXT, ctx_attributes);
    if (context == EGL_NO_CONTEXT) {
        return false;
    }
```

in `_sapp_android_init_egl` (context is always EGL_NO_CONTEXT) 

This when:
- Compiling with `SOKOL_GLES3` as the API
- Linking against the android NDK (v30)'s included libs
- Running on the Android emulator (x86_64 on Windows and macOS) as well as an actual device (Pixel 4a)

Is Sokol currently working on Android? Unfortunately I am unable to get a debugging session working so the amount of investigation I can do is limited.

**Comment by floooh** [comment]
About a month ago or so it was working on my old Pixel tablet. I think I'm testing with older SDK/NDK platform versions though:

https://github.com/floooh/fips/blob/8e67bb6810409fcfb43746ec24589f8df77b6525/mod/android.py#L119-L123

I'm currently charging my Android tablet and will give it a try later.

I had successfully debugged the sokol-samples Android demos with Android Studio as "standalone debugger" (when starting Android Studio you can select an APK to debug). I guess that Visual Studio can also debug Android executables, but I didn't get around testing that yet).

**Comment by albertofustinoni** [comment]
I managed to get past the `eglCreateContext` issue on the emulator (device is crashing for another reason, it turns out) by setting OpenGLES conformance to max supported.

Thank you Google for hiding that setting in the emulator's advanced settings page instead of being a property in the AVD device manager...

I'm desperate enough for a working debugger I'll try using Android Studio that way too - really wanted to avoid if possible...

**Comment by floooh** [comment]
Ah ok, I also just tested on my (fairly old) Nexus tablet and at least the sokol-samples are running, also those that use GLES3 features (with the Android SDK/NDK installed via fips). Only the samples that load data via sokol_fetch.h don't work because the resource files aren't copied into the APK currently.

![IMG_1007](https://user-images.githubusercontent.com/1699414/92408373-9139ba00-f13d-11ea-8218-2ef49f569cf7.JPG)

**Comment by floooh** [comment]
PS: if you want to try the sokol-samples:

```
...attach an Android device
> mkdir workspace
> cd workspace
> git clone https://github.com/floooh/sokol-samples
> cd sokol-samples
> ./fips fetch
> ./fips setup android
> ./fips set config sapp-android-make-debug
> ./fips make cube-sapp
...
> ./fips run cube-sapp
```
The last step should upload the 'cube-sapp' demo to the device and start it. I haven't tested this with the Android emulator though.

**Comment by albertofustinoni** [comment]
I managed to debug using Android Studio and fix my issue. Now my stuff runs finally.

When you say "the examples that use GLES3 features", do you mean that sokol can run on OpenGLES2 as well on Android?
When I tried compiling it with SOKOL_GLES2 I kept getting linker errors for three functions as below:

```
undefined reference to 'glVertexAttribDivisorANGLE'
undefined reference to 'glDrawElementsInstancedANGLE'
undefined reference to 'glDrawArraysInstancedANGLE'
```

So I thought it was not supported.

**Comment by floooh** [comment]
> do you mean that sokol can run on OpenGLES2 as well on Android

There's basically a "compile-time GLES2" mode (selected via SOKOL_GLES2 vs SOKOL_GLES3), but also a "compile-time GLES2" mode (when compiled with SOKOL_GLES3, but a GLES2 context should be used), the linker errors you are getting seem to indicate that the compile-time mode currently has problems (it should be easy to fix though).

As for the "runtime GLES2 mode": all the sokol-samples which don't require GLES3 features are setting the "sapp_desc. gl_force_gles2" hint, this is mainly so that those demos also run in WASM on browsers that don't support WebGL2, but the Android backend makes use of this flag too and requests a GLES2 context if the flag is present:

https://github.com/floooh/sokol/blob/00f81dc6251fa91697dc611abb42afa58479b7f3/sokol_app.h#L5659-L5666
