### ISSUE TITLE
Off the Wall Idea for Embedded

### ISSUE THREAD

**Issue by frink** [floooh/sokol#369]
I was wondering if you could run Sokol on top of KMS/DRM. I've seen a few GL examples of this (See: https://github.com/ds-hwang/gbm_es2_demo) but nobody has really put together a framework on top of KMS to make it truly usable. Curious if this was possible. Obviously this isn't probably a design goal of the lib...

**Comment by floooh** [comment]
I've been considering "bare metal support" for RaspberryPi 4, mainly because it would be fun to try out and directly boot into a minimal sokol program (like my emulators) from an USB stick in a fraction of seconds. Currently there are other more important things though ;)

I don't know if I would accept a PR for this (ideally it would only affect sokol_app.h, but not sokol_gfx.h). It probably makes more sense to create a separate mini-library which does the same things like sokol_app.h (setup the GL context and drive the frame-loop), similar to the ```xxx_entry.h/.c``` files in sokol-samples, for instance:

https://github.com/floooh/sokol-samples/blob/master/d3d11/d3d11entry.c
