### ISSUE TITLE
Multiple dlls with Sokol renderer.

### ISSUE THREAD

**Issue by andorxornot** [floooh/sokol#372]
Hi, Andre. 
I use Sokol for UI in VST plugin (with JUCE wrapper) and noticed one thing, it looks like Sokol is using static (or global) variables. So when i open several plugins in one program at the same time, the render breaks. ( 
Tell me, are there any ways to use several instances of the Sokol from different threads in one program (for me, it's DAW audio host)?

**Comment by floooh** [comment]
Yeah, that's going to be a problem. In general, most sokol headers expect that there is only one instance per process running. For some headers that's ineviatable (like sokol_app.h), for some headers (like sokol_gfx.h) it might be fixable but requires pretty deep changes.

Since the big internal sokol-gfx refactorings that happend this year it would be pretty easy to pass in a memory chunk where sokol-gfx stores its state (each sokol-gfx instance would also need its own GL context, and D3D or Metal device, so how multiple sokol-gfx instaces would be "orchestrated" in a single process is also an open problem, even when there's no global state).

Another problem where I don't have a good idea how to solve it is that I want to avoid to add a "context parameter" to each single sokol-gfx call.

One solution might be that all plugins that use sokol-gfx would need to use the same shared sokol-gfx instance instead of each plugin DLL initialized its own.
