### ISSUE TITLE
[FAQ] Minimal clear, using gles2 on ipad not clearing & causing GL_INVALID_ENUM

### ISSUE THREAD

**Issue by SoylentGraham** [floooh/sokol#375]
I'm just getting sokol_gfx integrated and replacing my old c++ bindings, so starting with a minimal implementation;

I have a GLView, which I'm manually repainting. In the view delegate `drawInRect` callback, (which is always on mainthread) I added 
```
glClearColor(1, 0, 0, 1);
glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);
```
This works. (no flip, no make-current-thread-context etc). Checked `glGetError()` before & after, always 0

I've got a sokol desc setup
```
sg_desc desc={0};
sg_setup(&desc);
```

From my `drawInRect` callback, I call a simple default pass to clear (viewrect x/y from the cgrect)
```
sg_pass_action mPassAction = {0};
mPassAction.colors[0] = {.action = SG_ACTION_CLEAR, .val = {0, 1, 0, 1}};
sg_begin_default_pass( &mPassAction, ViewRect.x, ViewRect.y );
sg_end_pass();
sg_commit();
```
this;
- Clears black (or, stays red if my raw gl code is still there)
- No Error at end of pass/commit
- On second frame, in `sg_begin_default_pass` has a glError of `GL_INVALID_ENUM`

I've tried
- Ensuring thread is set/madecurrent. (setting to null at end of frame flushes error, but otherwise no diff as already bound to context in thread)
- Adding setting GL_FRAMEBUFFER to 0 in my code (no diff)
- Removing my gl code (then clears black)
- Commenting out all the other gl calls in sokol (doing this has lead to clearing green, but still erroring!)

Just nailing down what else is being called, and which change allowed clear to correct colour...

Not seeing any memory corruption or anything odd (no odd params etc)
AFAIK no other gl code is called (unless deep inside ios, profiling calls hasn't revealed any). So I'm currently a bit stumped as to what is possibly causing the `GL_INVALID_ENUM`. 
It could be erroneous somewhere in ios or how I've got my glview setup... but I only get this error if I call sokol code. (Plus I think that default pass should be clearing without changing any sokol code)

**Comment by SoylentGraham** [comment]
commenting out 
`glBindFramebuffer(GL_FRAMEBUFFER, _sg.gl.cur_context->default_framebuffer);` in `_sg_gl_begin_pass`
Makes the green clear appear. Still errors, and `glError()` immediately after this call has no error.

**Comment by SoylentGraham** [comment]
If I switch to GLES3 so I can read the framebuffer bindings;
```
GLint drawFboId = 0;
GLint readFboId = 0;
glGetIntegerv(GL_DRAW_FRAMEBUFFER_BINDING, &drawFboId);
glGetIntegerv(GL_READ_FRAMEBUFFER_BINDING, &readFboId);
```
These are both `1` (GLKView is always rendering to it's own allocated buffer? a metal wrapper perhaps?)

Ipad Pro 24" 2020 on ios14...

**Comment by SoylentGraham** [comment]
Also, with GLES3 instead of GLES2, `_sg_gl_begin_pass` asserts at the end of the function with `glGetError() == GL_INVALID_FRAMEBUFFER_OPERATION`
Guessing that's the driver just being a little different (maybe GLES2 underneath is missing a check)

**Comment by SoylentGraham** [comment]
As soon as I started searching for `default_framebuffer` the answer revealed itself; (plus some documentation I missed - though the call order still wasn't super clear, so writing this out for anyone who finds the same problem)

I have to create my sokol context on the first render callback which sets up the default frame buffer :)

```
auto OnPaint = [this](CGRect Rect)
{
	[EAGLContext setCurrentContext:mOpenglContext];
	if ( mSokolContext.id == 0 )
	{
		sg_desc desc={0};
		sg_setup(&desc);
		mSokolContext = sg_setup_context();
	}
	// callbacks and render etc here
};
```

Notably, it seems like ios only sets up the frame buffer before rendering, NOT on context creation, this does NOT work
```
// on my create-stuff thread
mOpenglContext = [[EAGLContext alloc] initWithAPI:Api];
mView.context = mOpenglContext;
sg_desc desc={0};
sg_setup(&desc);
mSokolContext = sg_setup_context();

// on paint later will bind to 0
```

**Comment by SoylentGraham** [comment]
I think this is just PEBCAK, but... it wasn't obvious :) (just figuring out why my clear is h/2 and w/2, like the view rect and framebuffer size dont match)

**Comment by floooh** [comment]
Hmm, lot's of stuff to unpack :) 

Unfortunately, sokol_gfx.h can't assume that the framebuffer of the default pass has the id ```0``` because this is not true on various platforms (not just iOS) so what it does is querying the currently bound framebuffer in ```sg_setup()``` (which in turn calls ```_sg_gl_create_context()``` for the "default context"):

https://github.com/floooh/sokol/blob/36b35207c7016ef42c43c7425e21ffd4c11bf01b/sokol_gfx.h#L5586

The expectation is basically that you create and make active the GL context before calling sg_setup().

This "default GL context" will then be bound in sg_begin_default_pass():

https://github.com/floooh/sokol/blob/36b35207c7016ef42c43c7425e21ffd4c11bf01b/sokol_gfx.h#L6286

GLKView seems to do this automatically (make the GLKView GL context active as soon as it is created), but on other platforms this must be done explicitly before sg_setup() is called.

On macOS (which uses NSOpenGLView) this must be done explicitly, I think the best place to do this is in the prepareOpenGL callback:

https://github.com/floooh/sokol/blob/36b35207c7016ef42c43c7425e21ffd4c11bf01b/sokol_app.h#L2798-L2804

On other platforms this is usually done right after the GL context has been created:

Win32/WGL:

https://github.com/floooh/sokol/blob/36b35207c7016ef42c43c7425e21ffd4c11bf01b/sokol_app.h#L4640-L4646

It seems that some platforms also need to set the GL context at the start of each frame, for instance on Linux/GLX I do this:

https://github.com/floooh/sokol/blob/36b35207c7016ef42c43c7425e21ffd4c11bf01b/sokol_app.h#L8099

**Comment by floooh** [comment]
As for the "clear only clears w/2, h/2": This is because sokol-gfx resets the viewport and scissor before clearing to the framebuffer size that's passed into sg_begin_default_pass() here:

https://github.com/floooh/sokol/blob/36b35207c7016ef42c43c7425e21ffd4c11bf01b/sokol_gfx.h#L6288-L6289

If it only clears a quarter of the screen this means that there's a HighDPI mismatch. The GL framebuffer is high resolution, but the size passed into sg_begin_default_pass() isn't.

I had a similar problem with NSOpenGLView on macOS because of the Catalina breakage (and this problem still wasn't fixed so I had to implement a workaround. The problem was that the reported framebuffer size was wrong right after NSOpenGLView was created, instead I had to move querying the framebuffer size into the ```reshape``` callback:

https://github.com/floooh/sokol/blob/36b35207c7016ef42c43c7425e21ffd4c11bf01b/sokol_app.h#L2781-L2793

However on iOS the initial framebuffer_width/height is taken from UIScreen.mainScreen.bounds, which I then multiply by 2 if HighDPI rendering is requested:

https://github.com/floooh/sokol/blob/36b35207c7016ef42c43c7425e21ffd4c11bf01b/sokol_app.h#L3113-L3124

...and during frame rendering, the size is taken from GLKView.drawableWidth:

https://github.com/floooh/sokol/blob/36b35207c7016ef42c43c7425e21ffd4c11bf01b/sokol_app.h#L3057-L3058

(I'm actually not sure why I'm not using drawableWidth/Height also for the initial size)

**Comment by SoylentGraham** [comment]
I guess The width/height is a seperate issue, I'll figure out if the drawable rect is definitely different (my rect/onpaint is coming from the GLKView delegate's draw callback)

My initial confusion I think all stemmed from the fact that I didn't realise I *had* to make my own context wrapper, as I could happily make a `sg_context` AND draw with no errors on frame0. 

Also FYI (in case its some cause of problems) my `GLKView` is in a xib, with NO `GLKViewController`. (Allowing me to do metal & opengl in one app/view!)

**Comment by floooh** [comment]
> I had to make my own context wrapper

Hmm, I'm a bit confused by this. You shouldn't need to call ```sg_setup_context()``` unless you're going to use more than one GL context. sg_setup() already does this to create an internal default sokol-gfx context" (this does *not* create a GL context, just create a local "resource environment" for sokol-gfx):

https://github.com/floooh/sokol/blob/2cd00ec6c80d4ef05d0522c7c0a5de0fa6daaadd/sokol_gfx.h#L13969

On the GL backend, sg_setup_context() calls _sg_gl_create_context(), which queries the currently bound framebuffer id (which will bound each time sg_begin_default_pass() is called):

https://github.com/floooh/sokol/blob/2cd00ec6c80d4ef05d0522c7c0a5de0fa6daaadd/sokol_gfx.h#L5586

...and a context also creates its own global VAO object:

https://github.com/floooh/sokol/blob/2cd00ec6c80d4ef05d0522c7c0a5de0fa6daaadd/sokol_gfx.h#L5591

...but that's it.

**Comment by SoylentGraham** [comment]
If I had called `sg_setup()` in the draw callback, I think it would have been fine. (Evidently, as that's what I do now)

Now I think about it, if I was calling `sg_setup()` outside the gl's [current] thread (even if not from the draw callback), shouldn't some of the initialisation GL calls have failed?...
In fact, perhaps, when I was calling it before, there was no gl context at all (but again, no errors...)

I totally understand what's happening underneath re: contexts/sg contexts (I'm managing render contexts, flipping etc and sg is just the generic rendering). 
I just don't quite get why there weren't [more obvious] errors when I was doing it wrong :) (and wouldn't want others to have the same problem in future)

**Comment by SoylentGraham** [comment]
I do have it working, so don't spend too much time digging more into this, unless perhaps this crops up again for more users?

**Comment by floooh** [comment]
That's why I slapped a FAQ label to the issue :) But I'll close it anyway, otherwise it's too distracting.
