### ISSUE TITLE
"wgpu" build fail with last version of Emscripten

### ISSUE THREAD

**Issue by Maeiky** [floooh/sokol#377]
API change on v2.0.2 of Emscripten.

Here is one of the errors:

>  ../sokol\sokol_gfx.h:10771:5: error: unknown type name 'WGPUBindGroupLayoutBinding'; did you mean 'WGPUBindGroupLayoutEntry'?

Related to this change:
[https://github.com/emscripten-core/emscripten/commit/9010921ff2ac9ae2750cf23dc5653b9670a68e75#diff-e97d0c632ffc49fb045df614348718f5
](https://github.com/emscripten-core/emscripten/commit/9010921ff2ac9ae2750cf23dc5653b9670a68e75#diff-e97d0c632ffc49fb045df614348718f5)

**Comment by floooh** [comment]
The WebGPU has changed quite a bit since I wrote the WebGPU backend (especially the resource mapping and bindgroup areas have changed or will change), so the backend code needs to be updated at some time. I want to wait with this until the API has somewhat stabilized, and also until WSL support has been added. I haven't checked what the current state is though.
