### ISSUE TITLE
Shader reuse over multiple models

### ISSUE THREAD

**Issue by mgarcia-org** [floooh/sokol#38]
Nice API!

I would like to set up soko with one shader setup and render multiple models(verts/index date) with the same format.
I've probably missed something really obvious, but I can't see a way to do this?
I see SG_MAX_SHADERSTAGE_BUFFERS is set to 4 and streaming data via sg_update_buffer is also limited to "... only one update allowed per frame and resource object, and data must be written from the start (but the data size can be smaller than the resource size)."

Any help would be great :)
Cheers
Mike.

**Comment by floooh** [comment]
Hi, the most efficient way is when all geometries have the same vertex format, and the total number of vertices is less then 64k. In this case:
- prepare a memory chunk which contains the geometry data for all vertices, create one immutable vertex buffer from this
- prepare a memory chunk which contains the indices for all geometries, 'rebased' to the vertices in the one big vertex data chunk, create one immutable index buffer from this, also you need to keep track of the index range for each geometry (this will be the base_element and num_elements)
- create one shader and one pipeline object with matching vertex format
- prepare one draw_state struct with the pipeline object, vertex buffer and index buffer, this will not change during the draw loop
- the draw loop would look like this:
```c
    sg_begin_default_pass(...);
    sg_apply_draw_state(draw_state);
    for (int i = 0; i < num_models; i++) {
         //...compute model-view-projection matrix here...
         sg_apply_uniform_block(...);
         // now the important part, issue a draw call with the right index range
         // for the sub-geometry:
         sg_draw(models[i].base_element, models[i].num_elements, 1);
    }
    sg_end_pass();
    sg_commit();
```

If your geometry needs to live in different buffers, but still have the same vertex format, you can still use a single pipeline object, but move the sg_apply_draw_state() call into the loop which renders each model, because the vertex- and index-buffer binding must be updated, e.g.:

```c
    sg_begin_default_pass(...);
    for (int i = 0; i < num_models; i++) {
         // need to update the buffer bindings:
         draw_state.vertex_buffers[0] = models[i].vertex_buffer;
         draw_state.index_buffer = models[i].index_buffer;
         sg_apply_draw_state(draw_state);
         //...compute model-view-projection matrix here...
         sg_apply_uniform_block(...);
         // now the important part, issue a draw call with the right index range
         // for the sub-geometry:
         sg_draw(models[i].base_element, models[i].num_elements, 1);
    }
    sg_end_pass();
    sg_commit();
```

Now finally, if your models have different vertex formats, but you will need one pipeline and shader per vertex format, and also need to update the pipeline object binding, this is the most expensive option (so it makes sense to order draw operations to minimize pipeline binding updates:
```c
    sg_begin_default_pass(...);
    for (int i = 0; i < num_models; i++) {
         // need to update the pipeline and buffer bindings:
         draw_state.pipeline = models[i].pipeline;
         draw_state.vertex_buffers[0] = models[i].vertex_buffer;
         draw_state.index_buffer = models[i].index_buffer;
         sg_apply_draw_state(draw_state);
         //...compute model-view-projection matrix here...
         sg_apply_uniform_block(...);
         // now the important part, issue a draw call with the right index range
         // for the sub-geometry:
         sg_draw(models[i].base_element, models[i].num_elements, 1);
    }
    sg_end_pass();
    sg_commit();
```

The multiple vertex buffer slots in sg_draw_state are used for streaming vertex data from different input buffers for the same draw call, this is for instance used for hardware-instanced rendering.

And finally sg_update_buffer() is used for updating buffer content dynamically, this is a fairly expensive operation and is usually used for procedurally generated geometry.

You can also have a look at the Oryol samples, these are written in C++ and have a slightly higher level Gfx API, but the ideas are the same (once I'm crawling out of the emulator-coding-rabbit-hole I'm currently in I will continue moving the Oryol Gfx module to sokol_gfx). For instance this sample renders multiple shapes from the same vertex/index buffer (like in the first example): http://floooh.github.io/oryol/asmjs/Shapes.html (follow the "Source" link for the source code).

Hope this helps :)

**Comment by floooh** [comment]
PS: once I have this implemented: https://github.com/floooh/sokol/issues/37, there will be another option which would live between example (1) and (2) (you'll have more options to pack multiple geometries into vertex- and index-buffers, it's slightly less expensive then rebinding new buffers, but you don't need to 'rebase' indices to the start of the buffer, and you can 16-bit indices even if the total number of vertices in a buffer is greater 64k.

**Comment by mgarcia-org** [comment]
code: 
 Hey man! :)
Cool thanks for the very detailed explanation!
Very much appreciated :+1: 

2nd solution is exactly what I missed, I assumed the pipeline and draw state were tightly coupled.
I see how you update the buff/ind ID's, cool thanks for the info!

2 questions regarding the design of sg_draw_state struct, is there a reason why the "num_elements" isn't also stored? Maybe either use it as a var to sg_draw or it can use the correct num_elements using the index param, it would make it cleaner IMO.

And, why is the vertex_buffers (ID's) limited to just 4, is it an arbitrary number or a graphic limitation? (SG_MAX_SHADERSTAGE_BUFFERS)

A dynamic vertex_buffers would be ideal for me to do some rudimentary, server side animation.. and keep it all in sokol :dagger: 

I know I can do it as is, but just putting it out there.
I see your C64 tweets.. it's very impressive!
Thanks again!

Cheers
Mike.

**Comment by floooh** [comment]
> 2 questions regarding the design of sg_draw_state struct, is there a reason why the "num_elements" isn't also stored? Maybe either use it as a var to sg_draw or it can use the correct num_elements using the index param, it would make it cleaner IMO.

That's because you can reuse the same sg_apply_draw_state() for multiple draw calls. In all 3D APIs, base_element and num_elements is part of the draw call function and very 'light weight', while the sg_apply_draw_state() function may be quite heavy (depending on what members have changed)...

In other 3D API wrappers I wrote in the past, I stored such 'submesh ranges' or 'material groups' in low-level mesh objects (which also contained the vertex- and index-buffers), but this limited the flexibility of the API, so sokol_gfx is now at the same abstraction level as D3D, GL or Metal in order to not put too many restrictions on what can be done with it.

The SG_MAX_SHADERSTAGE_BUFFERS is currently an arbitrary limitation, the underlying 3D APIs also have restrictions for this, but more like 16 or 32 (in D3D11 it's 32, in GLES2 it's most likely 8 or 16). The number of 4 has been choosen to keep the size of the sg_draw_state structure somewhat small but still useful for most scenarios. In a later sokol_gfx version those values might be configurable from the outside through defines.

**Comment by mgarcia-org** [comment]
Ha cool!
Thanks, makes sense!

`In a later sokol_gfx version those values might be configurable from the outside through defines.`
Maybe also doing something like this would be a good compromise?

```

typedef struct {
    uint32_t _start_canary;
    sg_pipeline pipeline;
    sg_buffer vertex_buffers[SG_MAX_SHADERSTAGE_BUFFERS];
    sg_buffer index_buffer;
    sg_image vs_images[SG_MAX_SHADERSTAGE_IMAGES];
    sg_image fs_images[SG_MAX_SHADERSTAGE_IMAGES];

#ifdef CUSTOM_DRAW_STATE_FIELDS
    CUSTOM_DRAW_STATE_FIELDS
#endif

    uint32_t _end_canary;
} sg_draw_state;

```

**Comment by floooh** [comment]
Hmm but for CUSTOM_DRAW_STATE_FIELDS you'd also need code somewhere inside sokol_gfx to handle those extra fields. In this case it would probably make more sense to have some sort of feature toggle define, or if this gets to messy, create a fork.

**Comment by mgarcia-org** [comment]
oh no no no, not to use inside of sokol, but to keep the data in sokol and use it with standard soko calls, ie sg_draw, ie:
Instead of having to have eternal data with sokol:
sg_draw(0, models[i].num_elements, 1);  //as per your example above

No external data storing is required:
sg_draw(0,  draw_state.MyCust_numElements, 1);

IMO, a cleaner interface, a poor man's encapsulation if you will ;) 
It's no big deal tho, if you see it of value then cool, if not, that's cool too.
I'm happy to use sokol, as per your design.. I'm a graphic's noob after all.
Mike.

**Comment by floooh** [comment]
hmm, I think its better to embed sg_draw_state inside your own struct instead (for instance as part of a model's material description, e.g.:

```c
typedef struct {
    sg_draw_state draw_state;
    int base_element;
    int num_elements;
    my_vertex_shader_uniforms vsu;
    my_fragment_shader_uniforms fsu;
    ...
} my_model_material;
```

**Comment by mgarcia-org** [comment]
Oh I see, that makes more sense :D 
I will check out your Oryol samples!
Thanks tips!
