### ISSUE TITLE
sokol_gfx.h cant grow / shrink image_content properly

### ISSUE THREAD

**Issue by Skytrias** [floooh/sokol#385]
hey first time here, im trying to resize an image in my program and it wont quite work. 

essentially: 
* repeat calling `sg_make_image({..})` on `fs_images[0]` causes assertion at some point, but is the only way to affect `width / height` growth of the image (afaik)
* `sg_update_image(...)` needs the image content to be the same `.size`

so i tested this stuff out in the texcube example so its testable. didnt want to spend too much time on it so i only got it barely working on d3d11.

[texcube-image-resize.zip](https://github.com/floooh/sokol/files/5257560/texcube-image-resize.zip)

**Comment by Skytrias** [comment]
reenable certain comments to test out the two states that wont work, for the update_image example i had to make the image dynamic and init the content later!

**Comment by floooh** [comment]
Without looking at the code (I will have a closer look tomorrow), are you destroying the old image? Otherwise you will eventually run out of image handles. 

This code from the plmpeg_sapp sample probably comes closest, this re-creates an image when the required size changes (in plane->width and plane->height), and then copies new data into it:

https://github.com/floooh/sokol-samples/blob/8e212c995770e83aa6f9b84013236442367edeaa/sapp/plmpeg-sapp.c#L264-L297

**Comment by floooh** [comment]
Yeah in the example code you attached you are creating new images but don't destroy old ones. This means you're leaking a lot of memory, and after 128 images or so creation of new images will fail because the image pool is exhausted.

The fix for this is to put a:
```
sg_destroy_image(bind.fs_images[0]);
```
...before the sg_make_image() call.

The behaviour of sg_update_image() is as expected. The image usage hint must be DYNAMIC or STREAM (not IMMUTABLE which is the default), and if you're trying to write more data into the image than will fit, the function will fail.

(e.g. you can't write 5*4 pixels worth of data into a 4x3 image)

As I wrote above, you can probably get rid of the separate call to sg_update_image() when the new font data is available at the time you need to re-create the image.

**Comment by floooh** [comment]
...and some similar code in my emulator framebuffer rendering code:

Recreate textures if their required size changes before copying new data (of the new size) into one of the textures:

https://github.com/floooh/chips-test/blob/ce3000d74061ccb99d4866d189d7e888fe662adf/examples/common/gfx.h#L235-L248

...and here's the actual function which creates the size-dependent resources:

https://github.com/floooh/chips-test/blob/ce3000d74061ccb99d4866d189d7e888fe662adf/examples/common/gfx.h#L89-L122

**Comment by Skytrias** [comment]
okay nice that fixed my bug 👍 
thought the image lived on the gpu but yea should probably never forget that, think i can close this!

**Comment by Skytrias** [comment]
now that i think about it i havent seen sg.destroy_* in most examples yet

**Comment by floooh** [comment]
> now that i think about it i havent seen sg.destroy_* in most examples yet

Most example code only creates images once at startup and all resources are destroyed in sg_shutdown(), that's why most examples don't explicitly have resource destruction calls.
