### ISSUE TITLE
sokol_app.h - sapp_width() >= 980 when on a web browser on the phone

### ISSUE THREAD

**Issue by OAguinagalde** [floooh/sokol#387]
I have an application which creates an orthogonal projection with the width and height set to that of the window (or canvas) being used. This way if my window is 500x500, I'll draw exactly 500x500 pixels of the image allowing me to have a "pixel perfect" render of the image regardless of the size of the window. Now so far this works great for me both on Windows and the browser.

However, when I open the browser **on the phone** this breaks and my image is slightly deformed.

The problem seems to be that sapp_width reports a width of 980 as a minimum. This can be tested easily with chrome phone navigation emulator, as you can drag and drop the width of the emulated screen. The moment that the screen size gets lower than 980 pixels width, it stays there and the image is deformed. If you make the image width higher than 980, actually it works good. So this brings me to what I think will fix my issue, why is the minimum width reported by sapp_width 980?

I was hoping to get some directions on how to approach this and any other tip on using sokol on the web is appreciated too, thanks!

The application itself can be found here.
<https://oaguinagalde.github.io/cengine/canvas.html>

**Comment by OAguinagalde** [comment]
Aah, I asked too fast. Just learned that this is not a Sokol thing itself, but rather a html thing. If anyone ends up here, this is fixable by adding something like this on the canvas:

```html
<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi" />
```

Not 100% sure what all of them do but it's documented here <https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag>.

Still open to any other tip you might have for web on mobile tho!

**Comment by floooh** [comment]
Nice demos :)

I'm not sure why there's a minimum width reported TBH. The width and height members in sapp_desc are more like hints, on some platforms sokol_app.h cannot guarantee that the resulting framebuffer has this size because on some platforms (e.g. mobile) there's no concept of sizeable windows, and on mobile I have control over the canvas size, but not over the browser window size.

In my emulators I wanted to have at least a fixed aspect ratio to prevent distortions. What I'm doing there is stretch the WebGL canvas over the whole browser window client area:

https://github.com/floooh/chips-test/blob/ce3000d74061ccb99d4866d189d7e888fe662adf/webpage/emsc.html#L13-L30

...and also apply the header-tags that you discovered: 

https://github.com/floooh/chips-test/blob/ce3000d74061ccb99d4866d189d7e888fe662adf/webpage/emsc.html#L5

...the rest I'm doing on the C side via sg_apply_viewport():

https://github.com/floooh/chips-test/blob/ce3000d74061ccb99d4866d189d7e888fe662adf/examples/common/gfx.h#L209-L232

(I opted to anchor the viewport area at the top border to make room for a virtual keyboard on mobile devices, before that fix I had it centered vertically)

**Comment by Maeiky** [comment]
Really nice demo! I'm interested by the ECS part. Is this a closed source?

**Comment by OAguinagalde** [comment]
> Really nice demo! I'm interested by the ECS part. Is this a closed source?

Well my demo is indeed closed source, as in its not anything I would be proud to show hahah but let me know if there is anything specific you would like to know about.

The ECS however is an open source library called FLECS. Really cool stuff, I'd recommend it any day! It's maintainer is also a very nice and active person in his discord :)
