### ISSUE TITLE
Visualize depth buffer

### ISSUE THREAD

**Issue by dbacchet** [floooh/sokol#39]
Hi, thanks for creating sokol, I find very refreshing working with it!
Question:
do you have somewhere a snippet of code or an example on how I can access/visualize the depth buffer?
I naively tried to attach the depth_image to a color attachment but it doesn't seem to work for me.

For example, in the `offscreen-glow.c` sample, if I modify the default draw state like this (around line 242):
```c
    sg_draw_state default_ds = {
        .pipeline = default_pip,
        .vertex_buffers[0] = vbuf,
        .index_buffer = ibuf,
        .fs_images[0] = depth_img // was: "color_img"
    };
```
I see no difference in the generated output image.

Similarly, using the `mrt-glfw.c` sample, if I change the debug view in the main loop to also draw the depth, like this (around line345):
```c
        sg_draw(0, 4, 1);
        for (int i = 0; i < 3; i++) {
            sg_apply_viewport(i*100, 0, 100, 100, false);
            dbg_ds.fs_images[0] = offscreen_pass_desc.color_attachments[i].image;
            sg_apply_draw_state(&dbg_ds);
            sg_draw(0, 4, 1);
        }
        for (int i = 3; i < 4; i++) {
            sg_apply_viewport(i*100, 0, 100, 100, false);
            dbg_ds.fs_images[0] = offscreen_pass_desc.depth_stencil_attachment.image;
            sg_apply_draw_state(&dbg_ds);
            sg_draw(0, 4, 1);
        }
        sg_end_pass();
```
what I get is a duplication of the last color attachment that has been bound (see the following screenshot).
<img width="478" alt="screen shot 2018-03-26 at 7 00 37 am" src="https://user-images.githubusercontent.com/10245297/37910927-8fd44320-30c3-11e8-8665-b1a29f7f2eb1.png">

Probably I'm trying to "map" my OpenGL mindset to Sokol, and doing something wrong.
Any suggestion on the right way to use the depth buffer in a shader?

thanks!

**Comment by floooh** [comment]
Using a depth image object as texture won't work unfortunately (and it should warn about this in the validation layer, looks like I forgot a check).

The reason (at for GL) is that a sokol image with depth-pixelformat is created as a glRenderBuffer object (see here: https://github.com/floooh/sokol/blob/ce6414d9eb24d7462fca0365aeb30916b8f33b53/sokol_gfx.h#L2738)

IFIR the reason for this was various compatibility problems with GLES2 platforms (unextended GLES2 and WebGL doesn't have depth textures)/

If you need the depth texture visualization only for debugging purposes I'd recommend using a 3D API debugger like RenderDoc. If you need the depth content otherwise one solution would be to render the depth into a image texture from the pixel shader (but if you need to run on lowend platforms, also keep in mind that single-channel float32 textures might not be available everywhere, for the shadow map in this demo: http://floooh.github.io/oryol-samples/wasm/BulletPhysicsBasic.html I used the RGBA8 encoding from this blog post: http://aras-p.info/blog/2009/07/30/encoding-floats-to-rgba-the-final/

Cheers,
-Floh.

**Comment by dbacchet** [comment]
thanks for the explanation @floooh!

I will try copying the depth buffer into a texture; that should work for me (only targeting desktop systems).

closing this issue.
