### ISSUE TITLE
can you support window setting functions?

### ISSUE THREAD

**Issue by alittlesail** [floooh/sokol#391]
set_window_size
set_window_position
get_window_position
show_window
hide_window
set_window_icon

**Comment by floooh** [comment]
Only as far as those make sense, e.g. if only desktop platforms are a concern it might make more sense to switch to another library for window management, like SDL or GLFW). The tricky part is usually deciding which of those features are important enough to add to the API if they don't work across all platforms (I want to avoid fragmenting the API too much with features that only work on one platform for instance), e.g. setting the window size and position doesn't make sense on Android, iOS or HTML5. Same with show/hide window.

Support for setting the window icon is planned, but the tricky part there is that this is not entirely programmatical on all platforms. E.g. on Windows I can set the windows/taksbar icon programmatically, but the application icon is an executable resource. On other platforms all icon types may be resources that are embedded in the application bundle, but are not set anywhere through an operating system API call.

I'll close this issue, because it's not "focused" enough.

**Comment by alittlesail** [comment]
Thank you for your patient answer. sokol is a wonderful library. I will not open issue like this. thanks
