### ISSUE TITLE
Image Export

### ISSUE THREAD

**Issue by thennequin** [floooh/sokol#40]
Hi Andre,
I use sokol since few weeks and (for now) I think the only missing feature is the export of image to CPU side.
I don't known if this request is compatible with Metal and GLES API but I think it's Ok for DX11 and OpenGL.
And maybe you don't want to add new feature to your lib?
Anyway, thanks for this awesome little and simple lib.

**Comment by floooh** [comment]
Yes this will be tricky to do across 3D APIs, I think a better option is to allow access to the internal resource structs, so that the 3D objects are accessible.

There's also a few other options as workaround:
- you can inject your own 3D API textures and buffers, so that you have direct access to them in your own code (see the inject samples for instance: https://github.com/floooh/sokol-samples/blob/master/glfw/inject-glfw.c),
- another option is to add your own sokol 'extension functions' outside the header, but inside the implementation source, since in the implementation source file you already have access to all private functions and structures.

**Comment by thennequin** [comment]
Ok thanks for your answer, I think I will do the second option.

**Comment by thennequin** [comment]
First version with OpenGL support only.
https://gist.github.com/thennequin/719ef9c3db55f93ca16e161cc95d71ab
