### ISSUE TITLE
sokol_gfx.h: Render Targets with Different Pixel Format

### ISSUE THREAD

**Issue by MrMilad** [floooh/sokol#402]
I tried to attach two color_attachment with different pixel formats (SG_PIXELFORMAT_RGBA16F and SG_PIXELFORMAT_RGBA8) in the same pass, but i get this error: 
**all pass color attachment images must have the same pixel format**.

Please allow the use of render targets with different pixel formats in the same pass.
According to the documents, this is possible for D3D11 and same for OpenGL:
> Each render target can have a different data format. These render target formats are not required to have identical bit-per-element counts.

**Comment by floooh** [comment]
I'm don't quite remember why I added this restriction, it might have been related to WebGL2 (quickly browsing the spec I can't find the restriction though), or simply because ```sg_pipeline_desc``` only has a single ```color_format``` item. Apart from the pixel format, there's definitely further differences between 3D APIs though, e.g. whether alpha-blending can be set up per attachment or must be the same across all attachments.

This definitely needs a public API braking change and some research and experimentation, so it's not just removing that validation check

**Comment by MrMilad** [comment]
Thanks for the information. So can I comment out that line of code as a quick and dirty way?
`SOKOL_VALIDATE(img->cmn.pixel_format == color_fmt, _SG_VALIDATE_PASSDESC_COLOR_PIXELFORMATS);`
Although I know this is wrong, I have no choice :)

**Comment by floooh** [comment]
> So can I comment out that line of code as a quick and dirty way

It might work on GL and D3D11, but definitely not on Metal, because this requires pixel format information in the pipeline state object for each color attachment:

See here: https://developer.apple.com/documentation/metal/mtlrenderpipelinedescriptor?language=objc

...and search for MTLRenderPipelineColorAttachmentDescriptorArray. in the current sg_make_pipeline() implementation this array has identical entries for each attachment:

https://github.com/floooh/sokol/blob/cb50040aab19ef299117742f983bb2f99283ef46/sokol_gfx.h#L9827-L9838

**Comment by floooh** [comment]
This is now possible with the latest API update.
