### ISSUE TITLE
Questions about using sokol_gfx in my hobby project

### ISSUE THREAD

**Issue by oviano** [floooh/sokol#403]
I'm a fan of these single header libraries and I like the look of this wrapper.

My application is a video playback application and right now I use bgfx for the rendering with my own application windowing/events system.

I don't mind bgfx but it of course drags in bimg and bx, and also I had to make some modifications to the code to make it work with my application and occasionally these cause problems when I merge back in bgfx main code. The main mod I made was to be able to pass in a native texture to the updateTexture2D function so that when I hardware decode video I can make bgfx use the native texture directly. In the case of D3D11 this also allows me to override the texture with a SRV which is needed for the Y/UV shading. For Apple platforms I can pass in the metal texture, for Android an OES texture.

Another mod was made by someone else to make bgfx support OES_EGL_image_external, which allowed me to use native mediacodec video decoded textures with bgfx, but then this addition was removed from master, so again, every time I merge I have to make sure this still works.

So while my current implementation with bgfx works well, I'd love to be able to just drop in something like sokol_gfx and have less code to have to worry about when I merge the latest.

The obvious drawbacks I can see with sokol_gfx seem to be (from what I can tell):

- it expects all the calls to be made from the device thread. With bgfx I have an update thread which I use to do all my drawing etc, and then the device thread only does the execution of the commands. Since I have structured my application code around this, I would think I'd need to add a layer ontop of sokol_gfx to queue commands right? I am attracted to the slim layer that sokol offers, and so maybe adding some code to deal with the threading is not really the end of the World.

- someone ported nanovg to bgfx and I use this heavily in my application for the UI. So I would need to port nanovg to sokol, as I don't think anyone has done this from what I can tell? I wonder how much that would involve. Alternatively, are there any other 2d vector libraries of a similar nature to nanovg that have been ported to sokol?

Anyway, just curious as to whether others have trodden this path before, and encountered any of the same Qs!

**Comment by floooh** [comment]
>  I would think I'd need to add a layer ontop of sokol_gfx to queue commands right

Yes, but this shouldn't be much work because there are not many different commands to handle. I use a similar record/replay system in some utility headers (for instance sokol_gl.h and sokol_debugtext.h, also not for doing the recording in another thread, but instead for allowing to record draw operations "anywhere" in a frame outside the sokol-gfx render passes.

For instance here's the playback function for sokol_gl.h: 

https://github.com/floooh/sokol/blob/cb50040aab19ef299117742f983bb2f99283ef46/util/sokol_gl.h#L3223-L3278

I've actually been thinking about a generic ```sokol_cmdlist.h``` header a couple of time, which would offer a similar API as sokol-gfx but act as a record/replay layer. The tricky part there is handling big data blobs for resource creation and updating. This is where I think a specialized record/replay layer might be better optimizable for memory-usage.

> (nanovg) as I don't think anyone has done this from what I can tell

Not that I know of. I tinkered a bit with NanoVG (and Oryol) back in 2014, but I just looked up the code in the history and this didn't actually route rendering calls through the Oryol renderer, but instead called GL directly, so that code isn't very helpful.

There's a fontstash backend though (https://github.com/floooh/sokol/blob/master/util/sokol_fontstash.h), since NanoVG also uses fontstash this might be a good starting point.

And even though it's not very helpful, here's all the stuff I've been digging up about my old NanoVG experiments:

- the Oryol module (but as I said, this just uses NanoVG's original GL backend): https://github.com/floooh/oryol/tree/0a4c06839eb9fb1843aa5881ea5ed352bf8775dc/code/Modules/NanoVG
- some random notes (mainly useful for emscripten/HTML5 though, so also not very useful): https://gist.github.com/floooh/06e010e95271e9271afe
- ...and this old tweet: https://twitter.com/FlohOfWoe/status/505450260240814080

**Comment by oviano** [comment]
Thanks for the feedback and hints, much appreciated. I hadn't really considered whether ImDrawList might be sufficient for the VG side of things. I think though that I would also need to use a modified version of the sokol imgui impl that would also use a command list method.

Well, anyway, I'm going to have a mess about and see where I get.

**Comment by Maeiky** [comment]
I'm also interested in a NavoVG / vector implementation, and this could lead to an implementation of [Rive](https://beta.rive.app/) runtime
