### ISSUE TITLE
sokol_app.h: user resource / data path api proposal 

### ISSUE THREAD

**Issue by slmjkdbtl** [floooh/sokol#405]
Hi! I'm thinking about adding functions to get the resource directory (e.g. MacOS / iOS `*.app/Contents/Resources`, binary path for others) and the preference / data directory in `sokol_app.h`, just want to know if you're down for it
```c
sapp_get_res_dir();
sapp_get_data_dir(const char *org, const char *name);
```

**Comment by floooh** [comment]
It depends on how much this code is dependent on internal data that's only available in sokol_app.h, e.g. if those functions can also be implemented without having to access internal sokol_app.h data I'd rather have them outside of the header (maybe in a separate filesystem helper header).

For instance, the swapchain, clipboard and drag'n'drop are examples of features that are closely tied to the window system code, and implementing them outside of sokol_app.h would either mean duplicating a lot of code, or exposing platform-specific data from sokol_app.h. If this wouldn't be the case, I would have put those features into a separate header.

An example for a feature that will definitely go into an external header is touch gesture recognition, because it can be built completely on the lower-level touch events that are exposed by sokol_app.h.

Another consideration is whether the feature makes sense a "meaty" subset of supported platforms, however there's already a lot of "wiggle room" for this (e.g. there are quite a few functions which only make sense on a single platform, e.g. those that start with sapp_win32_* etc...

If (taking all those considerations into account) we decide to put those functions into sokol_app.h, I would probably turn them into platform-specific functions (e.g. sapp_android_*(), or even sapp_ios_android_*(), because on desktop platforms and HTML5 there are no standard directories for this, and "inventing" a filesystem location for those wouldn't make sense either IMHO.

Do you already have some code around to have a look?

**Comment by slmjkdbtl** [comment]
Thanks for the reply. 

For the predefined OS paths, they won't rely on any sapp state or functionality so yes I totally agree it should be in a separate lib. But I'm not so sure about the resource path function since the main purpose is unify the experience of a windowed application accessing resource files between MacOS (and iOS maybe I haven't tried) and other platform, it wouldn't make much sense for a non-windowed application so I think `sokol_app.h` might be a good place to put it.

Code-wise I currently only have a routine that gets the resource path on MacOS, which relies on `Foundation.h`. For pre-defined OS paths I'm thinking of looking at [xdg-rs/dirs](https://github.com/xdg-rs/dirs) or SDL for reference.

**Comment by floooh** [comment]
> unify the experience of a windowed application accessing resource files 

Ah ok, this is actually a very interesting point... if we can come up with some sort of unified resource access API that would be excellent... but I think that's also big enough to go into a separate header... one interesting problem I have been struggling with how to put it into a header like sokol_app.h is something seemingly simple like defining the application and window icons.

This is extremely different between platforms and involves a lot of "non-C/C++" stuff, like separate resource data files (e.g. *.ico files), meta files (like manifest or *.rc files) and tools (like the resource compiler on Windows)...

Also on Windows, those resource files (icons etc) are not separate files in the file system, but embedded in the executable.

All those differences is why I never got around actually working on this type of stuff, and it is probably better to just "make it easier" with platform-specific helper-functions instead of "solving it completely" und some abstract cross-platform API.

**Comment by slmjkdbtl** [comment]
For stuff like icons the only "cross-platform" solution I can think of is to make a command line tool for packaging freshly compiled windowed application binaries into platform-specific executables, like generate a `.app` bundle for macOS, or a resource / icon embedded windows `.exe`, it's actually not a bad idea in my opinion ([amulet](http://www.amulet.xyz/doc/#exporting) ([code](https://github.com/ianmaclarty/amulet/blob/master/src/am_export.cpp)) has a similar tool built-in that's very pleasing to use).

I'm not sure the "resource path" we were referring to is the same thing tho, I meant something like [SDL_GetBasePath()](https://wiki.libsdl.org/SDL_GetBasePath) where the application access external images, audio or shader files, in my experience it's mostly needed on macOS when you're running your application inside an `.app` bundle and need to access your files under `.app/Contents/Resources` folder, on other platforms `SDL_GetBasePath()` would resolve to the currently running binary path.

**Comment by floooh** [comment]
I'm closing this as "won't fix" (to not increase the sokol_app.h scope).

For the sokol-samples I have fixed the resource path issue with some helper code (see the fileutil* files):

https://github.com/floooh/sokol-samples/tree/33c8b501d6d3f48690abd096b4cf4381a4210920/libs/util
