### ISSUE TITLE
Any reason why sokol_gfx.h can't  #include <GLES2/gl2.h> when SOKOL_IMPL and SOKOL_GLES2 defined?

### ISSUE THREAD

**Issue by oviano** [floooh/sokol#416]
In my arrangement, the SOKOL_IMPL definition, and include for sokol_gfx.h is done in a CPP file which is not in the same place as where the Window, device, context etc are set up. Instead this in a platform-independent rendering class that uses sokol but queues commands for multi-threaded rendering. Since this class also does the setup() and shutdown() calls of sokol (but using a sg_desc that is passed to it from somewhere else), it makes logical sense for the IMPL to be here too.

Also, the definition for the sokol backend is a project level definition, to avoid having to do it in more than one place otherwise (such as before including sokol_imgui.h).

This all works fine on all platforms except on Android; in this case because I am not including GLES2/gl2.h before including sokol_gfx.h when doing the IMPL, it cannot find definitions for a few basic things like GLenum, GLuint.

I noticed that on for example Windows, it includes d3d11.h, on Apple platforms it imports Metal.h, etc. so maybe this is just an oversight and could be added (happy to make a PR, it's a one-line addition)?

**Comment by floooh** [comment]
This is because on some platforms (looking at you Windows) there are no uptodate GL headers provided by any "standard SDK", so the user needs to use a custom GL loader library (like flextGL or GLEW) to provide the GL API declarations. Because of this mess sokol_gfx.h depends on that a GL header has already been included by the user (if used together with sokol_app.h, than sokol_app.h will take care of this though, as a "convenience").

I'm rolling around a better solution in the back of my head for quite a while now, basically moving the required parts of the Windows GL header from sokol_app.h into sokol_gfx.h, and on other platforms include the system headers) - but don't hold your breath ;)

**Comment by floooh** [comment]
Note, this will be fixed with this PR: https://github.com/floooh/sokol/pull/495
