### ISSUE TITLE
Crash on macOS external monitor.

### ISSUE THREAD

**Issue by PhilCK** [floooh/sokol#419]
So running the demo app will crash on macOS with an external monitor. I suspect this is a DPI math issue. I had a look around but this is my first time with these headers so don't really know where to start.

![Screenshot 2020-11-02 at 08 29 14](https://user-images.githubusercontent.com/26706/97846612-28f2f900-1ce6-11eb-9599-c0ba2018b52a.png)

**Comment by PhilCK** [comment]
Yeah DPI issues are a pain, I tried to look at it, but I was time bound this morning. I assumed that DPI should be 2 or somesuch on the 'retina' display, but yeah the time thing.

Just for claification, the crash happens if.

- window spawns on external monitor.
- window is dragged to external monitor (in this case the inital value is fine)

**Comment by floooh** [comment]
No worries. I'll see if I can reproduce this by plugging my 1080p PC monitor to my MBP, I have a lot of other things "in flight" currently though, so it might take a little while until I get around to it.

**Comment by floooh** [comment]
Just taking some notes:

After dragging a 640-pixel-width 'low-dpi' window from a Retina-display to a non-Retina-display, MTKView seems to change the size of its framebuffer to 320-pixels-wide while still reporting a drawableSize of 640. This triggers a Metal assertion when setting the scissor rectangle because the scissor-rect is bigger than the framebuffer size.

Setting MTKView.autoResizeDrawable to false fixes the assertion/crash, but then of course the backing buffer isn't resized automatically.

Potential solution: manually update the drawableSize in windowDidResize event.

**Comment by floooh** [comment]
Ok, I have committed a fix which disables MTKView.autoResizeDrawable and instead explicitly sets the MTKView drawable size during window resize events:

**Comment by floooh** [comment]
PPS: I just noticed a strange effect on macOS 11.0.1: rendering stops when grabbing a window border with the mouse (as if resizing) but not moving the mouse... rendering only happens during actual resizing... at first I thought that's a bug I introduced with the monitor-change fix, but it also happens when rolling sokol_app.h back. So I guess it's a regression in macOS.
