### ISSUE TITLE
_SOKOL_PRIVATE is a reserved identifier

### ISSUE THREAD

**Issue by iboB** [floooh/sokol#434]
In C (and in C++) identifiers which begin with an underscore followed by a capital letter are reserved: https://en.cppreference.com/w/c/language/identifier

Not sure if you care, since many, many libraries break this convention and there doesn't even seem to be a compiler warning in mainstream compilers which identifies macros (certain static code analyzers may complain).

In my libraries, to be on the safe side, I follow the `I_MYLIB...` (as in "internal") pattern.

**Comment by floooh** [comment]
Yep, I'm aware of the rule, but I haven't seen a compiler yet where this is a problem. I think this is just a catch-all thing so that the standard is on the safe side when adding new stuff to the standard headers (basically C's std:: namespace). But since all the sokol-header-symbols are prefix-namespaced too this shouldn't cause any problems even if the C committee suddenly goes crazy and adds a ton of new stuff to the C stdlib ;)
