### ISSUE TITLE
high_dpi bug on mac

### ISSUE THREAD

**Issue by stomanovski** [floooh/sokol#438]
Hi,
Currently I am observing mac-only bug related to retina displays when the app is not running in full screen. When high_dpi is set to true, the framebuffer dimensions are 2x smaller (see the attached screenshot).
The issue seems to be caused by the fact that in applicationDidFinishLaunching
the framebuffer calculations are being applied only in full screen mode.
The fix is trivial - the logic body just has to be moved outside the fullscreen check. Something like this
(I verified that this works on my macbook pro):

@implementation _sapp_macos_app_delegate
- (void)applicationDidFinishLaunching:(NSNotification*)aNotification {
    _SOKOL_UNUSED(aNotification);
    if (_sapp.fullscreen) {
        NSRect screen_rect = NSScreen.mainScreen.frame;
        _sapp.window_width = screen_rect.size.width;
        _sapp.window_height = screen_rect.size.height;
    }
    if (_sapp.desc.high_dpi) {
        _sapp.framebuffer_width = 2 * _sapp.window_width;
        _sapp.framebuffer_height = 2 * _sapp.window_height;
    }
    else {
        _sapp.framebuffer_width = _sapp.window_width;
        _sapp.framebuffer_height = _sapp.window_height;
    }
    _sapp.dpi_scale = (float)_sapp.framebuffer_width / (float) _sapp.window_width;
...

Sorry, probably I should've created PR instead - I just wasn't sure if I have privileges to create branches.

Anyway - thank you for the wonderful library and I hope this might be of some help to you :)

<img width="802" alt="Screen Shot 2020-12-01 at 10 26 31 PM" src="https://user-images.githubusercontent.com/2738021/100836824-db70c580-3424-11eb-8933-78cdc4730110.png">

**Comment by stomanovski** [comment]
I forgot to mention that I was testing with the OpenGL backend. I am not sure if this is affecting Metal. I also verified that this is happening both on Mojave and on Catalina and the fix works in both.

**Comment by floooh** [comment]
Hmm, I can't reproduce the problem on the latest Big Sur 11.1 Beta (20C5048k), setting the high-dpi flag in the cube-sapp sample with the GL backend, returns sapp_width/sapp_height returns 1600x1200, and the whole window is covered. Apple messed around a lot with NSOpenGLView since the Catalina beta, so I'm really not sure what's actually a bug and what is a feature. The 

<img width="349" alt="Screen Shot 2020-12-02 at 12 06 48 PM" src="https://user-images.githubusercontent.com/1699414/100865165-4955d500-3497-11eb-9b8a-5d3d6d1d55fa.png">

<img width="802" alt="Screen Shot 2020-12-02 at 12 07 01 PM" src="https://user-images.githubusercontent.com/1699414/100865312-74d8bf80-3497-11eb-9ccf-8f07bd1d8462.png">

The framebuffer width/height that's computed at the start of didFinishLaunching shouldn't be relevant, whether the NSOpenGLView runs at Retina-Resolution is selected here:

https://github.com/floooh/sokol/blob/f047abc7e144f32654ca7c09b195944132d2fd83/sokol_app.h#L3045-L3050

...and then the actual dimensions are read back here:

https://github.com/floooh/sokol/blob/f047abc7e144f32654ca7c09b195944132d2fd83/sokol_app.h#L2841-L2843

...which in turn is called from the [NSOpenGLView reshape] callback (which is a relatively recent change to fix another NSOpenGLView regression, see the nearby comment:

https://github.com/floooh/sokol/blob/f047abc7e144f32654ca7c09b195944132d2fd83/sokol_app.h#L3191-L3203

...maybe this reshape function isn't actually called after creating the NSOpenGLView on Catalina and Mojave?

**Comment by stomanovski** [comment]
I want to humbly apologize... I dropped the ball - the issue was that I haven't synced up to latest. My sokol_app.h was at least 5 months old. I figured out that something is completely wrong after I couldn't find the reshape function. I have a bit of complicated setup where I am manually picking only particular files from sokol and I am not using the fips build method so my copy of the file was just stale. I can confirm that latest code works fine both on Catalina and Mojave. 
Thanks again and sorry for the wasted time!

**Comment by floooh** [comment]
No problem, I'm glad that it was something simple like this. Having to add different code paths for different OS versions would be much more hassle ;)
