### ISSUE TITLE
(Documentation) sapp/iOS requires linking with Foundation framework

### ISSUE THREAD

**Issue by bryantdrewjones** [floooh/sokol#441]
Can we make an addition to the Sokol App docs for iOS?

https://github.com/floooh/sokol/blob/64a6f2e2fac607ddcd4ccc5bd8bcd25946293550/sokol_app.h#L79

The Foundation framework defines a handful of ObjC-related symbols used by sapp/iOS, like `NSStringFromClass`.

Cheers! ☺️

**Comment by floooh** [comment]
Ok fixed, I didn't notice this so far because I have Foundation hardwired in fips. Not a great idea in hindsight. Strange that macOS doesn't seem to require Foundation though (e.g. in https://github.com/floooh/cimgui-sokol-starterkit I'm using a vanilla CMakeLists.txt file without fips and it works).
