### ISSUE TITLE
Window focus detection

### ISSUE THREAD

**Issue by toyboot4e** [floooh/sokol#444]
Sorry if it's duplicate. I have two questions:

1. Can we listen to Sokol events while a Sokol application doesn't have focus?
2. Can we detect if Sokol application has focus?

Background:

I'm on macOS and using `sokol_app.h` without hijacking the `main` method. While I focus on other window than a Sokol application, I found my app didn't listen to Sokol events. So my input module missed some key released event and worked as if a key were always down.

Thank you!

**Comment by floooh** [comment]
It depends on the event type... on macOS, key down events are only received when the window has the input focus, but key up events for keys that have been pressed are also received when the window has become inactive. That's why your bug description is a bit puzzling. 

Here's how I tested:

- compile and run the events-sapp application on macOS
- press a key and keep it held down
- while keeping the key pressed, click the mouse outside the window so that the window becomes inactive
- release the key, the border of the event panel "KEY_UP" should briefly flash red (meaning a KEY_UP event has been received)

Can you describe the reproduction steps how you ended up with a stuck key? If this can happen it's basically a bug.

As for your second question: currently it's not possible to detect when a window goes in and out of focus, this would require two new event types.

**Comment by toyboot4e** [comment]
Thank you for your 200% answer. I appreciate your help!

> but key up events for keys that have been pressed are also received when the window has become inactive

Yes I tried it just now and got to know what you mean. But **left shift key up event** seem to come when I click outside Sokol application window. Ah, also I'm using Japanese keyboard. It might matter.

I'm using Sokol in Rust so it's a bit hard to provide with reproduction steps, so let me skip it this time.

I would try to provide  more accurate information next time (>_<) Thank you.

**Comment by toyboot4e** [comment]
By the way, thanks for your reply while you're on vacation. Feel free to forget this issue and please enjoy!

**Comment by toyboot4e** [comment]
The title is misleading, so I refined it in #464

**Comment by floooh** [comment]
PS: I have finally added two new events in sokol_app.h to track when the window gains and loses input focus (via the events SAPP_EVENTTYPE_FOCUSED and SAPP_EVENTTYPE_UNFOCUSED). Listening to the UNFOCUSED event should allow to "cancel" any pressed keys, so that they're not stuck when the window becomes focused again. sokol_app.h doesn't do this though, it must be implemented in the event callback function. This probably also allows to workaround the problem described in #464 .
