### ISSUE TITLE
HighDPI on macOS only works correctly for fullscreen

### ISSUE THREAD

**Issue by raegnar** [floooh/sokol#453]
This can be reproduced with the imgui-highdpi-sapp.

HighDPI rendering doesn't seem to work properly unless the app is started in fullscreen mode. It can then be reduced to a window and continue to render correctly.

If the app is started with `fullscreen = false;`
<img width="112" alt="image" src="https://user-images.githubusercontent.com/593220/103677738-85b59e80-4f37-11eb-820d-8f6620ccc139.png">

If the app is started with `fullscreen = true;`
<img width="117" alt="image" src="https://user-images.githubusercontent.com/593220/103677843-aaaa1180-4f37-11eb-9ea2-683262208630.png">

This is on an iMac running macOS 11.0

**Comment by floooh** [comment]
Oops, can confirm, how embarrasing. I'll try a fix, one sec.

**Comment by floooh** [comment]
...could also be related to this change:

https://github.com/floooh/sokol/commit/8d042b5862bda588e3f8bcd264d6acc495e4edeb

...which fixes this crash when moving a window to an external monitor:

https://github.com/floooh/sokol/issues/419

I'm committing a simple fix which looks alright here. It's probably not correct when running on low-dpi monitors though (I guess that rendering will happen at double resolution which would be wasteful, a proper fix would need to request the dpi scaling factor from the screen, but the obvious NSScreen.userSpaceScalingFactor is deprecated (https://developer.apple.com/documentation/appkit/nsscreen/1388375-userspacescalefactor?language=objc), so I'll need to figure out how that's supposed to work now).

**Comment by raegnar** [comment]
I think there is still an issue, when I drag windows around children are not moved properly relative to their parent.
![Jan-08-2021 09-15-03](https://user-images.githubusercontent.com/593220/104044551-4cc53600-5192-11eb-9f91-603fa2040012.gif)

**Comment by floooh** [comment]
I think this is just because the imgui-usercallback demo hasn't been written with highdpi-support in mind. For such "mixed scenarios", all screen coordinates going into sokol-gfx must be multiplied with sapp_dpi_scale(), like here in the sokol_imgui.h header:

https://github.com/floooh/sokol/blob/924f13b8715fed762d8bed9ae3b043e89722c270/util/sokol_imgui.h#L1980-L1984

...the imgui-usercallback demo doesn't do this adjustment when setting viewports and scissor-rects:

https://github.com/floooh/sokol-samples/blob/f773129bde30bc8197934f66979283c17f6bf0c9/sapp/imgui-usercallback-sapp.c#L150-L155
