### ISSUE TITLE
SOKOL_VALIDATE_NON_FATAL getting ignored

### ISSUE THREAD

**Issue by raegnar** [floooh/sokol#454]
Sorry, I'm confused about what is going on here. I had been receiving a 

> `@"sg_apply_bindings: fragment shader image count doesn't match sg_shader_desc\r\n"`

message in debug builds (works in release), and I was trying to track down why that was occurring, when I figured I would just turn on `SOKOL_VALIDATE_NON_FATAL` with a `#define` in my main source file just before the Sokol includes, and yet that doesn't seem to take any effect, I can step through to the same assert inside the `_sg_validate_end` function same as before.

**Comment by floooh** [comment]
Maybe a stupid question, but does your main source file include the sokol-gfx implementation? (e.g. SOKOL_IMPL is defined before the include). The check for SOKOL_VALIDATE_NON_FATAL is in the implementation block, if it defined before including the header as declaration only it won't have any effect.

But TBH, the macro isn't all that useful, you'll most likely hit an assert (so the problem would be fatal nonetheless).

As for this specific error, check that your sg_shader_desc struct has the image types that the shader is expecting, like here:

https://github.com/floooh/sokol-samples/blob/732d4e871ea9124f46e812ed8c2dd1e6823e5284/d3d11/mrt-d3d11.c#L206-L210

(when using sokol-shdc, this information is created from the shader source itself)

...and that your providing the right number of images in the sg_bindings struct:

https://github.com/floooh/sokol-samples/blob/732d4e871ea9124f46e812ed8c2dd1e6823e5284/d3d11/mrt-d3d11.c#L263-L267

One common and non-obvious situation when using sokol-shdc is that your shader code doesn't actually use one of the textures. In that case the texture slot is optimized-out of the shader. To get an idea whether this is the case, use the SLOT_xxx defines which are generated by sokol-shdc when assigning a texture to the sg_bindings struct, if the shader texture slot has been optimized away, this define won't exist and you'll get a compilation error instead of a runtime validation error.

**Comment by raegnar** [comment]
Okay, I also tried `add_compile_definitions(SOKOL_VALIDATE_NON_FATAL)` in the CMakeLists.txt, and that worked. Though you were correct that I would hit a later assert.
> `@"Assertion failed: (Size > 0), function front, file ../ext/sokol/../imgui/imgui.h, line 1618.\r\n"`

This is another works in release issue, and not in debug. It assert on this
> imgui.h:1618 `    inline T&           front()                             { IM_ASSERT(Size > 0); return Data[0]; }`

from
> sokol_imgui.h:1921 `const ImDrawVert* vtx_ptr = &cl->VtxBuffer.front();`

I'm basically trying to use user callbacks in c++ ImGui, and I'm wondering if there is some issue there?
At this point its just a simplified version of the imgui-usercallback-sapp with all the cimgui calls replaced with c++ ImGui:: equivalents.

**Comment by floooh** [comment]
Hmm, this looks like there are ImGui CmdLists without vertices in them, I haven't encountered such a situation yet:

https://github.com/floooh/sokol/blob/a1c1a57d7f572d04192ba23792e8ccc91c21a5b0/util/sokol_imgui.h#L1921-L1935

But I would first check what's wrong with the "fragment shader image count" validation error, fix that first and then continue from there.

**Comment by raegnar** [comment]
I'm going to close this because I think this is my own issue, but I do need to track down the CmdList thing at some point and if I find something worthy of a new issue I will create one.
