### ISSUE TITLE
 D3d11: using Depth texture as SRV ?

### ISSUE THREAD

**Issue by septag** [floooh/sokol#457]
Just to check in with you, It seems like I can't use depth texture as SRV in shaders, can I ?

**Comment by floooh** [comment]
I haven't tried that yet, but it definitely won't be portable. On the GL backend it won't work because a 'depth image' isn't a real texture underneath, but a GL renderbuffer.

On D3D11 it might work unless the sokol-gfx validation layer disallows it, but glancing over the validation error messages I don't think that's covered, so it might be worth a try.

The "recommended" cross-platform way to store and load depth values is by rendering into a regular texture (like in the shadows-sapp sample).

**Comment by septag** [comment]
Ok, I see.
I have tested it on D3d11. It doesn't work. I have modified the d3d11 backend, and noticed that it only works when we create DXGI_FORMAT_R32G8X24_TYPELESS (D24_S8) for depth, add D3D11_BIND_SHADER_RESOURCE to BindFlags and create SRV with DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS  format (currently it doesn't create SRV or sampler object for depth formats). We can get it working.
I suspect we could do the same stuff with GL/metal backends (however, don't think ES2 will work).

So overall, I think this can be a really neat feature. because depth only rendering is very optimized on most cards and you can have less bandwidth/mem/etc... 

I can look into other backends and come up with a PR if you are ok with this

**Comment by floooh** [comment]
Sounds good. If you can test on macOS it would be good if you could also figure out the required changes for Metal.

For GL we will most likely need two different code paths as long as GLES2 needs to be supported. Might make sense to ignore GL for the first version.

Since GLES2 wouldn't work anyway, we should add a new flag to sg_features.

Btw, one related problem I had with reading depth textures in the past is that I often had situations where the same depth surface is needed as depth buffer and as texture in the same rendering pass, for instance in a deferred renderer with a depth-pre-pass, where the depth information is needed in a followup pass which also needs the regular z-buffer. This "double-use" is explicitely disallowed in WebGL, and AFAIK "undefined behaviour" in regular GL. I don't know if this configuration is allowed in D3D by having two resource views. This was another reason why I usually wrote out the depth information separately from the pixel shader instead of using the information in the z-buffer.
