### ISSUE TITLE
LEFT_SHIFT key up event is not caught if the window it not focused

### ISSUE THREAD

**Issue by toyboot4e** [floooh/sokol#464]
This is refined version of #444.

Environment:

* macOS BigSur (11.0.1)
* Japanese QWERTY keyboard

Steps to reproduce:

1. Press left shift key and keep it held down
2. While keeping the key pressed, click the mouse outside the window so that the window becomes inactive
3. Finally release the left shift key, then KEY_UP event doesn't come

It can be tested with for example [cimgui-sokol-starterkit](https://github.com/floooh/cimgui-sokol-starterkit) with a custom `event` function:

```diff
static void event(const sapp_event *ev) {
+    if (ev->type == SAPP_EVENTTYPE_KEY_UP || ev->type == SAPP_EVENTTYPE_KEY_DOWN) {
+        printf("%d\n", ev->type);
+    }
    simgui_handle_event(ev);
}
```

**Comment by floooh** [comment]
You can now check for the SAPP_EVENTTYPE_UNFOCUSED event (happens when the window becomes inactive), and "cancel" any potentially pressed keys. It's not super-convenient, because you need to keep track of pressed keys yourself, but it should fix the problem of keys getting stuck when the window loses input focus.

Closing the ticket.
