### ISSUE TITLE
[Suggestion] Nuklear (Immediate Mode UI) Renderer.

### ISSUE THREAD

**Issue by wmerrifield** [floooh/sokol#471]
Hi, I've been working on this for a couple of days, and I don't know if you would like this as a formal MR or not. It's a renderer/event handler for the [Nuklear](https://github.com/Immediate-Mode-UI/Nuklear/) library (Which seems to meet the Sokol-style -- a single header public domain ANSI C lib)

It's *heavily* based on the existing sokol_imgui.h header, and I've only tested it on Mac and iOS (The only platforms I have).

I've just published them as gists for now, but I could make a more formal MR if you were interested?
* The [sokol_nuklear.h](https://gist.github.com/wmerrifield/965465ab1c3be60b0e022a65cb16fbe7) file itself.
* And a [nuklear-sapp.c](https://gist.github.com/wmerrifield/3500002512d5cc72682c881c064956e3) example file.

**Comment by floooh** [comment]
That looks great. A PR would be much appreciated. Just a small warning: I will merge an API-breaking branch within the next one or two weeks, this will require some minor changes, but those changes are small enough for beind applied "post-PR". It'll be at least a few weeks until I will get around merging new PRs though, because I have some catching up to do after I merge the API-breaking stuff.

**Comment by floooh** [comment]
This has been merged now. Many thanks again!
