### ISSUE TITLE
Q. Ring buffer of vertices?

### ISSUE THREAD

**Issue by toyboot4e** [floooh/sokol#477]
I have a classic quad batcher for 2D rendering. When the vertex buffer is full of quads, I'd like to restart from the beginning of the buffer. Is it possible with `sokol_gfx`?

I looked into `sokol_gl` and it [didn't do it](https://github.com/floooh/sokol/blob/master/util/sokol_gl.h#L2360), so I'm assuming it's impossible. Should I just make a big buffer that won't be saturated?

Thank you :)

**Comment by floooh** [comment]
Yeah, even if it would be possible I would advice against such an updating pattern. It will always be most efficient across all backend APIs to record all "related" vertices for a whole frame into a single buffer update.

sg_append_buffer() allows to interleave buffer updating and rendering calls, *but* the target buffer must still be big enough to hold all vertices for one frame. And unfortunately it was discovered the sg_append_buffer() has "unfixable" performance problems on some GL implementations which cause more or less serious performnace problems (worst case being GLES and WebGL on Android).

If you rewind a buffer mid-frame, I think there's no way around introducing a potential stall where the CPU side needs to wait for the GPU. GL and D3D11 might work around this by internal buffer renaming (so that you're not actually writing to the same memory area), but in Metal you need to be explicit about such things.
