### ISSUE TITLE
Animating gltf2 models

### ISSUE THREAD

**Issue by supercranky** [floooh/sokol#490]
Hello!

First of all - I just love the sokol headers! I'm tinkering with a small game runtime combining sokol with the equally excellent QuickJS javascript engine and it works like a charm!

Now I'm trying to figure out how to support skinned mesh animation with sokol_gfx. The gltf sample is a great start, and I'm guessing I could add the vertex skinning part of the Khronos gltf viewer reference pretty easily but I'm struggling a bit with finding the best approach to do the actual bone animation. Using something like the ozz-animation library could work but seems a bit overkill? 

Surely @floooh or someone have messed with skinned animations in the past? 😀

**Comment by floooh** [comment]
Yeah I did, but actually not yet with sokol-gfx.

TBH I *would* actually use ozz-animation these days, but if you want to do it yourself you can have a look at my Oryol-samples. However the character animation-system and renderer is a bit more complex then usual because it renders characters optionally via and pulls the bone animation data from a texture. It doesn't use GLTF as file format though, but a custom binary format.

Here are the relevant demos:

- https://floooh.github.io/oryol-samples/wasm/OrbViewer.html
- https://floooh.github.io/oryol-samples/wasm/Dragons.html

The skinning shader is here:

- https://github.com/floooh/oryol-samples/blob/master/src/OrbViewer/shaders.glsl

The toplevel C++ code:

- https://github.com/floooh/oryol-samples/blob/master/src/OrbViewer/Main.cc

...and the important part is this character-animation module (this is the main part that would be replaced by ozz-animation):

- https://github.com/floooh/oryol-animation

...oh, and this Dungeon-Crawler demo also seems to have skinned characters:

- https://dealers-dungeon.com/demo/?q=3

...maybe worth looking at the source code:

- https://github.com/bqqbarbhg/spear

Cheers!

**Comment by supercranky** [comment]
Oooh, awesome stuff! Animating instanced characters is really interesting. 

I also noticed raylib recently added support for GLTF animations, I'm going to check that out as well. With all these great resources I'm sure I'll get something working (famous last words 😀 )

Thank you for taking the time to answer this!
