### ISSUE TITLE
Implementing new backends for gfx?

### ISSUE THREAD

**Issue by IngwiePhoenix** [floooh/sokol#493]
Hello!

I am reading across several graphics APIs and learning more about OpenGL, Vulkan and friends - but more specificaly, within the realms of homebrew development on consoles. For instance, [vita2d](https://github.com/xerpi/libvita2d) and [vitaGL](https://github.com/Rinnegatamante/vitaGL) for the Playstation Vita. That should be relatively simple since also TinyGL was ported to it, but I had gotten strong recommendations to use the 2D and 3D libs instead.

Now, if I wanted to implement a new backend for sokol_gfx to implement this, I think it'd be better to implement it as an external file (`sokol_gfx.vita.h`). But, which APIs are the ones that I need to implement? Is there a list of public symbols that are required?

My ultimate goal is to use sokol_gfx as a general abstraction layer for tiny applications that use smaller ifdef blocks to function across a few platforms, so that a bigger bulk of what is needed for an implementation is already taken care of (i.e. only the application business logic remains and the graphics is, mostly, taken care of).

Thank you in advance and kind regards,
Ingwie

**Comment by floooh** [comment]
Have a look at those blog posts:

- https://floooh.github.io/2020/02/17/sokol-gfx-backend-tour-gl.html
- https://floooh.github.io/2020/02/18/sokol-gfx-backend-tour-d3d11.html
- https://floooh.github.io/2020/02/20/sokol-gfx-backend-tour-metal.html

Putting a new backend into an external header my be tricky though, because the platform-specific and platform-agnostic declarations are "interleaved". You may need two headers:

- sokol_[backend]_decls.h
- sokol_[backend]_impl.h

...and include them in the right locations in sokol_gfx.h.

This is all at your own risk though ;) Restructuring sokol_gfx.h for a "bring your own backend" approach would be cleaner but is "out of scope", might be better to fork a new project for this.

**Comment by quetzalsly** [comment]
Any updates on this? for example lets say nintendo switch, it supports vulkan but needs app code, where should devs inject their own code? ofcourse things will get a lot more tricky with things like ps4/ps5 because it needs a different renderer right? I don't suggest any big changes to the code but maybe a small document for people trying to attempt this with step by step instructions to help people get started right away without having to read the entire codebase of sokol? I am just thinking to be future proof there should be some way to extend the code easily because there are new platforms coming out regularly.

**Comment by floooh** [comment]
Those blog posts are still the most useful resource if you want to implement your own backends in sokol_gfx.h. There is no "backend plugin API" or similar. For sokol_app.h it's probably better to not use this at all but instead write your own game loop wrapper (that's basically why sokol_gfx.h and sokol_app.h are separate headers, so that one can be used without the other).
