### ISSUE TITLE
Linker error on MinGW with D3D11 Backend

### ISSUE THREAD

**Issue by legends2k** [floooh/sokol#497]
I've a project using sokol_{app,gfx}.  When building using MinGW on Windows with D3D11 back there's a linker error

```
C:/Apps/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/CMakeFiles/TestExe.dir/main.cpp.obj:D:\Work\TestExe\build2/../third_party/sokol/sokol_app.h:5321: undefined reference to `D3D11CreateDeviceAndSwapChain'
collect2.exe: error: ld returned 1 exit status
```

I know that `sokol_gfx.h` adds `d3d11` for MSVC compilers using `#pragma comment` but it'd be good to document this instead of the currently misleading line in `sokol_app.h`

>     - on Windows: no action needed, libs are defined in-source via pragma-comment-lib

We could add something like

>     - on Windows: kernel32, user32, dxgi, d3d11, dxguid; for MSVC toolchain these are already added

**Comment by legends2k** [comment]
Aside: Great library btw, thanks a ton!

**Comment by floooh** [comment]
Hi thanks for the bug report. Is the missing linker libraries actually the only problem with gcc+mingw on Windows? I had expected that there would be more subtle problems.

So far I had tested with clang on Windows (installed via ```scoop install llvm```) which works fine, however clang's Windows version has more compatibility with the MSVC toolchain and Windows SDK.

I'll try to give gcc+mingw a whirl over the next few days.

**Comment by legends2k** [comment]
> Is the missing linker libraries actually the only problem with gcc+mingw on Windows? I had expected that there would be more subtle problems. I had expected that there would be more subtle problems.

@floooh No, it's actually pretty smooth :)  I was using GLCORE33 back end (with CMake's `target_link_libraries(OpenGL::GL)` without any issues).  I tried switching to D3D11 out of curiosity and found this out.

> I'll try to give gcc+mingw a whirl over the next few days.

Sure, if you face any issues do let me know.  I use the MSYS2 (it comes with `pacman` where I got MinGW).

**Comment by floooh** [comment]
FYI, I started tinkering with MSYS2 / mingw (via ```scoop install msys2``` and I'll try to "improve the situation" over the weekend. One problem I found that should be relatively easy to fix is the platform detection in sokol_app.h (and this has probably also leaked to sokol_gfx.h when I moved the GL loader code over).

This platform detection thinks it's running on Linux and tries to include X11 headers.

Other then that getting the d3d11 samples (https://github.com/floooh/sokol-samples/tree/master/d3d11) to work was no problem (they just require the additional linker libs because the linker pragma is ignored).

**Comment by floooh** [comment]
Ok, I did some fixes to sokol_audio.h, this had a broken platform detection even when compiling with ```-mwin32```, and some other less critical fixes, and I updated the build instructions in various places, for instance:

https://github.com/floooh/sokol/blob/232bb096c615e2d2ce210c14d805956fbf9b6839/sokol_app.h#L71-L74

https://github.com/floooh/sokol/blob/232bb096c615e2d2ce210c14d805956fbf9b6839/sokol_audio.h#L43-L44

...and in the sokol-samples readme:

https://github.com/floooh/sokol-samples#building-manually-on-windows-with-msys2mingw-gcc

I think that's enough for now to close the issue :)

**Comment by pr0g** [comment]
Hi @floooh,

I ran into a very similar issue recently when switching from the OpenGL backend of sokol to DirectX (d3d11).

The problem I hit was the use of `IID_ID3D11Texture2D` as an argument in the third parameter of `IDXGISwapChain_GetBuffer`

```
ID3D11Texture2D* back_buffer = NULL;
IDXGISwapChain_GetBuffer(swap_chain, 0, &IID_ID3D11Texture2D, (LPVOID*)&back_buffer);
```

`sokol_gfx.h` adds `d3d11` and `dxgi` automatically (see below)

```c++
#pragma comment (lib, "dxgi")
#pragma comment (lib, "d3d11")
```

...but is missing `dxguid`. It would be great to also add `dxguid` to be able to use the guids defined in `d3d11.h`. The work around for me was just to add `dxguid.lib` to my CMakeLists.txt `target_link_libraries` command, but it'd be cool if this just happened automatically like `dxgi` and `d3d11`.

I noticed in [this example](https://github.com/floooh/sokol-samples/blob/master/d3d11/d3d11entry.c#L15) you create a variable (`_d3d11entry_IID_ID3D11Texture2D`) for this instead of using the existing one in `d3d11.h`. There may well be a good reason for this but I wanted to check.

Thanks again for creating such a fantastic library and suite of tool. `sokol-shdc` has been a pleasure to use as well as the main sokol_gfx library.

**Comment by floooh** [comment]
Hmm yeah, the reason why those IID variables exists is exactly so that linkage with dxguid isn't needed. I don't quite remember **why** the dxguid requirement was removed (I guess it was exactly because of mingw compatibility).

For instance here in sokol_app.h:

https://github.com/floooh/sokol/blob/956a0d8c996a611979a706a233a0c38e1ea9ae92/sokol_app.h#L6129-L6133

Now I just wonder why this doesn't seem to work...

I also checked my own build system files again (e.g. in the sokol-samples and fips), and I'm not linking dxguid anywhere.

Any ideas what could be different on your build setup which causes it to not 'see' those global variables?

**Comment by pr0g** [comment]
Thanks for getting back to me @floooh.

So I could totally do what you suggest and duplicate the definitions of the IIDs but I thought it would be nice to just use the ones defined in dxguid.lib.

It's definitely not a huge deal and if linking against it breaks MinGW then maybe excluding it is the best option.

The project I'm testing this in can be found here for reference - https://github.com/pr0g/sokol-experiment (it's not using sokol_app, instead I'm using SDL2).

Thanks!
