### ISSUE TITLE
glDrawArraysInstancedANGLE and others undefined when linking on Android

### ISSUE THREAD

**Issue by oviano** [floooh/sokol#518]
Just grabbed latest sokol_gfx.h and noticed that the code using these functions has been enabled.

Unfortunately, on Android, this gives these link errors:

ld: error: undefined symbol: glVertexAttribDivisorANGLE
>>> referenced by sokol_gfx.h:7270 (./thirdparty/sokol_gfx.h:7270)
>>>               renderer.o:(sg_apply_bindings) in archive ../../../builds/ovlibs/ovgfx-android/lib/armeabi-v7a/libovgfx.a

ld: error: undefined symbol: glDrawElementsInstancedANGLE
>>> referenced by sokol_gfx.h:7349 (./thirdparty/sokol_gfx.h:7349)
>>>               renderer.o:(sg_draw) in archive ../../../builds/ovlibs/ovgfx-android/lib/armeabi-v7a/libovgfx.a

ld: error: undefined symbol: glDrawArraysInstancedANGLE
>>> referenced by sokol_gfx.h:7360 (./thirdparty/sokol_gfx.h:7360)
>>>               renderer.o:(sg_draw) in archive ../../../builds/ovlibs/ovgfx-android/lib/armeabi-v7a/libovgfx.a
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build/android-armeabi-v7a/debug/libemu-player.so] Error 1

I'm linking to GLESv2 and EGL, is there something else I am supposed to do?

I'm using:

ANDROID_NDK_ROOT      := /Users/Oliver/Library/Android/sdk/ndk/22.1.7171670
ANDROID_NDK_TOOLCHAIN := $(ANDROID_NDK_ROOT)/toolchains/llvm/prebuilt/darwin-x86_64

**Comment by oviano** [comment]
I guess this is because I wasn't previously including gl2ext.h, whereas now sokol_gfx.h is doing the includes it includes this file, which enables instancing.

So I just need to figure out why this ends up with a link error.

**Comment by oviano** [comment]
It looks like Android needs the equivalent of the _sg_wglGetProcAddress jiggerypokery, but using eglGetProcAddress for these functions.

From what I can tell, you have to check at runtime whether these functions exist.

**Comment by floooh** [comment]
Hmm strange, did this work in your code before I moved the includes from sokol_app.h to sokol_gfx.h?

I might not have noticed the problem in the sokol samples because the combination of Android and GLES2 is not tested there (only Android+GLES3):

https://github.com/floooh/sokol-samples/blob/73af0563ae7e0d5865e1be78d87cbd8f940bb9e6/CMakeLists.txt#L51-L53

...so this problem has most likely slipped through.

Requiring dynamic function pointer lookup would be really strange, normally, if the extension functions are defined in the gl2ext.h header, than the linker should also be able to look up those functions, same as the regular GL functions, but I'm not all that familiar with how GL works on Android, so maybe extension functions are handled differently.

Are you defining ```GL_ANGLE_instanced_arrays``` anywhere?

I'll try to set aside some time to check with GLES2 on my Android phone.

But realistically, the best option might be to disable the instancing functions when on Android GLES2 (needs changes in sokol_gfx.h though), and instead switch to GLES3 (if possible).

**Comment by oviano** [comment]
So it built before because I was not including gl2ext.h when I included sokol_gfx.h so instancing was just not enabled.

Once I uograded to new code, you obviously now include gl2ext.h in sokol_gfx.h, and gl2ext.h in my environment defines angle instancing (I do not defined it anywhere myself). Thus sokol_gfx.h defines those functions but they appear to be missing at the link stage.

I don’t know if it’s significant, but sokol_gfx.h is included as part of a static library, which is then linked to produce the dynamic library that is then used to build the final Android apk/aab. I don’t see why that should matter….

For now I’ve just commented out including gl2ext.h in sokol_gfx.h which gives me the behaviour I had before.

I did a little bit of Googling the other day and it did seem that the solution was to check the extension exists at runtime, and get the pointers dynamically.

For me, I’m not using the functionality anyway, so my workaround is fine.

**Comment by floooh** [comment]
Hmm ok, thanks for the quick answer. I think I would prefer to simply not enable instancing on Android when the GLES2 code path is used. I'll try to tinker around with this once I can see the light at the end of the multiwindow-rabbit-hole I've digged myself into currently ;)

**Comment by floooh** [comment]
This ticket is kinda obsolete now because GLES2 has been removed (along with the DrawInstanced wrapper macros)
