### ISSUE TITLE
sokol/zep/microui/fonstash mashup

### ISSUE THREAD

**Issue by meshula** [floooh/sokol#532]
Not an issue, but thought you might like to see my sokol/zep/microui/fonstash mashup :) It was an interesting exercise in getting general font rendering via bitmaps and fontstash working across a bunch of otherwise unrelated systems.

https://github.com/meshula/LabFont/

**Comment by floooh** [comment]
Nice :) Thanks for the heads-up!

**Comment by floooh** [comment]
Btw: when in C++, ```= { };``` works reliably to set a C struct to zero. The memset is only needed for code which should compile both as C and C++ (because in C it's ```= { 0 };``` and in C++ it's ```= { };```.

For instance here's a recent character-rendering where I can't use the C99 designated init because of C++ where I'm doing the desc struct initialization like this:

https://github.com/floooh/sokol-samples/blob/4d0f58ae8a044c69c44dfb4647af6314ab517ce9/sapp/ozz-skin-sapp.cc#L157-L161

Cheers!

**Comment by meshula** [comment]
Ah, I didn't know that = {}; would zero-initialize in C++, thanks! It's also helpful to see your C++ setup for Sokol, in general. I hadn't noticed that example yet.

**Comment by meshula** [comment]
PS, it's impressive to see 512 instances running at 60hz in Safari! Very nice demo!
