### ISSUE TITLE
Depth SG_IMAGETYPE_CUBE in Metal

### ISSUE THREAD

**Issue by eduardodoria** [floooh/sokol#545]
I'm trying to create point light shadows with samplerCube and worked in OpenGL but not in Metal.

In function `_sg_mtl_create_image`:

```
    /* special case depth-stencil-buffer? */
    if (_sg_is_valid_rendertarget_depth_format(img->cmn.pixel_format)) {
        /* depth-stencil buffer texture must always be a render target */
        SOKOL_ASSERT(img->cmn.render_target);
        SOKOL_ASSERT(img->cmn.type == SG_IMAGETYPE_2D);
        SOKOL_ASSERT(img->cmn.num_mipmaps == 1);
```

Why `SOKOL_ASSERT(img->cmn.type == SG_IMAGETYPE_2D) `?

I commented this line and worked.

**Comment by floooh** [comment]
Hmm, a bit surprising that depth-stencil-cubemaps actually work, they're "supposed" to be 2D textures only. A similar solution for D3D11 wouldn't work though, because this is using a D3D11_TEXTURE2D_DESC, also note that *sampling* a depth texture isn't portable across all backends, that's why the shadow demo here (https://floooh.github.io/sokol-html5/shadows-sapp.html) is rendering depth to an RGBA8 texture:

https://github.com/floooh/sokol-samples/blob/bfb30ea00b5948f2029c7dd228cf30de08b8036c/sapp/shadows-sapp.c#L49-L58

...and then encodes and decodes the depth in the pixel shader to RGBA8:

https://github.com/floooh/sokol-samples/blob/bfb30ea00b5948f2029c7dd228cf30de08b8036c/sapp/shadows-sapp.glsl#L12-L21

IME this is basically the most portable (and on low-end GPUs also fastest) shadow-map-rendering technique.

I'll keep this ticket open, once I'm back from vacation I need to check if the depth-stencil-cubemaps would be portable across all backends, if yes it would make sense to "unlock" the feature.

**Comment by eduardodoria** [comment]
But for `sg_make_pass` you need also a `depth_stencil_attachment`.

Look this sample:
https://github.com/GeertArien/learnopengl-examples/blob/master/src/5-4-point-shadows/2-omnidirectional-shadows.c#L44-L70

It uses SG_IMAGETYPE_CUBE for `depth_stencil_attachment` and `color_attachments[0]`.
I did similar this sample and not work on Metal, but if I comment that line it works. I did not test in D3D11.

**Comment by floooh** [comment]
Cube map depth/stencil attachments should work now via https://github.com/floooh/sokol/pull/834, but it's currently not possible to do anything useful with the rendering result, since depth textures still can't be sampled (I'll try to tackle this again after the WebGPU backend is finalized).
