### ISSUE TITLE
[Question] Rendering  sgl intro a framebuffer - assertion failure

### ISSUE THREAD

**Issue by Hperigo** [floooh/sokol#547]
Hi there, 

I'm working on a small text app and I managed to render sokol_fontstash into a framebuffer, it works well, but I'm getting an assertion error when validating the pipeline when the `sample_count` and `depth format` is different from main default pipeline and pass. 

here's more or less what I'm doing,

1. creating the offscreen image: 

```cpp

sg_image_desc fbo_desc = (sg_image_desc){
        .render_target = true,
        .width = OFFSCREEN_WIDTH,
        .height = OFFSCREEN_HEIGHT,
        
        .pixel_format = SG_PIXELFORMAT_RGBA8,
        .min_filter = SG_FILTER_LINEAR,
        .mag_filter = SG_FILTER_LINEAR,
        .wrap_u = SG_WRAP_REPEAT,
        .wrap_v = SG_WRAP_REPEAT,
        
        .sample_count = OFFSCREEN_SAMPLE_COUNT,
        .label = "color-fbo",
    };

offscreen_state.fbo_color_img = sg_make_image(&fbo_desc);

fbo_desc.pixel_format = SG_PIXELFORMAT_DEPTH_STENCIL;
fbo_desc.label = "depth-image";
sg_image fbo_depth_img = sg_make_image(&fbo_desc);
```

1. creating the pass for the offscreen buffer: 

```cpp
sg_pass_desc desc = (sg_pass_desc){
            .color_attachments[0].image = off_state.fbo_color_img,
            .depth_stencil_attachment.image = fbo_depth_img,
            .label = "offscreen-attach",
        };
offscreen_state.pass = sg_make_pass(&desc);
```

1. Drawing into the FBO

```cpp
sgl_load_pipeline(offscreen_state.pipeline);
sgl_push_pipeline();

sgl_begin()
.... 
sgl_end()
sgl_pop_pipeline();

sg_begin_pass(off_state.pass, off_state.pass_action);
sgl_draw();
sg_end_pass();
sg_commit();
```

1. drawing the FBO image: 

```cpp
sgl_load_pipeline(app_state.sgl_pip); //default pipeline
sgl_push_pipeline();

sgl_pop_pipeline();

sg_begin_default_pass(&app_state.pass_action, width, height);
sgl_draw();
sg_end_pass();
sg_commit();
```

if `OFF_SCREEN_SAMPLE_COUNT` is the same used in `main_pass_action` and the main `sgl_pipeline`, no assertion fails.

if it's not the same, I get this error: 

```cpp
sg_apply_pipeline: pipeline MSAA sample count doesn't match render pass attachment sample count
^^^^  VALIDATION FAILED, TERMINATING ^^^^
Assertion failed: (0), function _sg_validate_end, file fips-workspace/sokol/sokol_gfx.h, line 13690.
```
 
 stepping into the `sgl_draw` function, it looks like the pipeline being applied is the default one and not the offscreen one ( with samples = 4 )

<img width="895" alt="Screen Shot 2021-08-11 at 09 56 29" src="https://user-images.githubusercontent.com/3333460/129032928-07d8c369-2c73-4989-ab6c-447a3ded0744.png">

I'm not sure if I'm doing something wrong, or I'm supposed to use the same settings for the `offscreen_pipeline/pass` and main `pipeline/pass`

**Comment by floooh** [comment]
Hi, the ```sgl_load_pipeline()``` needs to go after the ```sgl_push_pipeline()``` (because push basically creates a new entry on the pipeline stack, and sgl_load_pipeline() loads a pipeline handle on the current top of the pipeline stack).

After that you will run into a more serious problem though: currently you can't call sgl_draw() twice in the same frame, because of the sg_update_buffer() call here:

https://github.com/floooh/sokol/blob/9aa7891121f4495974c54cd12449c04ad9512e4d/util/sokol_gl.h#L3248

So currently you can only draw in a single render pass.

The proper solution for this are ```contexts``` like I'm using the sokol_debugtext.h header, but I didn't get around yet adding context support to sokol_gl.h

**Comment by Hperigo** [comment]
Hey, 

unfortunately swapping `sgl_push_pipeline()` with `sgl_load_pipeline()` didn't fix the assertion error... I still get the same break

here's my offscreen buffer draw code, if it helps clarify anything: 
```
void draw_fbo(){
    const int width = OFFSCREEN_WIDTH;
    const int height = OFFSCREEN_HEIGHT;
    float radius = 100.0f;
   
    sgl_push_pipeline();
    sgl_load_pipeline(off_state.pipeline);
    
    sgl_viewport(0, 0, width, height, true);
    sgl_defaults();
    sgl_matrix_mode_projection();
    sgl_ortho(0, width, height, 0, -1.0, 1.0);
   
    sgl_matrix_mode_modelview();
    int num_of_sides = 32;
    sgl_c3b(255, 30, 50);
    sgl_begin_triangles();
    for(int i = 0; i < num_of_sides; i++){
        float radians = ((float)i / num_of_sides) * 2.0 * M_PI;
        float next_radians = ((float)(i + 1) / num_of_sides) * 2.0 * M_PI; 
        float x =  cos(radians) * radius;
        float y =  sin(radians) * radius;
        float nx = cos(next_radians) * radius;
        float ny = sin(next_radians) * radius;
        sgl_v2f(0.0f, 0.0f);
        sgl_v2f(nx, ny);
        sgl_v2f(x, y);
    }
    sgl_end();
    sgl_pop_pipeline();

    sg_begin_pass(off_state.pass, off_state.pass_action);
    sgl_draw();
    sg_end_pass();
    sg_commit();
}
```

*After that you will run into a more serious problem though: currently you can't call sgl_draw() twice in the same frame* 
Yeah, that's why I ended up calling `sg_commit()` twice ( 1. at the end of the `draw_fbo()` function, 2. at the end of the default pass ) 
*The proper solution for this are contexts like I'm using the sokol_debugtext.h header, but I didn't get around yet adding context support to sokol_gl.h.* 
got it! I was mainly curious to why the pipeline was not being applied, but maybe it's not even worth to take a look at this issue if rendering `sgl_` to an fbo is not supported and the way that I got it to work is a bit hackish

**Comment by floooh** [comment]
> unfortunately swapping sgl_push_pipeline() with sgl_load_pipeline() didn't fix the assertion error... I

Oops, yes you're right. It's because I'm patching in the default framebuffer attributes into the pipeline desc here:

https://github.com/floooh/sokol/blob/abadc11723c860ac17a325b7e272c30696710e38/util/sokol_gl.h#L2257-L2265

> Yeah, that's why I ended up calling sg_commit() twice

Uh oh, that's "unsupported". It probably works by accident because in some backends.

I've started to work on the context support in this branch: 

https://github.com/floooh/sokol/tree/sgl-contexts

With test code and a new sample I should be able to finish this over the weekend. This will provide "proper" support for your use case.

**Comment by floooh** [comment]
Ok, a bit later then intended, because some real-world stuff got in the way, but sokol_gl.h now has context support, see this sample for how to render both into an offscreen pass and the default pass with sokol_gl.h:

https://floooh.github.io/sokol-html5/sgl-context-sapp-ui.html

...and the updated header documentation:

https://github.com/floooh/sokol/blob/master/util/sokol_gl.h

**Comment by Hperigo** [comment]
that's awesome! thank you!

**Comment by Larpon** [comment]
@Hperigo would you mind sharing or explaining how you got sokol_fontstash rendering to an offscreen buffer?

I have difficulties that seem to be similar to what you have achieved here (My problem: https://github.com/floooh/sokol/issues/749) I think it might be the pipeline, which isn't provided in this issue :sweat_smile:
