### ISSUE TITLE
Creating a Precompiled header with clang 

### ISSUE THREAD

**Issue by alighazi** [floooh/sokol#554]
Hi,
Thanks a lot for nice pieces of software :)

I'm trying to generate a Precompiled header with all the sokol headers so I can later include the precompiled header in my program and minimize compile time.
How do I go about creating that?

I tried generating the headers using this command:
`clang -cc1 .\pch.h -emit-pch -o pch.h.pch -O0 -Wall -Wextra -Wfatal-errors -pedantic -D_DEBUG -DSOKOL_D3D11 -I .\sokol -I .\include`
but it failed:

```
In file included from .\pch.h:8:
.\sokol\sokol_app.h:995:10: fatal error: 'stddef.h' file not found
#include <stddef.h> // size_t
```

pch.h contains:
```

#define SOKOL_IMPL
#define SOKOL_NO_DEPRECATED
#if defined(_WIN32)
    #define SOKOL_LOG(s) OutputDebugStringA(s)
#endif
/* this is only needed for the debug-inspection headers */
#define SOKOL_TRACE_HOOKS
#include "sokol_app.h"
#include "sokol_gfx.h"
#include "sokol_glue.h"
#include "sokol_time.h"
#include "sokol_fetch.h"
#include "util/sokol_debugtext.h"

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
#define HANDMADE_MATH_IMPLEMENTATION
#include "HandmadeMath.h"

```

**Comment by floooh** [comment]
Don't know to be honest, I only used precompiled headers in big C++ projects with the Visual Studio compiler (didn't help much with compile speed though).

The error message:

```
.\sokol\sokol_app.h:995:10: fatal error: 'stddef.h' file not found
```

...looks like the compiler invocation doesn't setup the C runtime header search paths, because stddef.h is the first header that's included in most sokol headers.

Also, defining SOKOL_IMPL looks weird to me for a precompiled header, because SOKOL_IMPL is only supposed to be defined once in the entire project, and usually in a .c or .cpp source file. Otherwise you'll get the implementation code included everywhere where you'd include pch.h.

I'd recommend putting the content of your pch.h file into a regular C file and add that to the project, this will then only be compiled once into an .o file. Including the declarations (without the SOKOL_IMPL) should be cheap because it's all just C declarations (enums, structs and function prototypes). IME precompiled headers are only useful if there's a lot of inline or C++ template code in the headers.

This is basically how I do it in (some of) my projects, all the sokol headers are copied into a subdirectory called 'sokol', and there's a sokol.c file which compiles the implementation:

https://github.com/floooh/pacman.c/tree/main/sokol

...and the part in the cmake file which compiles the sokol.c file into a library:

https://github.com/floooh/pacman.c/blob/709a31d728032c0c8cc0bdc5d76f12d83bd97644/CMakeLists.txt#L14-L38

But if you want to use precompiled headers, you should definitely remove all the "IMPL" defines from the pch.h (you'll still need a separate implementation source file though).

**Comment by alighazi** [comment]
Thanks for the explanation. yes I now realized that what I'm looking for is actually the .o files. but why can't I put the SOKOL_IMPL in pch.c file? I checked your sokol.c file and it includes the  SOKOL_IMPL definition.

btw, since I don't use cmake do you know what clang/gcc flags should I use to generate .o and then link it to my program?

**Comment by floooh** [comment]
> but why can't I put the SOKOL_IMPL in pch.c file?

In a pch.**c** file it would work, since that's only compiled once for the entire project, but if it's in the precompiled header itself then the code that's been compiled into the header would be included multiple times into the project which can cause all times of problems. 

There's more info here: https://github.com/nothings/stb/blob/master/docs/stb_howto.txt

This readme snippet has examples of how to compile the sokol samples without cmake (or any other build system), looks for the command line examples with "sokol.c" in them:

https://github.com/floooh/sokol-samples#how-to-build-without-a-build-system

**Comment by alighazi** [comment]
I found the following in your examples:
`clang cube-sapp.c ../libs/sokol/sokol.c -o cube-sapp-d3d11.exe -O2 -DSOKOL_D3D11 -I ../../sokol -I ../libs`
this builds and run fine, but it doesn't generate any .o or .a libs so I think this builds the headers and implementations every time, thus  I'm not sure if there is any build time advantage here.

I however played around and found a formula that works.
I generated the .a file using clang
```
  clang -c $Flags .\clibs.cpp -o .\bin\clibs.o
  llvm-ar -rc .\bin\clibs.a .\bin\clibs.o
```
and linked in simply by
clang $Flags -o .\bin\win.d3d11.exe .\main.cpp .\bin\clibs.a 

so this way you only build the implementations once. I haven't benchamrked to see how much the build time is reduced tho.
