### ISSUE TITLE
bugfix for you in `sokol_imgui.h`

### ISSUE THREAD

**Issue by voidware** [floooh/sokol#558]
`sokol_imgui.h::simgui_render`

change `front` to `begin`

```
       const size_t vtx_size = cl->VtxBuffer.size() * sizeof(ImDrawVert);
            const size_t idx_size = cl->IdxBuffer.size() * sizeof(ImDrawIdx);
            
            //const ImDrawVert* vtx_ptr = &cl->VtxBuffer.front();
            //const ImDrawIdx* idx_ptr = &cl->IdxBuffer.front();

            const ImDrawVert* vtx_ptr = cl->VtxBuffer.begin();
            const ImDrawIdx* idx_ptr = cl->IdxBuffer.begin();
```

**Comment by PathogenDavid** [comment]
Context on this issue: https://github.com/ocornut/imgui/issues/4528

The short version is that `front()` will assert when there are no vertices/indices associated with the command list, which can happen if you add a user callback without adding any widgets.

-----------

Also I think rather than switch to `begin()`, I believe this this preprocessor section can just be eliminated entirely:

https://github.com/floooh/sokol/blob/667df71044ecd19c218c93c5cbdb188c9ed6eeb8/util/sokol_imgui.h#L1927-L1932

The C version of that block is already in line with what the Dear ImGui-provided backends do.

**Comment by floooh** [comment]
Ok fixed in https://github.com/floooh/sokol/commit/cc20a3ba92246b852e1bb3a6734e0561fc733a55, I've removed the C++ block as suggested, and also added a couple ifs for the case that the number of vertices or indices ends up being 0.

Thanks for the bug report!
