### ISSUE TITLE
sg_query_image_info() doesn't initialize upd_frame_index.

### ISSUE THREAD

**Issue by kssreeram** [floooh/sokol#559]
It's a minor thing.
`sg_image_info` has a `upd_frame_index` field that isn't set by `sg_query_image_info()`.

```
SOKOL_API_IMPL sg_image_info sg_query_image_info(sg_image img_id) {
    SOKOL_ASSERT(_sg.valid);
    sg_image_info info;
    memset(&info, 0, sizeof(info));
    const _sg_image_t* img = _sg_lookup_image(&_sg.pools, img_id.id);
    if (img) {
        info.slot.state = img->slot.state;
        info.slot.res_id = img->slot.id;
        info.slot.ctx_id = img->slot.ctx_id;
        #if defined(SOKOL_D3D11)
        info.num_slots = 1;
        info.active_slot = 0;
        #else
        info.num_slots = img->cmn.num_slots;
        info.active_slot = img->cmn.active_slot;
        #endif
        info.width = img->cmn.width;
        info.height = img->cmn.height;
    }
    return info;
}
```

**Comment by floooh** [comment]
Thanks for the bug report!

**Comment by floooh** [comment]
Ok fixed. Eventually I'd like to return more information in the query_info functions, a while ago I restructured the per-resource structs to have a 'common' nested struct (sg_buffer_common_t, sg_image_common_t, etc...), and it would make sense to return all the info in there in query_info functions. 

But on the other hand, most of this information otherwise only needs to be kept around for the validation layer, so in release it's just dead weight (this little conflict is why didn't move ahead with adding more stuff the query_info funcs yet).
