### ISSUE TITLE
[Reminder]: expose Metal's render pass store action in public API?

### ISSUE THREAD

**Issue by septag** [floooh/sokol#563]
Is it possible to do two default passes with `sampleCount > 1` on Metal device ? 

I'm using `SG_ACTION_LOAD` for the second pass, but after the second one, drawable contents gets wiped with purple color. This behavior does not happen with other APIs (d3d11+GL). 

This is for example what I'm doing with sokol-triangle sample (with sampleCount = 4):

```cpp
    action.colors[0].action = SG_ACTION_CLEAR;
    action.colors[0].value = (sg_color) {1.0f, 0, 0, 1.0f};
    sg_begin_default_pass(&action, osx_width(), osx_height());
    sg_apply_pipeline(state.pip);
    sg_apply_bindings(&state.bind);
    sg_draw(0, 3, 1);
    sg_end_pass();

    action.colors[0].action = SG_ACTION_LOAD;
    sg_begin_default_pass(&action, osx_width(), osx_height());
    sg_apply_pipeline(state.pip);
    sg_apply_bindings(&state.bind);
    sg_end_pass();
```

**Comment by floooh** [comment]
Hmm, I wouldn't recommend this with any backend, two default passes in one frame is basically "undefined behaviour", it might work in some situations (or backends) but not in others.

I think the reason why you're seeing a blank surface is the ```MTLStoreActionMultisampleResolve``` here in this line:

https://github.com/floooh/sokol/blob/89b1b6b1b844fd968537e633a3ded7662bb63641/sokol_gfx.h#L10627

You could try to replace this with ```MTLStoreActionStoreAndMultisampleResolve``` and see what happens, but there will be lots of other unexpected problems with two default passes in the same frame (because in the Metal backend each default pass requests a new drawable to render into if I'm not mistaken).

With offscreen passes there's probably fewer problems (but I think the MSAA case still won't work because of the Metal store action that's used). I don't want to always do ```MTLStoreActionStoreAndMultisampleResolve``` because that shouldn't be usually needed, but maybe it makes sense to expose both the load- and store-action in the API (when creating a pass object).

**Comment by septag** [comment]
Ah nice! Thanks for the explanation.

I used your tip (MTLStoreActionMultisampleResolve) and modified here at line 10680 instead of the spot you mentioned (that one was for offscreen rendering):

```cpp
        bool is_msaa = _sg.desc.context.sample_count > 1;
        pass_desc.colorAttachments[0].loadAction = _sg_mtl_load_action(action->colors[0].action);
        pass_desc.colorAttachments[0].storeAction = is_msaa ? MTLStoreActionStoreAndMultisampleResolve :
                                                              MTLStoreActionStore;
```

It is now fixed and behaves like no msaa mode or other backends.
I'm not sure if this is undefined, since I couldn't find anything in the documentation. So I can confirm that it works on the default pass. Regarding the thing you said about having no control over actions, for drawables, you are getting the descriptor (MTLRenderPassDescriptor) from `[MTKView currentRenderPassDescriptor]` so we could change it's behavior like offscreen ones.

And I checked, as far as I understood, you are discarding the drawable in `commit` and not on every pass, so it should be safe.

**Comment by floooh** [comment]
Ah yeah right. I'll keep the ticket open as reminder (and change the title). I think it's better to give the API user more control over the store action, but I need to think about this a bit more.

**Comment by septag** [comment]
Sure thing, thanks for your support.

**Comment by floooh** [comment]
Fixed via: https://github.com/floooh/sokol/pull/834
