### ISSUE TITLE
Retrieve the description of an image

### ISSUE THREAD

**Issue by jojolatina** [floooh/sokol#568]
When we create an image with `sg_make_image`, we pass it a `sg_image_desc` with the width/height and other parameters. As far as I can see, it's not possible to retrieve it. The only thing that we can retrieve is an `sg_image_info` which gives us the width/height but why can't we get back the original desc structure with all the fields? Isn't is useful sometimes to know the other parameters? (maybe I'm dumb and we just don't care, but this seems strange to me)

**Comment by floooh** [comment]
Yep, that's an area where I haven't made up my mind yet :)

Some background: originally, sokol-gfx was going to be a strict "input-only" API, if you wanted to retrive information about resources, you'd have to store them yourself. But this was too 'extreme', so at some point I added the sg_query_*_info() structs with very little information (because at that time, the internal backend data was structured differently and there wasn't much data kept in the 'backend-agnostic' parts.

At some point this was cleaned up, and every resource type now has a backend-agnostic '_sg_*_common_t' struct, for instance:

https://github.com/floooh/sokol/blob/896497ad775153ebe1385c9f95d296860ef53714/sokol_gfx.h#L3008-L3028

After this cleanup it would make sense to return the data in those common-structs.

There are some counter-points though:

- the data in the common-structs is mostly needed in the validation layer, in release-mode where the validation layer is deactived, most of this data us dead-weight and those structs could be a lot smaller (and thus waste less memory in the resource pools)
- returning such big structs by value (just to query one or two items) would also be quite wasteful, but by value is the only option because one of sokol-gfx's 'hard rules' is to not return pointers (even const pointers) to internal data structures
- and finally: it should be a separate sg_*_info struct, not the original sg_*_desc struct, because those desc structs can be (a) quite a bit bigger indeed, and (b) contained "borrowed" pointers to transient external data, at least those references to external data would need to be cleared.

...that's my current thinking... so basically: yes, it's very likely that the query-functions will return more information, but it won't be the original desc-structs :)

**Comment by jojolatina** [comment]
Ok, thanks, it makes sense

**Comment by floooh** [comment]
This is now fixed via https://github.com/floooh/sokol/pull/796
