### ISSUE TITLE
sokol_gl.h: implement point size (and rebuild sokol-zig)

### ISSUE THREAD

**Issue by meshula** [floooh/sokol#579]
When rendering points on an M1 mac, they all come out different sizes. We are submitting via sgl_v2fC3b, but I'm wondering if we should be submitting points in some other way that also indicates the size?

```c
sgl.beginPoints();
sgl.v2fC3b(0, 0, 69, 157, 132);
sgl.end();
```

We'll follow up shortly with a repro.

**Comment by floooh** [comment]
Ping from sokol repository, @mehula, @ssteinbach (I have moved to issue form sokol-zig over here).

**Comment by floooh** [comment]
Lol: https://github.com/floooh/sokol/blob/8fcd271f7d4cb19c77aa9f0bbfe8cb7f319dbffc/util/sokol_gl.h#L70

My current plan is to add a new function:

```
void sgl_point_size(float size);
```
This will work the same as setting the vertex color or texture coordinates (meaning it can be called anywhere, outside begin/end, or also between vertex calls). This costs an extra float in the vertex struct, but I guess that's alright. 

I'll ignore D3D11 for now (meaning the point size there will be hardwired to 1 pixel, so it's not very useful), but I tinkered a bit today with ideas how to emulate point size if the D3D11 backend is active, just to get an idea how much effort it would be.

It'll probably be one or two days until it's ready.

**Comment by ssteinbach** [comment]
Thanks for the quick response!  pinging @meshula too (typo in his username above)

**Comment by floooh** [comment]
Quick question: do you need texturing to work with point lists? Because in that case I'd need to split off the point list shader and handle that as a special case (I also don't know yet if the method of generating texture coords in the pixel shader via gl_PointCoord works via SPIRVCross for the Metal backend).

In that case it's probably better to simulate point-list rendering in sokol_gl.h via instanced triangles (which would also be the solution for the D3D11 backend anyway).

If only coloring is needed I'm nearly done (only some compile fixes for the D3D11 backend, adding a new demo to the sample webpage, and rebuilding the sokol-zig bindings).

<img width="512" alt="Screen Shot 2021-11-18 at 2 14 33 PM" src="https://user-images.githubusercontent.com/1699414/142422114-093c20da-90ca-4cd9-abe1-55ad9205654a.png">

**Comment by floooh** [comment]
Ok sokol-zig has been updated, this is all that has changed in sokol_gl.h ;)

https://github.com/floooh/sokol-zig/commit/83c3e201ef6513e6ed6adbd966a3a55c889e1cc3#diff-249d3911afc2d93957d61f3710d35d98c114b6c1fc2b7240c5feaf2920116b44

I'm going to port the new sgl-points-sapp sample over to Zig now :)

**Comment by meshula** [comment]
Plain old color points is fine! Ultimately using triangles instead of points is probably preferable for portability to D3D, but it doesn't impact our project today, since we're iterating on a mac.

**Comment by floooh** [comment]
Ok, I just committed the points-sample to sokol-zig (still getting used to doing mixed integer/float math code in Zig):

https://github.com/floooh/sokol-zig/blob/master/src/examples/sgl-points.zig

I just noticed though that on my Intel Mac and the current Zig HEAD version the sokol samples crash hard when compiled with ```-Drelease-safe``` or ```-Drelease-fast```, don't know yet what's up with that, it works on my new M1 Mac though (and also on Windows), so I guess it's an Intel and Mac specific ABI issue (there have been several similar issues in the past, especially after updating the LLVM version).

Anyway... I'm going to close the issue and return to emulator coding. If there's anything else popping up, just open a new issue :)

**Comment by meshula** [comment]
Thanks very much! 

Similarly to your crash, we're running into lldb issues with M1/latest zig (inability to launch a zig compiled executable at all), I think if we let Apple and zig churn a little, ultimately these issues will just be temporary.

**Comment by ssteinbach** [comment]
Yes, just wanted to say thanks for the quick response and great library!
