### ISSUE TITLE
sokol_app, OpenGL support on Mac

### ISSUE THREAD

**Issue by pplux** [floooh/sokol#58]
I know, OpenGL is deprecated on mac, but maybe it would be nice to have it until it is removed completely?

**Comment by floooh** [comment]
I actually did have GL support for Mac in sokol_app.h until recently, but currently OpenGL support is indeed broken in the MacOS Mojave SDK (GLFW also is broken when compiled with the Mojave SDK because of this).

If those problems are fixed in later MacOS Mojave Betas I'm going to add GL support back, but until then it doesn't make much sense. On iOS, GLES2/3 is still working via GLKit, and sokol_app.h has support for this (unfortunately, GLKit isn't available on MacOS, and both NSOpenGLView and the more low-level approach GLFW is using is broken).
