### ISSUE TITLE
sokol audio to accept int16 samples ?

### ISSUE THREAD

**Issue by iOrange** [floooh/sokol#585]
Hi,

I'm currently using sokol audio for my video player on Windows, and my decoder outputs all audio samples as int16, so effectively we're wasting time and memory converting from int16 to float, and then sokol audio converts back from float to int16 for WASAPI.

It would be nice to have the ability to use int16 samples directly without double conversion.

PS. If you think this would be useful, I could try to make needed changes and prepare the pull request.

**Comment by floooh** [comment]
I've been thinking about this for a bit. Initially I thought that too much of the sokol_audio.h code is hardwired to float samples, but turns out that the fifo code that sits between the backend- and frontend-code is already 'type-agnostic'.

There's still the problem though that both the frontend and the backend code essentially needs to be duplicated. The public API functions need two versions for int16 vs float samples, and the backends also need to be extended to accept either float or int16 samples.

Not sure if that's really worth the it. I'd rather first investigate if WASAPI can accept float samples so that this one conversion step could be removed at least.

I would still prefer that there's only one generic sample format in sokol_audio.h for most of the code, and if there's any conversion necessary to do this in the frontend code before the data is forwarded to the backends (assuming the saudio_push() model, for the audio callback model, the user code would need to do the conversion).

Finally: maybe miniaudio is a better option for your use case: https://github.com/mackron/miniaudio, the idea with sokol_audio.h is that it is an extremely minimalist audio API, adding more config options would overlap with slightly higher level APIs like miniaudio or SoLoud.

**Comment by iOrange** [comment]
I've modified the Sokol Audio library to use float samples for WASAPI locally and it works like a charm!  Tested on Windows 11, but I guess it should work everywhere  (Sokol already specifies the flag for WASAPI to converts PCM data for the mixer).

The stupid and hacky PR just as an example - #586

**Comment by floooh** [comment]
I haven't looked at the PR yet, but I had a free minute and stumbled over this snippet from https://github.com/floooh/sokol/issues/585, looks like WASAPI is using float samples internally:

An application that uses WASAPI to manage shared-mode streams can rely on the audio engine to perform only limited format conversions. The audio engine can convert between a standard PCM sample size used by the application and the _floating-point samples that the engine uses for its internal processing_. However, the format for an application stream typically must have the same number of channels and the same sample rate as the stream format used by the device.

**Comment by iOrange** [comment]
Yes, read the same, so I guess sokol could switch to float samples for all of it's backends to make things easier.

**Comment by floooh** [comment]
Ok, this is no fixed via https://github.com/floooh/sokol/commit/73e6236d95fbd05063b0182df5b5a33b468b69e1 (which applies https://github.com/floooh/sokol/pull/586 with some minor changes)
