### ISSUE TITLE
Support for Uniform Buffer Objects

### ISSUE THREAD

**Issue by pseregiet** [floooh/sokol#589]
Hi. Are there any plans for support for Uniform Buffer Objects ? I've found this implementation in one of the old issues, but it's out of date with the current sokol_gfx state. I could try to remake this patch for myself, but I'd rather leave that to the professionals. 
https://github.com/floooh/sokol/issues/23#issuecomment-398576297

Any reason why it's not supported already ? I wonder what are my other options for submitting large amount of data to the shader (for example bone matrices for animation).

**Comment by floooh** [comment]
The reasons haven't changed since that thread, bulk-uploading dynamic uniform data via a single glUniform4fv() seems to be the most robust and fastest solution across GL implementations and GL versions.

This is the same method used here (search for "emulated uniform buffers"): https://fortniteintel.com/fortnite-on-android-launch-technical-blog/4430/

Also, GL only guarantees that UBO are at least 16 KBytes big, so they are also not really useful for uploading large amounts of data.

I'd recommend either uploading the data in a dynamic texture, those can be several megabytes, and it's possible to read the data in the vertex shader.

I have used this technique in this ozz-animation sample which renders many indipendently animates characters with a single draw call. The bone data is uploaded in a texture, which is sampled in the vertex shader, and the characters are rendered via hardware instancing (drag the "Num Instances" slider to the right, and open a bone texture visualization by clicking the "toggle joint texture" button):

https://floooh.github.io/sokol-html5/ozz-skin-sapp.html

**Comment by pseregiet** [comment]
I've read that UBOs are faster than data in textures, so that's why I wanted to use them but your example seems plenty fast (and in a browser too) so that's pretty awesome. Thanks for the example code.
