### ISSUE TITLE
Suggestion to undef annoying Windows.h defines

### ISSUE THREAD

**Issue by SanderMertens** [floooh/sokol#608]
Someone made me aware the other day that my code wasn't compiling on Windows because windows.h apparently contains definitions like these (😱):

```c
#define far     /* nothing */
#define near    /* nothing */
```

Because the sokol headers need to be included anywhere I want to do anything rendering related & near/far (I believe NEAR/FAR are defined as well) are common names for graphics apps, it would be nice if sokol could #undef those by default.

`<placeholder for rant on how these things can possibly end up in a header file of a major OS/>`

**Comment by meshula** [comment]
MacOS has a CHECK macro that really messes things up. Not as egregious as near/far and min/max though.

**Comment by floooh** [comment]
Ok yeah, I think undefining near/far makes sense and seems to be the only sensible way (e.g. I guess there's no "NOMINMAX" thing for near/far).

The sokol headers will only pull in platform specific headers in the implementation though, so another workaround would be to place the implementation in its own source file: https://github.com/floooh/sokol-samples/blob/master/libs/sokol/sokol.c, of course that partially undoes the convenience of single-file-libs for simple one-file programs.

I'll try to have a look at the CHECK macro too (another annoying macro (or was it a typedef?) on macOS which I remember from C++ is ```Ptr```).

**Comment by floooh** [comment]
Hmm... unfortunately easier said than done. If I simply undef ```near``` and ```far``` after any Windows platform includes, than any following Windows platform header fails to compile, because those won't include the winmindef.h header again (where near and far is defined) because this is protected by include guards.

Even if I add a block like this:

```c
#ifdef _MINWINDEF_
#define near
#define far 
#endif 
...Windows platform headers here
#ifdef near 
#undef near 
#endif 
#ifdef far 
#undef far 
#endif 
```
...then if any *other* following code includes a Windows header, it would fail :/

The only safe place to undef near and far is where it is guaranteed that no Windows platform headers will be included after...

Hmm...

**Comment by KenthJohan** [comment]
A different approach would be to create a custom windows.h header that only has the necessary declarations and macros.
I believe there must be a tool somewhere that can pull functions declarations and macros automatically by dependencies and generate a new file.
So instead of writing `#include <windows.h>` we could write `#include "custom_windows.h"`

**Comment by SanderMertens** [comment]
> Hmm... unfortunately easier said than done. If I simply undef `near` and `far` after any Windows platform includes, than any following Windows platform header fails to compile, because those won't include the winmindef.h header again (where near and far is defined) because this is protected by include guards.
> 
> Even if I add a block like this:
> 
> ```c
> #ifdef _MINWINDEF_
> #define near
> #define far 
> #endif 
> ...Windows platform headers here
> #ifdef near 
> #undef near 
> #endif 
> #ifdef far 
> #undef far 
> #endif 
> ```
> 
> ...then if any _other_ following code includes a Windows header, it would fail anyway :/
> 
> The only safe place to undef near and far is where it is guaranteed that no Windows platform headers will be included after...
> 
> Hmm...

That's a lot more complicated than I hoped it would be 😕 Probably not worth the hassle if it ends up potentially breaking other code.

**Comment by floooh** [comment]
@KenthJohan yes, a (very long term) plan/idea that's rolling around in my head is to get rid of such platform headers entirely by embedding all required definitions into the headers. I did this in sokol_audio.h for macOS:

https://github.com/floooh/sokol/blob/b2f60754841c0bbfad47da86974e43e494f11bef/sokol_audio.h#L674-L747

...but that only uses a very small "API footprint". This sort of embedding would also simplify cross-compiling a lot.

**Comment by DBJDBJ** [comment]
There is a special graveyard for developers who tried to replace `windows.h`.  Amazing fact is, there are newcomers, after all these decades.
