### ISSUE TITLE
Textures are upside down

### ISSUE THREAD

**Issue by pseregiet** [floooh/sokol#625]
Looking at renderdoc I see all my textures are upside down. It seems like it always was that way, as I had stbi_set_flip_vertically_on_load(true) in my code. Now that I removed it all textures are flipped. I've dumped the buffer memory before calling sg_make_image and the image is right side up in the memory. Is that normal ? Does openGL or sokol expect the images to be fliped vertically ?

**Comment by floooh** [comment]
sokol_gfx.h basically doesn't care what's up and down, it just passes the vertex data as is through to the shader code (so if you need to flip the texture upside down, then your geometry's UV coordinates have been built with that convention).

Now, OpenGL has a different texture coordinate origin than D3D11 and Metal, and that's awfully confusing, because one would excpect that the actual texture data needs to be flipped in GL but not D3D11 and Metal, which isn't the case. Why that's the case is explained here:

https://www.puredevsoftware.com/blog/2018/03/17/texture-coordinates-d3d-vs-opengl/

The only place where the different texture origin matters is when rendering to offscreen render target and then rendering the render target texture to the display. This will result in a flipped image either on OpenGL, or on D3D11/Metal. For that case, the sokol-shdc shader compiler can flip the output Y coordinate upside down via ```@glsl_options flip_vert_y``` (or if GL is 'correct', then ```@hlsl_options/@msl_options flip_vert_y```.

**Comment by pseregiet** [comment]
But I see my textures being upside down in the renderdoc texture viewer. I understand that openGL has 1 at the bottom coordinate and that affects how the UV is interpreted, but the texture dump in renderdoc shows it upside down already.

**Comment by floooh** [comment]
> So I should modify my models (or do it at load time) and flip the UVs ?

I would try to do it offline, either flip the mesh UVs, or the texture. If the texture looks "right side up" in a regular image viewer, than I would probably flip the UV coordinates to avoid confusion.

If the texture looks correct in an image viewer, but upside down in RenderDoc, then that's probably a RenderDoc thing.

**Comment by floooh** [comment]
PS: yeah, seems to be a RenderDoc thing. If I run the loadpng-sapp sample (which the monkey texture) with the D3D11 backend in RenderDoc, the texture is upright (like the original PNG image), but when running through the OpenGL backend, the texture is rendered on its head in the RenderDoc texture view.

**Comment by pseregiet** [comment]
I see. What is interesting is that I'm rendering md5 models from Doom3 which have the textures upside down in the files already. Doom3 was also made on openGL. Despite that, the texture is still upside down in the game if i don't flip the texture or UV. Strange.
