### ISSUE TITLE
[Question] Best practice

### ISSUE THREAD

**Issue by caiiiycuk** [floooh/sokol#630]
Hi. Thank you for great library. I found that using it even without graphics programming background is pretty easy. However I missed some newbie topics. It will be great if someone write docs about typical caveats.

I prepared some question (based on my experience with porting Samogonki from d3d to sokol):

### Texture wrapping/filtering
The game designed in a way where same textures can be applied with  REPEAT or CLAMP wrapping. So I don't have a full list which textures are REPEAT, CLAMP or both. Does it means that I need to call `sg_make_image` for each texture twice? A bit wired because I think that I consuming twice of needed memory. Is there are any workaround? (looks like metal able to change wrapping in shaders)

### New pipelines each frame
I mange to port game to sokol only if I create new pipeline each frame. Game changes following states: CULL (enable/disable), DEPTH (enable/disable), BLEND (enable/disable). Does it mean that I need to create `2*2*2*shader_count(1) = 6` pipelines on start to be effective? So, if I add new state switches then count of pipelines grows even more. How do you manage this is modern projects? Looks like you need to create too much pipelines for all possible cases...

### Base element

Does not understand the differences between buffer offsets and base_element in sg_draw. So this work fine:

```c++
      const auto base_element = command.index_buffer_view.offset; 
      bindings.index_buffer_offset = 0;
      // ...
      sg_draw(base_element, count, 1);
```

and this works fine too:
```c++
      const auto offset = command.index_buffer_view.offset * sizeof(uint32_t); 
      bindings.index_buffer_offset = offset;
      // ...
      sg_draw(0, count, 1);
```

Does offset and base_element do the same thing? When should I use one and when another?

### Update image multiple time

I understand why you want to allow image updates only one per frame. Is it possible to make this rule optional? E.g. I fixed sokol_gfx to disable this rule, because the game actually do updates multiple times. I realize that is better to rewrite game, but first things first. If I understand the disadvantages why I can't just disable this check?

**Comment by floooh** [comment]
> Does it means that I need to call sg_make_image for each texture twice?

Unfortunately yes, this is because GLES2 doesn't have separate sampler state. Once GLES2/WebGL can be dropped sokol_gfx.h will get separate sampler objects.

> Does it mean that I need to create 2*2*2*shader_count(1) = 6 pipelines on start to be effective?

Yes, this is because in some backend APIs those states cannot be separately set, but are part of the pipeline state, or other types of state-group objects. Unfortunately this won't be fixable by dropping older API backends, because this is a propery of the more modern APIs.

> differences between buffer offsets and base_element

The buffer offset is mainly put to group unrelated geometries into the same vertex- and index-buffer objects. It's more useful for the vertex buffer in indexed rendering though because the vertex index 0 points to the first vertex at the vertex buffer offset.

OTH the base element in sg_draw() is useful for rendering different material groups (aka submesh) in the same mesh.

If the base_element is good enough for your use case, then that's definitely preferable though.

> Update image multiple time

...disabling the check might work on some backends, but will completely break on others. On some backends it may appear to work, but introduce a pipeline stall where the CPU needs to wait for the GPU until the underlying resource object isn't used for rendering.

The resource update API is up for a rewrite though which offers more flexibility for copying data from memory into buffers and images, and probably also between resources of the same type. Some of this might also depend on dropping support for older backend APIs though.
