### ISSUE TITLE
IsMenuBarVisible leaks memory on macOS

### ISSUE THREAD

**Issue by Geolm** [floooh/sokol#651]
Hi,

I've created an app on macOS/metal using sokol_gfx, sokol_app, sokol_glue and I noticed that the memory keeps allocating memory. I've checked leaks and it seems to be related to IsMenuBarVisibile. I have no idea if it's because of sokol_app or me, just checking if you have an idea, thanks.

![callstack](https://user-images.githubusercontent.com/17522064/162006105-7d75589d-62ef-4db7-a68a-256f3216a778.png)

![leak](https://user-images.githubusercontent.com/17522064/162006145-3ec989e7-7685-4baf-bd65-0bea23de0152.png)

**Comment by floooh** [comment]
No idea sorry, what I'm seeing in the sokol-samples for macOS + Metal when running in Xcode is that the realtime memory usage graph fluctuates a bit. In the first few dozen seconds it slowly grows (about 100KB every few seconds), then it's stable, and sometimes when moving the mouse it may also go down by 1..2 MBytes.

I never was able to pin down any memory leaks in Instruments though.

How did you conclude that's there's a memory leak btw? The snapshot based leak check in your instruments (with all those green check marks) seems to indicate otherwise? I *did* indeed have some memory leaks when I fixed the ObjC code so that it also works with ARC disable, and the Instruments leak checker did identify all those leaks (e.g. no "green checkmarks").

**Comment by Geolm** [comment]
thanks for your answer and you're probably right, I was looking at some leaks because the memory graph keeps growing the first minutes. So I wrongly looked at allocations even with the green check mark... sorry! The memory graph stops growing after few minutes so I guess it's all good.
