### ISSUE TITLE
does sokol support arrays of textures in shaders?

### ISSUE THREAD

**Issue by meshula** [floooh/sokol#653]
does sokol support arrays of textures in shaders?

Not texture arrays, but arrays of textures? I'm trying to create an array of textures, all different sizes, but can't find a syntax that's compatible with sokol's shdc.

for example, here, in metal is an example of what I mean, with atlasTexture.

```
    fragment half4 render_fragment(
                      FragmentIn in [[stage_in]],
                      constant int& texture_slot [[buffer(1)]],
                      constant float& closest_linear [[buffer(2)]],
                      array<texture2d<half, access::sample>,16> atlasTexture [[texture(0)]])
    {
        constexpr sampler linearSampler(coord::normalized, filter::linear, address::clamp_to_edge);
        half mask_lin = atlasTexture[texture_slot].sample(linearSampler, in.texCoords).r;
        constexpr sampler closestSampler(coord::normalized, filter::nearest, address::clamp_to_edge);
        half mask_closest = atlasTexture[texture_slot].sample(closestSampler, in.texCoords).r;
        half mask = mask_lin * closest_linear + mask_closest * (1.f - closest_linear);
        half4 color = in.color * mask;
        return color;
    }
```

**Comment by meshula** [comment]
What I tried was any number of variations on this ~

```glsl

@module labimm

@vs vs
uniform vs_params {
    mat4 projectionMatrix;
    mat4 textureMatrix;
};

in vec4 position;
in vec2 texcoord0;
in vec4 color0;
out vec4 uv;
out vec4 color;

void main() {
    gl_Position = projectionMatrix * position;
    uv = textureMatrix * vec4(texcoord0, 0.0, 1.0);
    color = color0;
}

@end

@fs fs

uniform fs_params {
    int texture_slot;
};

uniform sampler2D tex0[4];
in vec4 uv;
in vec4 color;
out vec4 fragColor;
void main() {
    fragColor = texture(tex[texture_slot], uv.xy) * color;
}
@end
```

but couldn't work out a way to do it. I'm able to write native glsl that compiles and works in a non-sokol context for GL 4.5 and SPIRV, and native Metal.

**Comment by floooh** [comment]
There's a similar ticket here with a few more details: 

https://github.com/floooh/sokol/issues/530

Unfortunately it's not supported (both because of missing things in sokol-shdc and sokol_gfx.h), even if it's theoretically possible in the current backends with additional work, WebGPU support will then add a new problem because WGSL doesn't support combined image samplers, so I need to do some macro magic in order to make shader with combined image samplers work.

I tinkered around a bit, and I think the only way that currently works (and will work in the future) is separate samplers (e.g. tex0..tex4) and a switch-case to select which texture to sample.

**Comment by meshula** [comment]
Thanks for looking at it. The switch is on a uniform, so that will likely be fine. I can do that in my shader now as a solution that works today. I'll close this one in favor of the earlier issue.
