### ISSUE TITLE
[QUESTION] Picking a la OpenGL

### ISSUE THREAD

**Issue by yzeon** [floooh/sokol#661]
Hi there,

I'm in the process of trying to find a graphics library to replace OpenGL on MacOS. Sokol looks really good.
I was just wondering is there any kind of "picking" mechanism in sokol? OpenGL is quite nice in that it allows you to "pick" arbitrary complex objects, e.g., beziers, relatively easily.

regards,
yzeon

**Comment by floooh** [comment]
What technique did you use for picking with OpenGL, I assume something involving glReadPixels()?

There's no way to read data from the GPU back to the CPU in sokol_gfx.h, mainly because of the tricky GPU/CPU synchronization issues across the 3D backends. Maybe once the GL backend has been dropped completely in favour of WebGPU and Vulkan, the topic can be revisited. Don't hold your breath though ;)

FWIW, in https://floooh.github.io/visualz80remix/ and https://floooh.github.io/visual6502remix/ I'm doing the mouse picking entirely on the CPU via triangle picking (it's completely separate from the rendering).

**Comment by floooh** [comment]
PS: having said that, since sokol_gfx.h is an STB-style header, it's possible to write an "extension headers" with your own features which can directly access the "private parts" of the sokol_gfx.h implementation, e.g. adding a pixel picking function which calls glReadPixels() on GL, or the equivalents in the other backends, you'd be on your own though ;)

**Comment by yzeon** [comment]
Hi,

Thank you for the info! Your examples were quite impressive.

BTW, in my application I was using the GL_SELECT method to do the picking. Now, it's not enough that OpenGL is being deprecated on OSX but that particular selection method seems to be deprecated in OpenGL as well... I was really betting on all the right horses there...

> ... you'd be on your own though ;)

Aren't we always :)

Thanks again. I'll keep looking.

yzeon
