### ISSUE TITLE
Shader flags - best practice?

### ISSUE THREAD

**Issue by mhalber** [floooh/sokol#67]
Hello,

This is not much of an issue, and more of an exploratory question regarding the design of sokol.
sokol allows for specifying 5 uniform types - floats, vec2-4 and mat4.

In my programs I am finding myself to often pass boolean and integer values to my shaders, especially for toggling different flags (show normals, show mesh curvature, etc.). In OpenGL I'd use glUniformxi() family of functions [[ref](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glUniform.xhtml)] to pass these uniforms in. As mentioned above, and inspecting sokol source there don't seem to be an option to do so.

As such I wonder what is the intended best practice here? I see two options:
1) Pass everything as floats and cast in shader as needed?
2) Specify values as integers in uniform block structure, and abuse the fact that sizeof(float)==sizeof(int32_t)?

Both solutions seems a bit dirty to me, making me think that I am missing something obvious.

Thanks so much for all the help!

**Comment by floooh** [comment]
This is mainly an oversight and left-over from the Oryol shader-cross-compiling tool which doesn't support mixing float- and non-float types in the same uniform blocks. In sokol-gfx it should indeed be a bit more flexible, I'll write a ticket for this but until this is fixed I'd recommend to use floats as a workaround:

- for boolean, use magic values, such as 0.0==false and 1.0==true
- for integers (e.g. array indices), I think it's possible to always use floats for this and the shader compiler will 'do the right thing'

The trick you describe in (2) will most likely not work, since in OpenGL, shader uniforms are passed via glUniformxxv() calls, I would count on those functions to pass the values as 'raw bits' without any conversions.

**Comment by floooh** [comment]
tracking ticket: https://github.com/floooh/sokol/issues/68

**Comment by mhalber** [comment]
That answers my question! Thanks! Since you've opened separate ticket, I'll close this issue :)
