### ISSUE TITLE
Use 32-bit vertex indices in ImGui

### ISSUE THREAD

**Issue by timeinpixels** [floooh/sokol#680]
Hi,

Would it be possible to use 32-bit vertex indices in ImGui bindings?

There's this config option in imconfig.h - when I uncomment it, ImGui renderer breaks.
#define ImDrawIdx unsigned int

Would be great if this could be supported in sokol.

**Comment by timeinpixels** [comment]
I have looked into it a bit more and seems sokol supports VTX offset which is a good alternative to 32-bit indices.

**Comment by floooh** [comment]
Yep, it should now be possible to use more than 64k vertices overall in the UI as long as one draw-batch isn't bigger than 64k.
Other then that it's a bit unfortunate that 32-bit indices are a "compile-time setting" in Dear ImGui, otherwise we could just add a "use_32bit_indices" option to simgui_desc_t, and the renderer could switch to 32-bit indices under the hood.
Maybe it would also be possible to autodetect by looking at the ImDrawIdx type, but that seems a bit too much magic to me :)
