### ISSUE TITLE
sokol_gfx : sg_append_would_overflow proposal

### ISSUE THREAD

**Issue by RandyGaul** [floooh/sokol#681]
Would you be interested in a PR for the function `sg_append_would_overflow`? I'm dynamically streaming transient data to the GPU and could definitely do the bookkeeping logic on my end, but it might be a simple and good function to add to sokol_gfx.

```c
SOKOL_API_IMPL bool sg_append_would_overflow(sg_buffer buf_id, size_t size) {
    SOKOL_ASSERT(_sg.valid);
    _sg_buffer_t* buf = _sg_lookup_buffer(&_sg.pools, buf_id.id);
    bool result = false;
    if (buf) {
        int append_pos = buf->cmn.append_pos;
        /* rewind append cursor in a new frame */
        if (buf->cmn.append_frame_index != _sg.frame_index) {
            append_pos = 0;
        }
        if ((append_pos + _sg_roundup((int)size, 4)) > buf->cmn.size) {
            result = true;
        }
    }
    _SG_TRACE_ARGS(append_would_overflow, buf_id, size, result);
    return result;
}
```

I can make a PR if you think this is a good idea. Any thoughts?

**Comment by RandyGaul** [comment]
Also, I do have a question. I'm doing triple buffering, and sometimes all three buffers can fill up with data in a single frame. Do you know of a simple way to block until the buffers are free for usage? It looks like the default behavior is to silently drop further data appends with sg_append_buffer, and assert on `sg_update_buffer`. Though, I'd like to block and wait, even in debug mode.

**Comment by floooh** [comment]
It's a good idea, but going with the sg_query_* pattern for getting information out of the API, and the existing function ```sg_query_buffer_overflow()``` I think a better name would be ```sg_query_will_buffer_overflow(buf, size)```.

I think the function doesn't need a trace hook (all the other query functions also don't have one).

A PR would be welcome :)

As for the triple buffers filling up question, I don't quite understand the scenario, especially the part about "all three buffers filling up in a single frame", shouldn't only one buffer be used per frame? Also be aware that sokol_gfx.h does buffer renaming under the hood anyway (on GL and Metal, but not D3D11, where D3D does this on its own).

I think the best buffer data updating scenario is to write your per-frame updates into your own memory buffer with enough capacity for the worst case, and on the side record vertex ranges which will be needed later for rendering.

Then have a single big sokol-gfx vertex buffer the same "worst case" size as the capacity of your memory buffer. Then once per frame before rendering, call a single sg_update_buffer(), with the size of the valid data in the backing buffer in memory.

Then do the actual render loop with draw calls for the vertex ranges recorded earlier.

This is basically how all util headers work that deal with dynamic vertex data:

- the sokol_gl.h draw loop: https://github.com/floooh/sokol/blob/52e99842d3ec1050a198c4c4f29da4e1816e5ba7/util/sokol_gl.h#L3164-L3220
- the sokol_imgui.h draw function updates both a vertex- and index-buffer, but also just one update each per frame: https://github.com/floooh/sokol/blob/52e99842d3ec1050a198c4c4f29da4e1816e5ba7/util/sokol_imgui.h#L1943-L2084
- the sokol_debugtext.h draw loop isn't really a loop, because it can draw all recorded vertex data in a single draw call, this one uses sg_append_buffer() though, because it's possible to call sdtx_draw() multiple times per frame: https://github.com/floooh/sokol/blob/52e99842d3ec1050a198c4c4f29da4e1816e5ba7/util/sokol_debugtext.h#L4256-L4281

...but the basic idea is always the same: first record a potentially big batch of vertex-data (and possibly index-data) into a memory buffer, and then call the sg_update_buffer() function only once before rendering, or less ideally, sg_append_buffer() (which has known performance issues on some platforms).

Hope this helps :)

**Comment by RandyGaul** [comment]
Great yes that totally helps! Yes my question was confusing as I was a little confused, haha.

I'll get you a PR sometime today. Thanks again for the advice!

**Comment by RandyGaul** [comment]
> Also be aware that sokol_gfx.h does buffer renaming under the hood anyway (on GL and Metal, but not D3D11, where D3D does this on its own).

Oh interesting. I'm doing something like this:

```c
struct buf_t
{
	int stride = 0;
	int buffer_number = 0;
	int offset = 0;
	sg_buffer buffer[3];
};
```

Is this unnecessary? Should I only be using a single `sg_buffer` for certain backends?

**Comment by floooh** [comment]
Yeah that's unnecessary, for the GL and Metal backend, an SG_USAGE_DYNAMIC or SG_USAGE_STREAMING buffer or image is actually multiple GL or Metal buffers/textures under the hood which are rotated through each frame. The number is defined by the SG_NUM_INFLIGHT_FRAMES define (which is 2, but you could probably also experiment with 3).
In D3D11 this isn't necessary, because the data is copied into the buffer with D3D11_MAP_WRITE_DISCARD (in _sg_d3d11_update_buffer()) or D3D11_MAP_WRITE_NO_OVERWRITE (in _sg_d3d11_append_buffer()), and in this case D3D does a similar buffer renaming under the hood.

For _sg_gl_update_buffer() you can see the buffer rotation here (each call ticks the "active_slot" forward):

https://github.com/floooh/sokol/blob/52e99842d3ec1050a198c4c4f29da4e1816e5ba7/sokol_gfx.h#L7759-L7761
