### ISSUE TITLE
Using 16 bit / RGBA4 framebuffer formats

### ISSUE THREAD

**Issue by OttoHatt** [floooh/sokol#686]
Hello, I'm making a retro-ish game in Sokol, one feature I'd like to emulate from older consoles is 16 -bit color depth. I think that this feature was [intentionally removed](https://github.com/floooh/sokol/blob/master/CHANGELOG.md#:~:text=packed%2016%2Dbit%20formats%20(like%20RGBA4)%20have%20been%20removed), so I'm definitely not asking for it to be supported (as I imagine due to various weird hardware requirements), but is there a good way I could hack this feature in myself? Thanks

**Comment by floooh** [comment]
A single 4-bit channel can be expanded to 8 bits like this (basically duplicate the bits in the lower and upper half of the 8-bit number):

uint8_t r8 = (r4<<4) | r4;

...but there's probably a bit twiddling hack which does this more efficiently from an uint16_t to an uint32_t.

**Comment by OttoHatt** [comment]
Thanks for the response! Sorry I don't mean to do any bit shifting by hand. I'm trying to set the framebuffer to use an [`RGBA4`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/renderbufferStorage#:~:text=renderbuffer.%20Possible%20values%3A-,gl.RGBA4,-%3A%204%20red%20bits) or `RGB4`-like format, so that each color channel only has 4 bits assigned to it. I think the lowest you can go right now is `RGBA8`, which is 8 bits per channel, [as `RGBA4` was removed a while ago](https://github.com/floooh/sokol/blob/master/CHANGELOG.md#:~:text=packed%2016%2Dbit%20formats%20(like%20RGBA4)%20have%20been%20removed). I'm trying to hack support back in for it?

**Comment by floooh** [comment]
Sorry I should have gone into a bit more detail :)

I would recommend you work with a regular RGBA8 framebuffer, but fill it with RGBA4 data that's "somehow" expanded to RGBA8.

First, if you use sokol_app.h you can't really define the default framebuffer pixel format anyway, this is always either RGBA8 or BGRA8, depending on platform.

Now the next question is how you are doing rendering: if you have a pixel framebuffer that's populated with the CPU (which is common for emulators), you would do the 16- to 32-bit expansion with the CPU, and then upload the data into a sokol_gfx.h texture. Quite expensive of course.

If you render tiles and sprite layers (or do 3D-rendering) with the GPU, then you would almost certainly use offline-generated sprite- and tile-sheets loaded into sokol_gfx.h textures. In this case there's also a couple of options:

1. You could use RGBA8 as offline texture format and expand the RGBA4 pixel data to RGBA8 offline while generating the sprite/tile sheet texture files.

2. Or you could encode the 16-bit RGBA4 data into a 2-channel 16-bit texture format SG_PIXELFORMAT_RG8 (two 8-bit channels), so the RG channels from the input RGBA4 format would go into the 8-bit R channel, and the input BA channels would go into the 8-bit G channel. This would need to be unpacked then in the pixel shader to RGBA: R=>RG, G=>BA. But be aware that this solution wouldn't work on GLES2/WebGL1 (because SG_PIXELFORMAT_RG8 isn't supported on GLES2/WebGL, only on GLES3/WebGL2).

...option 2 is highly preferrable of course, because the input textures would be 16-bits per pixel.

**Comment by pseregiet** [comment]
If you want to do retro (and therefore I assume 2D) game/engine then you should try using just SDL. I worked on a retro engine that did 256 colors (1 byte per pixel) in 640x480 and all the blits done in software. It ran at 30 fps on a pentium1 166mhz cpu (SDL1 still runs on Windows 98 :) ), 500+ on a normal modern computer (probably limited by the OS api at this point). Modern hardware doesn't support such low color depth modes anyway, even if you programmed your engine to use such modes "directly" the driver would just convert it to true color behind the scenes.
