### ISSUE TITLE
using sapp_frame_duration for dt

### ISSUE THREAD

**Issue by kariem2k** [floooh/sokol#688]
Hi sorry for the many questions 

Is sapp_frame_duration intended to be used to get dt passed to game play code? I see it being used in packman with fixed step calculations. 

Thanks

**Comment by floooh** [comment]
It depends how timing works in your gameplay code. In general, sapp_frame_duration() gives you less 'jitter' compared to measuring the frame duration yourself, since the time may be obtained from the swapchain, and it has some filtering applied on top to smooth any remaining jitter. How you use that information is up to you :)

To make your gameplay timing display refresh rate independent you'll need *some* sort of frame timing, and sapp_frame_duration() provides that (otherwise your game would run twice as fast on a 120Hz display than on a 60Hz display).
