### ISSUE TITLE
Layered text with sokol_fontstash.h

### ISSUE THREAD

**Issue by Larpon** [floooh/sokol#703]
Cheerio,

I've been trying to achieve **layered** text rendering with [sokol_fontstash.h](https://github.com/floooh/sokol/blob/master/util/sokol_fontstash.h) and couldn't quite get it to work out of the box.

My approach has been to preallocate a pool of FONScontext's with `sfons_create(...)` and hand out one each time text needed to be rendered in the frame call - and then "re-cycle" them at the end of each frame.

But calling `sfons_flush(FONScontext* ctx)` followed by `sgl_draw()` *multiple times* per frame yields:
```
sg_update_buffer: only one update allowed per buffer and frame
^^^^  SOKOL-GFX VALIDATION FAILED, TERMINATING ^^^^
```
The FONScontext in each flush call is unique and only used once per frame. So something in the above call sequence is calling `sg_update_buffer` more than once, apparently.

I can work around this by commenting out:
https://github.com/floooh/sokol/blob/efc3a2b3d89d1d6371e130dd2d1046c976a4a9cc/sokol_gfx.h#L14712
and
https://github.com/floooh/sokol/blob/efc3a2b3d89d1d6371e130dd2d1046c976a4a9cc/sokol_gfx.h#L15944

Which enables me to render text in a layered way:
![layered_text_sokol_fontstash](https://user-images.githubusercontent.com/768942/184090230-b6606510-1082-4224-bab1-eb23b6367335.gif)
(The above GIF is a run where the desired layered rendering is achieved, by applying the "patch")

I'm not sure how intentional it is to not be able to render layered text, maybe I'm doing something wrong?
If not - is there any other way to achieve, layered text rendering?

**Comment by floooh** [comment]
> My approach has been to preallocate a pool of FONScontext's with sfons_create(...) and hand out one each time text needed to be rendered in the frame call - and then "re-cycle" them at the end of each frame.

This sounds about right, but:

The problem is most likely not sokol_fontstash.h (because that doesn't call ```sg_update_buffer()```, but instead sokol_gl.h's ```sgl_draw()``` call (which does an ```sg_update_buffer()``` call, and must only be called once per frame).

You may need to create one sokol-gl context per fontstash-context (so that each call to ```sfons_flush()``` is paired with a call to ```sgl_context_draw()```).

The ```sgl-context-sapp``` sample demonstrates how to use multiple contexts with sokol-gl:

https://github.com/floooh/sokol-samples/blob/master/sapp/sgl-context-sapp.c

(however not together with layered text rendering, but for rendering into different render targets), also see this section of the sokol_gl.h documentation: https://github.com/floooh/sokol/blob/efc3a2b3d89d1d6371e130dd2d1046c976a4a9cc/util/sokol_gl.h#L384-L457)

**Comment by Larpon** [comment]
Beautiful :heart: - it works a charm without any nasty workarounds.

Thanks a lot for your time and in-depth answer!
