### ISSUE TITLE
Combining sokol_gl with sokol_gfx pipelines

### ISSUE THREAD

**Issue by tomas** [floooh/sokol#725]
Hi and thanks for your work in the sokol libraries. They're simply beautiful.

I'm trying to use `sokol_gfx` together with `sokol_gl` but haven't found many examples showing how to ([the imgui usercallback example](https://github.com/floooh/sokol-samples/blob/master/sapp/imgui-usercallback-sapp.c) is probably the most official one I could find). 

Specifically, I want to be able to draw shapes and lines using stuff like `sgl_begin_quads() and sgl_v2f_t2f()` but also be able to use shaders to draw images with simple effects applied on them. I haven't found a way to use a `sgl_pipeline` with a shader + texture, and I'm not sure if that's because sokol_gl isn't meant to cover that type of complexity or maybe because it's not possible and I'm just trying to put a round peg in a square hole.

In pseudocode this is what I pseudo-aim for:

```c
init() {
  sg_setup(...)
  sgl_setup(...)

  regular_pipeline = sgl_make_pipeline(...) // no shader, use default
  effects_pipeline = sgl_make_pipeline(...) // use custom shader

  image1 = sg_make_image(...)
  image2 = sg_make_image(...)
}

frame() {
  sgl_load_pipeline(regular_pipeline);
  draw_shapes();

  sgl_load_pipeline(effects_pipeline);
  sgl_texture(image_1)
  draw_image_quad(image_1, ...);

  sgl_texture(image_2)
  draw_image_quad(image_2, ...);
  
  sg_begin_default_pass(...)
  sgl_draw();
  sg_end_pass();
  sg_commit();
}
```

Is this possible? Can I pass a texture to a shader using `sgl_texture` or must I use `fs_images` when calling from `sg_apply_bindings`? If so, are there any other examples that might help?

Thanks in advance! And sorry for the long issue, hope this is the right place for posting this! :)

**Comment by floooh** [comment]
There is some limited support for injecting your own shader during sgl_make_pipeline() (due to the if() here: https://github.com/floooh/sokol/blob/a2f1113e391228962f1f9c23ffa74f3d02349fa4/util/sokol_gl.h#L2533-L2535), but the shader needs to use the same inputs as the builtin shaders (e.g. the expected vertex attributes, uniform blocks and textures must all be the same). 

Basically if your vertex shader must have this 'input signature':

https://github.com/floooh/sokol/blob/a2f1113e391228962f1f9c23ffa74f3d02349fa4/util/sokol_gl.h#L857-L864

..and the fragment shader must take a single texture:

https://github.com/floooh/sokol/blob/a2f1113e391228962f1f9c23ffa74f3d02349fa4/util/sokol_gl.h#L876

...it's still very fragile, and depends that the shader compiler will assign the inputs to the same bind slots, that's why this feature hasn't been documented.

In general, do not mix sokol-gl calls with sokol-gfx calls, the sokol-gl run on their own 'time line', because any sokol-gl calls will just be recorded into internal command- and vertex-buffers, and only 'played back' during sgl_draw().

**Comment by tomas** [comment]
I see, thanks for the detailed answer. 

It would be great to have this included in the documentation, or maybe add a working example to `sokol-samples` (I can send a PR if you're interested, when/if I manage to get this to work!).
