### ISSUE TITLE
D3D11: Forced Depth/Stencil Buffer 

### ISSUE THREAD

**Issue by StrangeZak** [floooh/sokol#729]
Hello there!

I'm working on a 2d application that does not require a depth or stencil buffer, as far as i can see Sokol doesn't support me not having one set (at least on d3d11). Is this by design, or would you be open to accepting a PR where the depth stencil buffer is optional. Not sure on the implications of adding support for this this. 

Thanks!
- Zak

**Comment by floooh** [comment]
It would be possible (and eventually desirable) to get more configuration options about the color and depth pixel format of the default framebuffer in sokol_app.h, but it's definitely not one of the low-hanging fruits ;) (it requires work across all backends, but doesn't have all that great benefits apart from saving some video memory).

For now, if you don't want to pay the fillrate overhead for the depth-stencil-buffer, just create your sokol-gfx pass actions with SG_ACTION_DONTCARE for the depth-stencil-buffer, and in pipeline objects, set ```sg_pipeline_desc.depth.write_enabled``` to false.

TBH, providing a D3D11-only PR for this now doesn't make much sense, the PR would most likely just rot for quite some time, because currently there are quite a few more pending PRs which I haven't merged yet.

**Comment by StrangeZak** [comment]
This fix worked perfectly, thank you!

Looking forward to this being optional in the future 🤞
