### ISSUE TITLE
unknown type name 'NSExtensionContext'; did you mean 'NSAnimationContext'

### ISSUE THREAD

**Issue by caiiiycuk** [floooh/sokol#732]
Hi. I am pretty sure that it's not a bug, I belive it's problem with compiler (clang) options. I am new in Mac OS development. I am trying to build js-dos/sokol on MacOs, but even simplest example generates this error:

```
In file included from /Volumes/macext/caiiiycuk/js-dos/emulators/native/dosbox-jsdos/sokol/protocol-sokol.cpp:11:
In file included from /Volumes/macext/caiiiycuk/js-dos/emulators/native/dosbox-jsdos/sokol/../../sokol/sokol_app.h:1853:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:27:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCollectionView.h:9:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSViewController.h:248:39: error: unknown type name 'NSExtensionContext'; did you mean 'NSAnimationContext'?
@property (nullable, readonly,retain) NSExtensionContext *extensionContext API_AVAILABLE(macos(10.10));
```

I used this clang options:
```
 -ObjC -mmacosx-version-min=10.11
```

Any help will be really appreciated. Thank you.

**Comment by floooh** [comment]
Hmm, I'm also on the 12.3 SDK, so it's probably not a regression in a recent Xcode version.

The sokol-samples readme here has instructions for how to build the samples without all the cmake magic:

https://github.com/floooh/sokol-samples#how-to-build-without-a-build-system

The macOS build instructions are right at the top, those instructions should work as-is also on M1 Macs if you have Rosetta installed (because the shader compiler path points to the Intel binaries, otherwise use the following path on M1 Macs: ``` ../../sokol-tools-bin/bin/osx_arm64/sokol-shdc```

I just tested those on my M1 Mac with Xcode 14.0.1 and the Xcode command line tools installed (via ```xcode-select --install```).

**Comment by caiiiycuk** [comment]
I fixed it somehow. I think it was because of mixing C++ and Objective C++ code.

**Comment by caiiiycuk** [comment]
Btw, thank you very much for detailed description. It helped me a lot.
