### ISSUE TITLE
Do you plan to offer rust bindings ?

### ISSUE THREAD

**Issue by DomDumont** [floooh/sokol#74]
Hi,
I would like to learn rust and , as I like minimalism, I would like to use sokol also ;-)
Do you plan to offer rust bindings ?
Thanks

**Comment by ElArtista** [comment]
Especially for the sokol_gfx module, this would be fantastic!

**Comment by floooh** [comment]
It's currently not high on my list since I haven't written any Rust for quite a while. It would be a good thing though, also for getting some experience how this type of API would be translated to Rust (I guess things like the desc structures would need builder-pattern interfaces in Rust).

I know that @waywardmonkeys has started a sokol-gfx inspired API for Rust (not a binding), but I don't know how far this is and if it is open.

**Comment by ElArtista** [comment]
Do you happen to know the project name, or if we can reach him on #rust in IRC by some handle?

**Comment by floooh** [comment]
I don't sorry, was hoping mentioning him would summon him to this thread so he could chime in :)

**Comment by waywardmonkeys** [comment]
Sorry, I was away for a few days in the countryside where internet was slow / painful!

The start that I had was at https://github.com/endoli/grafiska.rs

I had also started at one point doing some bindings around the C implementation using `bindgen`.

I would love to get some help with grafiska or movement behind doing actual bindings.

**Comment by floooh** [comment]
Btw, there's now this: https://github.com/code-disaster/sokol-rs

**Comment by EriKWDev** [comment]
And now: https://github.com/floooh/sokol-rust
