### ISSUE TITLE
sokol_time multithreading?

### ISSUE THREAD

**Issue by creikey** [floooh/sokol#742]
Is sokol_time threadsafe to initialize in one thread then use in others? If not, can the state be made a thread local variable so this is supported?

**Comment by floooh** [comment]
Theoretically yes, but only by accident - because all functions except stm_setup() only read from the global state that has been initialized in stm_setup(). *But* only the various platform-specific ways to query the time all use a common time source across threads, that's what I'm not sure about. But in terms of thread safety, it should be ok.
