### ISSUE TITLE
BUG：SAPP_EVENTTYPE_CHAR char_code is error

### ISSUE THREAD

**Issue by alittlesail** [floooh/sokol#746]
1. in windows x64
2. create app x64
3. enter Chinese '中'
4. why char_code = 0x004e002d ?
5. 0x00004e2d is correct

**Comment by alittlesail** [comment]
I try out，you can handle WM_IME_CHAR to fix this bug
            case WM_CHAR:
                _sapp_win32_char_event((uint32_t)wParam, !!(lParam&0x40000000));
                break;
// fix bug=======================
            case WM_IME_CHAR:  
                _sapp_win32_char_event((uint32_t)wParam, !!(lParam & 0x40000000));
                return 1;
// ========================
            case WM_KEYDOWN:
            case WM_SYSKEYDOWN:

**Comment by floooh** [comment]
Uh, 'next week' was a bit optimistic. Looking into this now :D

**Comment by floooh** [comment]
Ok, I think the problem was just that I called DispatchMessage() instead of DisplatchMessageW() here in the Windows message pump:

https://github.com/floooh/sokol/blob/c06a5430351a97b75c785bf264f6303786d9d6d8/sokol_app.h#L6325-L6328

With the DispatchMessageW() call, WM_CHAR seems to receive the correct UNICODE value.

Can you check if this fix works on your side (if not, please re-open the issue).

I'll see if I can come up with an UNICODE text input sample using fontstash.
