### ISSUE TITLE
sg_apply_uniform_block + ES2, apply flattened uniform block ..

### ISSUE THREAD

**Issue by septag** [floooh/sokol#75]
I'm flattening the uniform blocks for ES2 shaders,
currently what I see in source is that is goes through the uniform names and applies them individually..
Can sokol_gfx apply the whole block (vec4 array) for flattened uniform arrays ?

**Comment by floooh** [comment]
Yes, you basically need to tell sokol_gfx that the uniform block only contains a single vec4 array, instead of unique uniform block members, e.g.:

```c
        .vs.uniform_blocks[0] = {
            .size = sizeof(vs_params_t),
            .uniforms = {
                [0] = { 
                    .name="flattened_ub", 
                    .type=SG_UNIFORMTYPE_FLOAT4,
                    .array_count = num_vec4s_in_array,
                }
            }
        },
```
I'm doing this in the WIP Oryol branch which sits on top of sokol_gfx, together with shader code generation which flattens GLSL uniform blocks into vec4 arrays:

https://github.com/floooh/oryol/blob/4bc0d522a108c608d9fe1e574f8333354d81ef87/code/Modules/Gfx/private/sokol/sokolGfxBackend.cc#L751-L757
