### ISSUE TITLE
SDL_Gpu and Shader Compiling

### ISSUE THREAD

**Issue by RandyGaul** [floooh/sokol#752]
Hey there, hope you don't mind me asking this question here. I was quite interested in SDL's idea to implement a shader compiler (https://github.com/libsdl-org/SDL_shader_tools) so you could have one function for `SDL_GpuCompileShader`. After inspecting the rough sketch of the WIP 3D API (https://github.com/icculus/SDL/blob/gpu-api/include/SDL_gpu.h) it looks like it's mostly following Metal's API design and turned out very similar to sokol_gfx.h.

I'm wondering if you had any thoughts about potentially changing things up a bit with sokol_gfx. So far I'd say the most difficult part is hooking up the offline tool sokol-shdc. I find SDL's idea really cool. One thing I've seen done in single-file headers is to test to see if another header has been included yet, and offer some wrapper functions to hook it up if so. One idea is that maybe sokol_gfx.h could have a wrapping around creating a shader with SDL's shader compiler.

The whole SPIR-V thing just seems way too complex and overkill and has rather heavy dependencies.

Personally I'm wondering if SDL's strategy of generating bytecode is also overkill for the task at-hand. The vast majority of shaders myself and my colleagues are interested in are very simple shaders. In many cases I believe there to be fairly straightforward 1:1 mappings.

**Comment by floooh** [comment]
Yeah! I didn't really keep track of SDL_gpu progress recently, but if the shader compiler part can be ripped out and put into its own library, then I'll definitely add support for it to sokol_gfx.h somehow (an obvious first step would be to integrate it into sokol-shdc as a separate language frontend instead of GLSL).

For sokol_gfx.h integration, I would prefer to keep the current philosophy of feeding backend-specific shader blobs into the sokol-gfx API, but those backend specific shader blobs could be provided by a new header which wraps the SDL shader compiler into a sokol-friendly API (e.g. taking SDL shader sources as input and returning an sg_shader_desc struct which can be plugged directly into sg_make_shader()).
