### ISSUE TITLE
Make it more clear what coordinate system sokol is using

### ISSUE THREAD

**Issue by las3rlars** [floooh/sokol#771]
Hi,

Currently I can't really find anything saying if sokol is using a left handed (directx) or right handed (opengl) coordinate system.

It would also be nice to know what depth space is used. -1 to 1 or 0 to 1.

**Comment by floooh** [comment]
sokol-gfx doesn't care about coordinate system handedness, that's all between your math code on the CPU side and your shader code on the GPU side.

There are a couple of more subtle differences between backends though, which are also mostly ignored or 'passed through' by sokol-gfx though (except for the 'origin_top_left' argument in sg_apply_viewport() and sg_apply_scissor_rect()):

When sampling and rendering an offscreen-rendered texture in the GL backend, the image will appear on its head. With sokol-shdc, this can be fixed in the shader with the ```@glsl_options flip_vert_y``` tag.

The clip-space z-range in GL is -1.0 to +1.0, and in D3D11/Metal the clipspace z-range goes from 0.0 to +1.0, this can also be patched by sokol-shdc with ```@glsl_options fixup_clipspace```.

These are both SPIRVCross features to 'normalize' shader behaviour between different backends.

For sokol-shdc this is documented here: https://github.com/floooh/sokol-tools/blob/master/docs/sokol-shdc.md#glsl_options-hlsl_options-msl_options

...and for SPIRVCross it's documented here: https://github.com/KhronosGroup/SPIRV-Cross#clip-space-conventions

**Comment by las3rlars** [comment]
Thank you very much for a great explanation! Didn't know about the @gsl_options!
