### ISSUE TITLE
SetCursor event + window handle

### ISSUE THREAD

**Issue by septag** [floooh/sokol#78]
Hi,
I was wondering if sokol could implement SetCursor event for desktop apps
I don't know about linux/mac platforms, but in windows I'd like to use WM_SETCURSOR to change the cursor in gui (like imgui). I could add the support to windows easily by adding these lines to _sapp_win32_wndproc's switch:

```
            case WM_SETCURSOR:
                if (LOWORD(lParam) == HTCLIENT) {
                    _sapp_win32_app_event(SAPP_EVENTTYPE_SETCURSOR);
                    return 1;
                }
                break;
```

Also, is there any way to fetch the window handle in order to implement some extra functions like SetCapture, ReleaseCapture (for drag&drop)

**Comment by floooh** [comment]
Both are good suggestions. I didn't want to add complete custom-cursor-image support (at least not yet), so exposing an WM_SETCURSOR as event looks like a good step in that direction. I need to figure out how that would work on OSX and Linux (...basically what GLFW does).

For exposing the window handles (and maybe a few other things) I think it makes sense to add platform-specific functions (similar to the sapp_d3d11_* and sapp_metal_* functions that already exist).

For instance ```sapp_win32_get_hwnd()``` to get the Win32 HWND. It would have to return a 'neutral type', like 'const void*' or maybe better 'uintptr_t', because the function should still exist when compiling on non-Windows-platforms (but return zero there).

I'll try to look into this over the next days.

**Comment by floooh** [comment]
Ok, a first Windows version is in:

https://github.com/floooh/sokol/commit/656f085c11bccc602db6514470adcc23b3845d71

I had to add a member ".user_cursor" to the sapp_desc struct, and in order to receive SAPP_EVENTTYPE_UPDATE_CURSOR events you'll need to set this to true. The reason for this is that Windows won't update the mouse cursor anymore if WM_SETCURSOR returns with 1 (or TRUE), so I only do this when the user requests to manage the cursor image/visibility himself.

I also found a difference between MacOS and Windows: on Windows, WM_SETCURSOR is sent each frame when the mouse is moved inside the window client area. On Mac, a similar message is only sent once when the mouse enters the window.

In your use case, do you require the Windows behaviour (sent each frame when mouse moves in window), or would you be ok with only receiving a single message when the mouse enters the window?

**Comment by septag** [comment]
awesome, works in windows
thanks

**Comment by floooh** [comment]
Closing this, although "proper" cursor image handling would be nice. Should be a separate issue though.

**Comment by floooh** [comment]
Hi @septag sokol_app.h is getting "official" cursor types support now (basically the cursor images required by Dear ImGui, see: https://github.com/floooh/sokol/pull/678

Because of this I would like to remove the entire "user cursor" stuff (SAPP_EVENTTYPE_UPDATE_CURSOR and sapp_desc.user_cursor). Any objectsion from your side? :)
