### ISSUE TITLE
sokol_app.h output log grep in windows powershell not work.

### ISSUE THREAD

**Issue by likun123687** [floooh/sokol#786]
The sapp_desc option win32_console_attach and win32_console_utf8 both set true.
I use this cmd:
`sokol_app_cmd | Select-String "pattern"`
But the Select-string not work, it still print all log.
Is there any option setting make this work?

**Comment by floooh** [comment]
Yes, I can reproduce (also on a regular console and with rip-grep instead of Select-String), but I don't know why it behaves that way.

I guess the most robust solution would be to compile the program as a regular command line tool (with a main() entry point) instead of a Windows application with WinMain(). There's a ```SOKOL_WIN32_FORCE_MAIN``` config define for this.

**Comment by likun123687** [comment]
Ok, i will try that.
