### ISSUE TITLE
Add alternate #define for sokol_glue.h for bindgen reasons

### ISSUE THREAD

**Issue by kkukshtel** [floooh/sokol#798]
Hello! I'm generating bindings for Sokol with [this library](https://github.com/dotnet/ClangSharp) and am running into a small issue with sokol_glue.h when generating bindings with clang. Specifically, the `sapp_sgcontext()` function isn't exported unless `SOKOL_GFX_INCLUDED` and `SOKOL_APP_INCLUDED` are defined. The library I'm using specifically allows for setting those defines, but as I'm trying to generate bindings for all of Sokol in one shot, adding those defines means that the sokol_app and sokol_gfx functions aren't exported.

I know this sounds like a library specific issue, but it also seems useful for other bindgen cases for Sokol where you'd want to emit library functions regardless of the defines. Would it be possible to get some define for sokol_glue that allows emitting of `sapp_sgcontext()` regardless of `SOKOL_GFX_INCLUDED` and `SOKOL_APP_INCLUDED`? Or some define used for all the headers that is basically a big "API_EXPORT" define? Thanks!

**Comment by floooh** [comment]
Late reply (sorry I must have missed the ticket at the time):

In the official bindings generator I generally don't include sokol_glue.h in the bindings generation but instead provide a manually maintained replacement, like here:

https://github.com/floooh/sokol-zig/blob/master/src/sokol/app_gfx_glue.zig

The reason is exactly because sokol_glue.h does this funky conditional stuff depending on whether certain header implementations have been included or not.

Closing this ticket, because I think the manual solution is an okay-ish solution :)
