### ISSUE TITLE
Using `-s EXPORTED_FUNCTIONS="[]"` in emscripten breaks the assigned `sapp_emsc_target` (et al) symbols.

### ISSUE THREAD

**Issue by skejeton** [floooh/sokol#799]
I need to use `-s EXPORTED_FUNCTIONS="['_malloc', '_free']"` because emscripten doesn't export those symbols by default (https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3131---012623), but they are used by miniaudio accessed through JS.

Something causes this flag to overwrite/ignore existing sokol assigned symbols like `sapp_emsc_target`. Enabling this flag may be causing to generate some initialization code to assign those exported functions, somehow overwriting/ignoring sokol symbols in result.

**Comment by floooh** [comment]
This is weird. ```sapp_emsc_target``` is only used on the Javascript side as a global helper variable on the Emscripten ```Module``` object, this shouldn't interfere with the EXPORTED_FUNCTIONS mechanism.

What Emscripten SDK version are you on, and what's the exact error you are getting?

From looking at the Emscripten release notes, it looks like the very latest 'in development' release might cause trouble because this reads like ```EMSCRIPTEN_KEEPALIVE``` will no longer work out of the box: https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3133-in-development

...but this should break differently (all the C functions which are annotated with ```EMSCRIPTEN_KEEPALIVE``` will most likely break then, but ```sapp_emsc_target``` isn't such a C function.

**Comment by skejeton** [comment]
It seems like I was wrong. It doesn't overwrite `sapp_emsc_target`, the main never got executed in the first place. Adding `_main` to `EXPORTED_FUNCTIONS` fixed everything. For some reason using `EXPORTED_FUNCTIONS` removed `_main` by default. But so be it.
