### ISSUE TITLE
Automatically generating Rust bindings, comments and thoughts

### ISSUE THREAD

**Issue by EriKWDev** [floooh/sokol#802]
Hi!
I started working on a bindgen for Rust today that I'm basing on the current bindgen scripts, especially looking at `bindgen/gen_zig.py`

Rust is low-level enough to be similair to C in many aspects and I think it is a good candidate as an automatically generated binding. It supports C's ABI as well as C's memory layout of structs and enums.

There are some design decisions that have to be made for Rust such as how to handle c-style strings, how to implement default field values, how to represent opaque types, how to represent enums and how to handle lifetime semantics around all the pointers.

I will update here as I make more progress, but It would be nice to hear some feedback in case anyone here has already made some thoughts about this or have experience in making ergonomic rust-C bindings.

### Default struct field values
Default values are usually provided in rust through implementation of the `Default` trait. This trait is, however, not a `const fn` meaning it cannot always be guaranteed to be called at compile time. To mitigate this, I'm implementing the by-convention standard function `new` as a `const fn` and then calling if from the Default trait implementation.

I've also chosen to add derive implementations of Debug, Copy and Clone to be able to easily debug-print all structs as well as copy them (move by value, pointer dereference ...) 

The way this looks in code is for a given sturct `MyStruct`, it is implemented as such:
```rust
#[derive(Debug, Copy, Clone)]
#[repr(C)]
pub struct MyStryct {
    pub struct_field: TypeOne,
    pub array_field: [TypeTwo; 10],
    pub const_ptr: *const Type,
    pub normal_ptr: *mut Type,
    pub bool_field: bool,
}
impl MyStryct {
    pub const fn new() -> Self {
        Self {
            struct_field: TypeOne::new(),
            array_field: {
                const VAL: TypeTwo = TypeTwo::new();
                [VAL; 10]
            },
            const_ptr: std::ptr::null(),
            normal_ptr: std::ptr::null_mut(),
            bool_field: false,
        }
    }
}
impl Default for MyStruct {
    fn default() -> Self {
        Self::new()
    }
}
```

One could also call the much more straight-forward unsafe function [`std::mem::zeroed()`](https://doc.rust-lang.org/std/mem/fn.zeroed.html), though I'm not familiar enough with all the various implications of it for every type, so I'm sticking to the explicit zero-initialization way as shown above for now.

Also, `std::mem::zeroed()` isn't `const fn` either, so it still wouldn't address the issue of being able to create constants. One can ofc implement a macro that gives this functionality as seen here [const-zero crate](https://github.com/maxbla/const-zero).

The Default trait gives the ability to later in code initialize structs like this which is standard in rust:

```rust
let my_struct = MyStruct { bool_field: true, ..Default::default() };
```

### Enums
Simple enums in rust can specify what underlying int type they should use to be represented in memory. I saw the "FORCE_U32" item in the zig bindings, and in rust I chose to simply not include it and annotate enums as either to be represented as 'i32' or 'u32':

```rust
#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
#[repr(i32)]
pub enum Backend {
    Glcore33,
    Gles2,
    Gles3,
    D3d11,
    MetalIos,
    MetalMacos,
    MetalSimulator,
    Wgpu,
    Dummy,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ResourceState {
    Initial,
    Alloc,
    Valid,
    Failed,
    Invalid,
}
```
Alternatively, we could keep the exact same number of enum variants and add the last `ForceU32 = <value>` and use `#[repr(C)]` on the enum.  

I still haven't fully decided what to do with enum variants that start with a number in the name as this is not allowed in rust:
```rust
#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
#[repr(u32)]
pub enum ImageType {
    Default,
    2d, // !
    Cube,
    3d, // !
    Array,
    Num,
}
```
It would perhaps be most idiomatic to have special cases for them like `ImageType::Dim3D`, or `ImageType::ThreeD` etc. Zig solves this by calling them `_3D`, `_2D`, but I like the look of ThreeD more. Perhaps that should be saved for the more idiomatic bindings and not in the ffi.

Furthermore, it is also common to capitalize enum variants with PascalCase, even for short acronyms like `RGB` in accordance with [rust's naming conventions](https://rust-lang.github.io/api-guidelines/naming.html)

```rust
#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
#[repr(u32)]
pub enum PixelFormat {
    // ...
    R8sn,
    R8ui,
    R8si,
    R16,
    R16sn,
    R16ui,
    R16si,
    R16f,
    Rg8,
    Rg8sn,
    Rg8ui,
    Rg8si,
    R32ui,
    R32si,
    R32f,
    // ...
    Rg32ui,
    Rg32si,
    Rg32f,
    Rgba16,
    Rgba16sn,
    Rgba16ui,
    Rgba16si,
    Rgba16f,
    Rgba32ui,
    Rgba32si,
    Rgba32f,
   // ...
}
```

### Opaque types
Some functions, like `saudio_userdata` return void pointers to data that is opaque to sokol. While returning `*mut std::ffi::c_void` is the most straight forward way to translate this, one other way to model this in rust would be to return a pointer to the generic type T which would require the user to specify exactly what type they meant to acquire:

```rust
/// inside sokol/audio.rs

extern "C" {
    fn saudio_userdata() -> *mut std::ffi::c_void;
}
pub fn userdata<T>() -> *mut T {
    unsafe { saudio_userdata() as *mut T }
}
```

It will however inherently be an unsafe operation by rust standards so I will keep experimenting with other ways of expressing these.

Also, most of this is in the ffi Api, so maybe such functionality should be expressed in a higher-level and more idiomatic rust Api (That I hope to also be able to generate), so perhaps c_void will suffice for now:

```rust
pub unsafe fn userdata() -> *mut std::ffi::c_void {
    saudio_userdata()
}
```

### Constant numbers
Some sokol constants are modeled as enums without explicitly declaring what underlying type they should use
```c
enum {
    SG_INVALID_ID = 0,
    SG_NUM_SHADER_STAGES = 2,
    SG_NUM_INFLIGHT_FRAMES = 2,
    SG_MAX_COLOR_ATTACHMENTS = 4,
    SG_MAX_SHADERSTAGE_BUFFERS = 8,
    SG_MAX_SHADERSTAGE_IMAGES = 12,
    SG_MAX_SHADERSTAGE_UBS = 4,
    SG_MAX_UB_MEMBERS = 16,
    SG_MAX_VERTEX_ATTRIBUTES = 16,      /* NOTE: actual max vertex attrs can be less on GLES2, see sg_limits! */
    SG_MAX_MIPMAPS = 16,
    SG_MAX_TEXTUREARRAY_LAYERS = 128
};
```
In rust, constants have to declare their type explicitly, which is not the case in neither odin, zig or nim.  If I'm not mistaken, it is undefined in C what type an enum should have and is instead up to the compiler to decide. What type should we use in rust? `usize`?

```rust
pub const SG_INVALID_ID: usize = 0;
pub const SG_NUM_SHADER_STAGES: usize = 2;
pub const SG_NUM_INFLIGHT_FRAMES: usize = 2;
pub const SG_MAX_COLOR_ATTACHMENTS: usize = 4;
pub const SG_MAX_SHADERSTAGE_BUFFERS: usize = 8;
pub const SG_MAX_SHADERSTAGE_IMAGES: usize = 12;
pub const SG_MAX_SHADERSTAGE_UBS: usize = 4;
pub const SG_MAX_UB_MEMBERS: usize = 16;
pub const SG_MAX_VERTEX_ATTRIBUTES: usize = 16;
pub const SG_MAX_MIPMAPS: usize = 16;
pub const SG_MAX_TEXTUREARRAY_LAYERS: usize = 128;
```

### Lifetime semantics around allocated resources
It would be nice to utlize rust lifetimes for buffers, shaders, passes, images and so-on since it is common in rust to not manually call a dealloc/free for types and instead model it around lifetimes and the `Drop` trait. I will return once I have experimented more and welcome any ideas in this regard. 

### Error handling
It is common to express errors in rust using a `Result` type and hence make all fallable calls return this type (or an `Option`).

I'm personally not totally sold on making EVERY fallable function return a Result and I am more in favor of sometimes letting ergonomics win and let a runtime panic!() happen. However, for some cases it is a really neat way of modelling errors and I would like to investigate where it would be appropriate to utilize them.

**Comment by floooh** [comment]
Phew, lots of topics :D 

I haven't read through everything yet, but let me just give you a quick brain dump (because I also had started thinking about Rust bindings):

- **C-style strings** are indeed the main problem, the other bindings currently all target languages which have some sort of builtin support for zero-terminated string literals, which simplifies the problem. One thing that maybe simplifies the problem is that incoming C string pointers are just 'borrow references', e.g. in general the sokol headers copy any pointer-referenced data they need to hold on to. So the Rust wrapper functions could create heap- or stack-allocated (if possible) C-string with the additional 0-byte, call the C function, and then destroy the C-string object again.
- **Default struct values**: I would prefer the ```...Default::default()``` way (even though the default values would all be zero in the end)
- **Underlying enum type**: the other language bindins usually use i32 as the underlying type (e.g. in Zig: https://github.com/floooh/sokol-zig/blob/6367c1a291edbc3474a959c292f1fd3ce3ab684a/src/sokol/gfx.zig#L68-L83
- **Special enum values** (like 2D, 3D...), your choice :)
- **Userdata types**: I haven't thought about this topic yet, so if you find a good "Rusty" solution just go ahead with it :)
- **Constant types**: this is actually a bit tricky... SG_INVALID_ID is usually used together with the .id field in sg_buffer etc... and that's an u32. For the others, usize probably makes more sense, because they are often used as loop counters. If Rust requires an explicit cast when trying to stuff an usize constant into an u32 field, it probably makes sense to treat SG_INVALID_ID special.
- **Lifetime semantics**: this is the one point where I don't agree :) I would not try to create some sort of RAII wrapper around resource handles, instead just treat them as the weak references they are, they don't collide with Rust's lifetime or ownership system (you can freely clone or borrow sokol handles, and you can call the destroy functions even when there are still handles for that resource object somewhere out in the wild, nothing bad will happen in that case).
- **Error Handling**: Yeah, same problem as in Zig. In general, the definition of what error handling even means hasn't been defined until recently when a combined logging- and error-handling callback was added. The new 'philosophy' is that errors should be reported to the outside world, but not cause any catastrophic failure. Instead (for instance) when a resource object failed to be created (which returns an 'invalid handle', any followup API calls involving such an invalid handle should just report an error through the error callback, but then simply skip the supposed operation. I would suggest to hook into the logging/error-handling callback, and use Rust's logging facilities to log out any warning and errors (maybe with a callstack), and for panic-level errors, terminate execution via Rust's panic(), but I would not try (yet at least) to wrap the public APIs with functions that return error unions or optionals.

**Comment by floooh** [comment]
PS: btw there's an older manually created Rust binding here: https://github.com/code-disaster/sokol-rs

...maybe @code-disaster had some ideas you can steal ;)

**Comment by EriKWDev** [comment]
Update: We are compiling and running on Linux

![image](https://user-images.githubusercontent.com/19771356/224248050-2acf106b-eb01-4ca2-8d7b-b4d5d4b14dfc.png)

**Comment by EriKWDev** [comment]
![image](https://user-images.githubusercontent.com/19771356/224724299-acc9d9a2-80f1-47c4-8e52-7859326fa80d.png)

Cube example and the shader stuff translated to and running from rust. I think it would not be too hard to adda  rust target to the shader compiler as well.

**Comment by EriKWDev** [comment]
Update: I have written a rust frontend for the shader compiler as well and it works nicely
https://github.com/EriKWDev/sokol-rust/blob/main/sokolrust.cc

It can translate shaders from the other examples as-is and works nicely together with the rust bindings.

**Comment by EriKWDev** [comment]
@floooh: If I finish up translating all the examples and do some further testing, would you be willing to accept a PR with the `gen_rust.py` script added to the bindgen folder, and perhaps a PR to `sokol-tools` adding the rust frontend to the shader compiler?

Since everything is written the same way as the other bindgens it would be cool if the rust bindings could get the 'official'-stamp as well xP

I would ofc be willing to move the `ErikWDev/sokol-rust` repo to be under your ownership on GitHub as well if you so wish.

**Comment by code-disaster** [comment]
This looks very nice and clean! Much more clean actually than that weird SApp trait I was (probably way over-)engineering with my own bindings a few years back.

I wonder, did you have a chance to look at sokol_gfx_imgui yet? There are Rust bindings (you are still free of dependencies, and this would introduce one), but I remember `imgui-rs` somewhat fiddly to work with back when I was experimenting with that.

**Comment by EriKWDev** [comment]
I have not had time to checkout the imgui header yet, but I definitely intend to create bindings for the `utils` headers. Only debugtext is done currently since it was already implemented for the other bindings.

Will check the imgui header out tomorrow :)

Do you think there will be anything that will require extra attention regarding the imgui bindings specifically? I have no experience with the current rust bindings for imgui.

**Comment by EriKWDev** [comment]
@code-disaster: I got the sokol imgui bindings to be automatically generated and I can now use the unsafe `imgui-sys` crate from `imgui-rs` and get something to display:

![image](https://user-images.githubusercontent.com/19771356/225888748-48bf1d10-23a1-466a-8564-759cae83b7b3.png)

Compilation wasn't pretty and `imgui-rs` seems very picky about how the imgui context is managed. I'll have to see if there is any way to get the safe bindings to work

**Comment by EriKWDev** [comment]
Also update: Got cargo to compile it all with emscripten if we chose wasm/emscripten target

![image](https://user-images.githubusercontent.com/19771356/226097822-2a77a30b-94f8-4ad0-81e5-2544450db85b.png)

**Comment by floooh** [comment]
Wow nice progress :) I'm currently a bit distracted again with build system stuff. But if you bundle this up into a PR I'd be happy to merge and integrate with the automatic bindings generation GH Action stuff. I guess I should also create a floooh/sokol-rs repo to merge into so that it is consistent with the other bindings.

**Comment by EriKWDev** [comment]
No worries! It's been fun doing this project

> I guess I should also create a floooh/sokol-rs repo

Perhaps call it sokol-rust specifically to not conflict with the old `sokol-rs` bindings :)

**Comment by code-disaster** [comment]
Oh I'd happy to retire my old stuff. Maybe I can even figure out how to transfer the crate ownership, if you ever want to publish that way.

**Comment by floooh** [comment]
Ok, empty project here where you can create a PR against: https://github.com/floooh/sokol-rust
