### ISSUE TITLE
sokol_gfx : Clear color one frame behind

### ISSUE THREAD

**Issue by RandyGaul** [floooh/sokol#804]
I've wrapped sokol_gfx in a 2D framework. It has a built-in "default pass" that captures drawables and gets them on the screen. Something I'm struggling with is how the clear color cannot be set/changed after a pass has begun. Here's a snippet of running the framework:

```cpp
#include <cute.h>
using namespace Cute;

int main(int argc, char* argv[])
{
	// Create a window with a resolution of 640 x 480.
	int options = APP_OPTIONS_DEFAULT_GFX_CONTEXT | APP_OPTIONS_WINDOW_POS_CENTERED;
	Result result = make_app("Fancy Window Title", 0, 0, 640, 480, options, argv[0]);
	if (is_error(result)) return -1;

	while (app_is_running())
	{
		app_update();
		// All your game logic and updates go here...
		app_draw_onto_screen();
	}

	destroy_app();

	return 0;
}
```

You can see in the middle of the main loop is where user drawing occurs. When `app_update` is called the default pass is setup for getting content onto the screen. When `app_draw_onto_screen` is called the actual frame is prepared. This means any time the user tries to set the clear color it won't show up until one frame later, causing an off-by-one-frame bug.

What would you suggest to get around this? To me it would be ideal to have a separate function for clearing the screen. Attaching the clear color onto a pass doesn't map very well, and has so far has been quite difficult to deal with. Maybe there is another way?

**Comment by floooh** [comment]
Having a separate screen clear function wouldn't work with the Metal backend, because the clear operation is integral part of the 'begin pass' functionality (I think the original reason for this design decision is the tiled rendering GPU on iOS).

One advice that I also had to learn to hard way is to try and avoid interleaving non-rendering work with rendering work, e.g. this is why all the sokol 'utility headers' (like sokol_debugtext.h, sokol_spline.h, sokol_gl.h etc...) record their 'render work' internally into their own memory buffers or command lists, which means that most API functions can be called outside of sokol-gfx render passes.

And then those utility headers have some sort of 'draw' function which must be called inside a sokol-gfx render pass, and that's the only place which calls sokol-gfx rendering functions.

E.g. if at all possible move as much code that's not directly related to rendering out of sokol-gfx render passes.

One thing that's been rolling around in the back of my head but is fairly low on the todo list is to have a record/replay header sitting on top of sokol_gfx.h. The API of this header would look very similar to sokol-gfx, but the regular functions would just record into a command list (with the advantage that those functions can be called outside a sokol-gfx render pass), and then a 'draw' function would 'replay' the recorded commands by calling sokol-gfx functions inside a render pass.

A 'next gen' sokol-gfx would be entirely built around that idea of command lists, just like the modern 3D APIs, but it's interesting to note that simply exposing 'native' 3D APIs command buffers wouldn't actually solve your specific problem - you would still need to have the right clear color handy before starting to record work into a native 3D API command buffer.
