### ISSUE TITLE
Something wrong with UNFOCUSED and Imgui

### ISSUE THREAD

**Issue by voidware** [floooh/sokol#808]
Had to disable this event so that Widget focus works properly in Imgui. Weirdly, everything so far seems to work without it.

```
_SOKOL_PRIVATE EM_BOOL _sapp_emsc_blur_cb(int emsc_type, const EmscriptenFocusEvent* emsc_event, void* user_data) {
    _SOKOL_UNUSED(emsc_type);
    _SOKOL_UNUSED(emsc_event);
    _SOKOL_UNUSED(user_data);
#if 0
    if (_sapp_events_enabled()) {
        _sapp_init_event(SAPP_EVENTTYPE_UNFOCUSED);
        _sapp_call_event(&_sapp.event);
    }
#endif    
    return true;
}
```

Edit: Sorry, need to add this is with emscripten.

**Comment by floooh** [comment]
sokol_imgui.h forwards the SAPP_EVENTTYPE_FOCUSED/UNFOCUSED events to ```ImGuiIO::AddFocusEvent()```:

https://github.com/ocornut/imgui/blob/5f301914a0bbca018fcbab7065480e1ab2c38e23/imgui.h#L1985

...not sure yet why this would cause trouble though. There might be interference with browser tabs becoming inactive when they're no longer active (e.g. the sokol frame callback would no longer be called until the tab becomes active again).

**Comment by floooh** [comment]
Late followup: I was running into the same issue in my VSCode IDE extension (https://github.com/floooh/vscode-kcide). The reason was that the hidden HTML text input maintained by sokol_app.h generated focus events (I think this happened when allowing mouse events to bubble up, which was required for focusing a VSCode tab by clicking into it).

...that triggered all the input-related changes of the last week (which I think you are aware of).

Closing this ticket now.
