### ISSUE TITLE
Question: Where are mipmaps generated?

### ISSUE THREAD

**Issue by danielchasehooper** [floooh/sokol#902]
I don't see any calls to `glGenerateMipmap` in sokol_gfx. When and how do mipmaps get generated? Does that happen automatically as needed if a mipmap sampler object is bound with a texture that hasn't been mipmapped? Is there a way to force it to generate mipmaps at a convenient time (other than to do a dummy draw call)?

**Comment by floooh** [comment]
There's no support for generating mipmaps in sokol_gfx.h, mainly because it's not universally supported across APIs.

One thing I have in mind is a support header which offers helper functions for things like generating mipmaps (and mainly stuff like postprocessing-antialiasing).

The mipmap generation would come in two versions, one to be plugged into sg_image_desc (using 'raw' data in memory as input and running on the CPU), and another version which uses a render target texture as input, and would use render passes to generate the mipmap chain.

**Comment by danielchasehooper** [comment]
I see now this is a dupe of #102

**Comment by remorses** [comment]
Did you end up implementing the helper functions for post processing? I would love to see a postprocessing example for Sokol
