### ISSUE TITLE
sokol_app.h: multi-window support

### ISSUE THREAD

**Issue by floatms** [floooh/sokol#93]
As I understand it sokol_gfx already supports multiple windows (for GL at least), so it would be very nice to have multi-window support in sokol_app as well. 

I'm planning on writing an application with sokol_gfx that could benefit from having multiple window support and I would love to use sokol_app with it.  

How hard would it be to implement this, or is something like this already planned?

**Comment by floooh** [comment]
Hi, no plans for sokol_app.h so far, mainly because multiple windows wouldn't be doable or make much sense on web and mobile. It would also complicate the internals quite a bit (also since it would require a new / different approach for creating the 3D contexts / devices. GL is a bit special with its multiple contexts per application, and even this is quite brittle.

It would probably make more sense to create a fork (or new header), which specializes on desktop platforms.

**Comment by floatms** [comment]
Hey, thanks for clarifying. I had guessed that you wanted to prioritize web so I understand that this doesn't really fit into the design. Impressive work btw. 
If I can allocate some time I'll look into creating a desktop specialization.

Can you give any hints on how you would approach this, e.g. where to start looking for relevant code passages or differences between sapp and sgfx that would need to be resolved?

**Comment by G-glop** [comment]
You could get the relevant system calls from the examples in the [ImGui repo](https://github.com/ocornut/imgui/tree/viewport/examples). Currently it's implemented for Windows and OpenGL or DX9/10/11/12.

**Comment by floatms** [comment]
Thanks for the tip, I'll have a look.
I had hoped that I could just hack the relevant parts from sgfx, which already support gl context switching into sapp but I definitely have to look into this more.

**Comment by Alzathar** [comment]
You may know, but Sokol + GLFW + ImGui is a super combo to develop a multiple window application with a reactive user interface.

**Comment by floatms** [comment]
I've thought about that yes but I want to try out some experimental UI ideas so I had to sort out ImGui sadly.
Maybe I'll try out GLFW with sgfx and see how that goes.
Thanks a lot again to all of you!
