### ISSUE TITLE
Split sg_apply_draw_state() into sg_apply_pipeline() and sg_apply_bindings()

### ISSUE THREAD

**Issue by iboB** [floooh/sokol#96]
There's somewhat of a bug here:

https://github.com/floooh/sokol-samples/blob/d5b4eb20df36fc97162d193bd08987490dbb648b/sapp/imgui-sapp.cc#L315

ImGui commands can potentially have different textures (`ImDrawCmd::TextureId`). There are none in the demo, so this works, but sometimes different textures might be displayed in an ImGui image widget.

I think the only way to fix this now is by moving...

```
sg_apply_draw_state(&draw_state);
sg_apply_uniform_block(SG_SHADERSTAGE_VS, 0, &vs_params, sizeof(vs_params));
```

... to the innermost loop, before each draw call. 

On the other hand, the cost of resetting a texture is probably so big, that the lost performance is negligible, but still a penny saved is a penny earned. 

Do you think you're going to optimize this use-case?

**Comment by iboB** [comment]
Right. My question was basically: is this behavior intended?... or perhaps, rather, shall I expect `apply_draw_state` + `sg_apply_uniform_block` to always work as an optimistic draw call batcher (performing minimal required calls to `glUniform` calls, `glBindBuffer`, `glVertexAttribLocation`, and the rest)

**Comment by iboB** [comment]
... or perhaps this is not clear enough. Here is a naive implementation of apply_draw_state + uniform_block:

```
use the gpu program
for each buffer:
  bind buffer
for each attribute
  set attrib pointer
for each uniform:
  set uniform to gpu
etc...
```

Now, moving those functions to the inner loop will cause `use program` to be needlessly called tens of times per frame with the same program. 

Is this something you'll be looking to optimize?

Moreover imagine a use case in many 2D games which use a lot of spritesheets:

* add **all** vertices from the scene into a single vertex buffer in world space
* `for each object: draw`
* the draw function checks whether something besides the vertex offset has changed. It could be that two or more consecutive objects have the same physical texture and same other uniforms.
	*  In such case, only change the offset and automatically batch the two objects to be drawn with a single draw call on one of the following iterations
	* otherwise draw the current batch and prepare for a next one

can this be achieved with sokol_gfx?

**Comment by Alzathar** [comment]
I am not a GL expert but if I correctly understand the behavior of ImGui and Sokol, the approach discussed here is the only one to load supplementary textures related to ImGui commands (i.e ImGui::Image, etc.). On the other hand, you can have several images in the same texture (think about sprites). So you can check if the latest bound texture is the same as in the received ImGui command. If this is not the case, you can modify it and update the draw state in consequence.

**Comment by Alzathar** [comment]
Hum... I think you have to clarify your goal. I thought the problem was initially related to the performance of Sokol combined with ImGui. But it seems you are doing something else. 

Regarding your example with sprites, you may be interested in the [Paclone](http://floooh.github.io/oryol-samples/asmjs/Paclone.html) sample proposed with Oryol. Oryol is a C++ game engine proposed by @floooh with higher-level functions than Sokol.

**Comment by iboB** [comment]
oryol's rendering system is about to be changed, based on sokol_gfx. 

Anyway. I'm not trying to do anything in particular right now. I'm just trying to get a feel for the api's capabilities and design decisions.

**Comment by floooh** [comment]
I started working on this in a branch: https://github.com/floooh/sokol/tree/apply-pipeline, progress will be a bit slow over the next days though since I'm currently deep into emulator stuff.

It doesn't require all too many changes though, most work will be the GL vertex attribute definition, and in the validation layer. I'll keep the old functions and structs around so that old code doesn't break (and the old sg_apply_draw_state() basically only needs to call the new sg_apply_pipeline() followed by sg_apply_bindings()).

**Comment by floooh** [comment]
Good point, yes I'll implement something like this behind a macro... I might also make use of (compiler-specific) deprecated attributes like https://clang.llvm.org/docs/AttributeReference.html#deprecated.

**Comment by floooh** [comment]
Ok, this has now been merged to master, see this blog post for details:

https://floooh.github.io/2019/01/12/sokol-apply-pipeline.html
