### ISSUE TITLE
Some API requests (sokol_app.h)

### ISSUE THREAD

**Issue by nesbox** [floooh/sokol#97]
Hi, I'm working on migration to the _Sokol_ lib in my TIC-80 project, it's almost done, but I need some additional cross-platform API to finish it, like
- clipboard support (like `SDL_SetClipboardText()` in SDL2).
- get user data folder path (like `SDL_GetPrefPath()` in SDL2).
- how to go fullscreen in runtime.
- set window icon/title.
- set mouse system cursor (like HAND or IBEAM).
- don't know how properly handle app exit when a user closes the window.

What do you think, could it be added to the `sokol_app.h` in near future? Not a problem if not, I'll try to implement something on my side.

Thanks in advance.

**Comment by pixelherodev** [comment]
I can help with some of this - I have a fullscreen routine for the GLFW backend already if you need it

**Comment by floooh** [comment]
...I have started working on the "programmatic quit" topic:

https://github.com/floooh/sokol/pull/166

**Comment by floooh** [comment]
> clipboard support (like SDL_SetClipboardText() in SDL2).

This has been implemented for a while, although it's a bit awkward on HTML5.

> how to go fullscreen in runtime.

This also works now (see ```sapp_toggle_fullscreen()``` and ```sapp_is_fullscreen()```

> set window icon/title.

There's ```sapp_set_window_title()``` but currently no way to set the window icon (makes sense though)

> don't know how properly handle app exit when a user closes the window.

This can now also be intercepted, see ```SAPP_EVENTTYPE_QUIT_REQUESTED```, and this documention: https://github.com/floooh/sokol/blob/29bbcd84147e287c501fbcbdb105d56e7aee3934/sokol_app.h#L689-L763

> set mouse system cursor (like HAND or IBEAM).

This is sorta-kinda-possible on Mac and Windows with the SAPP_EVENTTYPE_UPDATE_CURSOR event, but requires calling platform-specific functions.

Since most of the list is fixed I'm setting the ticket to closed, and for the missing things we can open separate tickets if the topic comes up again :)

**Comment by nesbox** [comment]
Thank you, going to update it soon.
