### ISSUE TITLE
support for glReadPixels

### ISSUE THREAD

**Issue by eloraiby** [floooh/sokol#98]
using sokol as the backend for a little CAD app, it would be handful to have glReadPixels support. Any plans to add that ?

**Comment by floooh** [comment]
I wasn't planning this, since it's hard to do with other APIs than GL and not often needed.

You can add this quite easily yourself though, as an "extension function" in the source file where you include the sokol_gfx.h implementation (or you can create a small extension header for this, similar how I did it here for the 8-bit emulator stuff where I'm adding system-specific file format loading functions to a generic floppy disc drive emulation: https://github.com/floooh/chips/blob/master/chips/fdd_cpc.h)

The idea is basically that fdd_cpc.h is included *after* the generic fdd.h both for the declaration and implementation (since fdd_cpc.h needs access to the "private" implementation functions).

**Comment by eloraiby** [comment]
Thanks, I will do that :)
