### ISSUE TITLE
Use retained command buffer in sokol_gfx

### ISSUE THREAD

**Issue by danielchasehooper** [floooh/sokol#981]
We just ran into a tricky async bug that came down to the fact that sokol_gfx uses metal's `commandBufferWithUnretainedReferences`.

From looking at sokol_gfx code, I don't see why `commandBufferWithUnretainedReferences` couldn't be changed to `commandBuffer`. Making that change would dramatically simplify sokol's memory management and make it easier for users of the library to use the underlying commandBuffer directly. the change would allow the removal of `_sg_mtl_release_resource` and all related code that extends lifetimes until a certain frame number.

Am I missing something that prevents a switch to `commandBuffer` from being better all around?

related: #762

**Comment by floooh** [comment]
There's a pretty big performance overhead with memory-managed command buffers unfortunately.

Best we could do is to add a Metal-specific config flag to sg_setup() which then just switches out the `commandBufferWithUnretainedReferences` with `commandBuffer`.

**Comment by danielchasehooper** [comment]
What is the overhead due to? Is it more than an increment and decrement of the refcount for each resource?

**Comment by floooh** [comment]
Here's an old blog post (2014), in a stress-test the overhead for refcounting dropped from 20% (!) to 7% just by switching to `commandBufferWithUnretainedReferences` (the remaining 7% overhead could then be eliminated only updating buffer offsets instead of "rebinding" buffers for each uniform update - those remaining 7% were a side effect of using ARC though):

https://floooh.github.io/2016/01/14/metal-arc.html

If you just do a couple hundred draw calls, the overhead should matter much though.

**Comment by floooh** [comment]
Note: this will be fixed as 'drive-by-fix' in https://github.com/floooh/sokol/pull/985 via a new runtime config item `sg_desc.mtl_use_command_buffer_with_retained_references`.
